<?php // phpcs:ignore - @generation-checksum MX-CDMX-38
/**
 * State City List for CDMX - MX.
 *
 * City count: 38
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for CDMX - MX.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Azcapotzalco', 'wpdev-locations'),
	__('Benito Juarez', 'wpdev-locations'),
	__('Ciudad de México', 'wpdev-locations'),
	__('Col. Bosques de las Lomas', 'wpdev-locations'),
	__('Colonia Nativitas', 'wpdev-locations'),
	__('Colonia del Valle', 'wpdev-locations'),
	__('Coyoacán', 'wpdev-locations'),
	__('Cuauhtémoc', 'wpdev-locations'),
	__('Delegación Cuajimalpa de Morelos', 'wpdev-locations'),
	__('Gustavo A. Madero', 'wpdev-locations'),
	__('Gustavo Adolfo Madero', 'wpdev-locations'),
	__('Iztacalco', 'wpdev-locations'),
	__('Iztapalapa', 'wpdev-locations'),
	__('Lomas de Tepemecatl', 'wpdev-locations'),
	__('Magdalena Contreras', 'wpdev-locations'),
	__('Miguel Hidalgo', 'wpdev-locations'),
	__('Milpa Alta', 'wpdev-locations'),
	__('Polanco', 'wpdev-locations'),
	__('San Andrés Mixquic', 'wpdev-locations'),
	__('San Antonio Tecómitl', 'wpdev-locations'),
	__('San Bartolome Xicomulco', 'wpdev-locations'),
	__('San Francisco Tecoxpa', 'wpdev-locations'),
	__('San Juan Ixtayopan', 'wpdev-locations'),
	__('San Lorenzo Acopilco', 'wpdev-locations'),
	__('San Lorenzo Tlacoyucan', 'wpdev-locations'),
	__('San Miguel Ajusco', 'wpdev-locations'),
	__('San Miguel Topilejo', 'wpdev-locations'),
	__('San Pablo Oztotepec', 'wpdev-locations'),
	__('San Pedro Atocpan', 'wpdev-locations'),
	__('San Salvador Cuauhtenco', 'wpdev-locations'),
	__('Santa Ana Tlacotenco', 'wpdev-locations'),
	__('Santa Catarina Yecahuizotl', 'wpdev-locations'),
	__('Tetelco', 'wpdev-locations'),
	__('Tlalpan', 'wpdev-locations'),
	__('Tláhuac', 'wpdev-locations'),
	__('Venustiano Carranza', 'wpdev-locations'),
	__('Xochimilco', 'wpdev-locations'),
	__('Álvaro Obregón', 'wpdev-locations'),
);
