<?php // phpcs:ignore - @generation-checksum MX-ROO-64
/**
 * State City List for ROO - MX.
 *
 * City count: 64
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ROO - MX.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akumal', 'wpdev-locations'),
	__('Alfredo V. Bonfil', 'wpdev-locations'),
	__('Bacalar', 'wpdev-locations'),
	__('Benito Juárez', 'wpdev-locations'),
	__('Cacao', 'wpdev-locations'),
	__('Calderitas', 'wpdev-locations'),
	__('Cancún', 'wpdev-locations'),
	__('Caobas', 'wpdev-locations'),
	__('Carlos A. Madrazo', 'wpdev-locations'),
	__('Chetumal', 'wpdev-locations'),
	__('Chiquilá', 'wpdev-locations'),
	__('Chunhuhub', 'wpdev-locations'),
	__('Ciudad Chemuyil', 'wpdev-locations'),
	__('Coba', 'wpdev-locations'),
	__('Cocoyol', 'wpdev-locations'),
	__('Cozumel', 'wpdev-locations'),
	__('Dziuche', 'wpdev-locations'),
	__('Dzula', 'wpdev-locations'),
	__('El Tintal', 'wpdev-locations'),
	__('Felipe Carrillo Puerto', 'wpdev-locations'),
	__('Huay Max', 'wpdev-locations'),
	__('Huay-Pix', 'wpdev-locations'),
	__('Ignacio Zaragoza', 'wpdev-locations'),
	__('Isla Holbox', 'wpdev-locations'),
	__('Isla Mujeres', 'wpdev-locations'),
	__('Javier Rojo Gómez', 'wpdev-locations'),
	__('Jose Narciso Rovirosa', 'wpdev-locations'),
	__('José María Morelos', 'wpdev-locations'),
	__('Juan Sarabia', 'wpdev-locations'),
	__('Kancabchén', 'wpdev-locations'),
	__('Kantunilkín', 'wpdev-locations'),
	__('La Presumida', 'wpdev-locations'),
	__('La Unión', 'wpdev-locations'),
	__('Leona Vicario', 'wpdev-locations'),
	__('Los Divorciados', 'wpdev-locations'),
	__('Lázaro Cárdenas', 'wpdev-locations'),
	__('Maya Balam', 'wpdev-locations'),
	__('Morocoy', 'wpdev-locations'),
	__('Nicolás Bravo', 'wpdev-locations'),
	__('Nuevo Xcán', 'wpdev-locations'),
	__('Othón P. Blanco', 'wpdev-locations'),
	__('Playa del Carmen', 'wpdev-locations'),
	__('Polyuc', 'wpdev-locations'),
	__('Presidente Juárez', 'wpdev-locations'),
	__('Pucté', 'wpdev-locations'),
	__('Puerto Aventuras', 'wpdev-locations'),
	__('Saban', 'wpdev-locations'),
	__('Sabidos', 'wpdev-locations'),
	__('San Angel', 'wpdev-locations'),
	__('Santa Rosa Segundo', 'wpdev-locations'),
	__('Sergio Butrón Casas', 'wpdev-locations'),
	__('Señor', 'wpdev-locations'),
	__('Subteniente López', 'wpdev-locations'),
	__('Tepich', 'wpdev-locations'),
	__('Tihosuco', 'wpdev-locations'),
	__('Tulum', 'wpdev-locations'),
	__('Ucum', 'wpdev-locations'),
	__('X Cabil', 'wpdev-locations'),
	__('X-Hazil Sur', 'wpdev-locations'),
	__('X-pichil', 'wpdev-locations'),
	__('Xul-Ha', 'wpdev-locations'),
	__('Zacalaca', 'wpdev-locations'),
	__('Zona Urbana Ejido Isla Mujeres', 'wpdev-locations'),
	__('Álvaro Obregón', 'wpdev-locations'),
);
