<?php // phpcs:ignore - @generation-checksum CN-GS-20
/**
 * State City List for GS - CN.
 *
 * City count: 20
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for GS - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Baiyin', 'wpdev-locations'),
	__('Beidao', 'wpdev-locations'),
	__('Dingxi Shi', 'wpdev-locations'),
	__('Hezuo', 'wpdev-locations'),
	__('Jiayuguan', 'wpdev-locations'),
	__('Jinchang', 'wpdev-locations'),
	__('Jiuquan', 'wpdev-locations'),
	__('Lanzhou', 'wpdev-locations'),
	__('Laojunmiao', 'wpdev-locations'),
	__('Linxia Chengguanzhen', 'wpdev-locations'),
	__('Linxia Huizu Zizhizhou', 'wpdev-locations'),
	__('Longnan Shi', 'wpdev-locations'),
	__('Mawu', 'wpdev-locations'),
	__('Pingliang', 'wpdev-locations'),
	__('Qincheng', 'wpdev-locations'),
	__('Qingyang Shi', 'wpdev-locations'),
	__('Tianshui', 'wpdev-locations'),
	__('Wuwei', 'wpdev-locations'),
	__('Zhangye', 'wpdev-locations'),
	__('Zhangye Shi', 'wpdev-locations'),
);
