<?php // phpcs:ignore - @generation-checksum CN-GX-28
/**
 * State City List for GX - CN.
 *
 * City count: 28
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for GX - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Babu', 'wpdev-locations'),
	__('Baihe', 'wpdev-locations'),
	__('Baise City', 'wpdev-locations'),
	__('Baise Shi', 'wpdev-locations'),
	__('Beihai', 'wpdev-locations'),
	__('Chongzuo Shi', 'wpdev-locations'),
	__('Dazhai', 'wpdev-locations'),
	__('Fangchenggang Shi', 'wpdev-locations'),
	__('Guigang', 'wpdev-locations'),
	__('Guilin', 'wpdev-locations'),
	__('Guilin Shi', 'wpdev-locations'),
	__('Guiping', 'wpdev-locations'),
	__('Hechi Shi', 'wpdev-locations'),
	__('Jinji', 'wpdev-locations'),
	__('Laibin', 'wpdev-locations'),
	__('Lianzhou', 'wpdev-locations'),
	__('Lingcheng', 'wpdev-locations'),
	__('Liuzhou Shi', 'wpdev-locations'),
	__('Luorong', 'wpdev-locations'),
	__('Nandu', 'wpdev-locations'),
	__('Nanning', 'wpdev-locations'),
	__('Pingnan', 'wpdev-locations'),
	__('Pumiao', 'wpdev-locations'),
	__('Qinzhou', 'wpdev-locations'),
	__('Wuzhou', 'wpdev-locations'),
	__('Yangshuo', 'wpdev-locations'),
	__('Yashan', 'wpdev-locations'),
	__('Yulin', 'wpdev-locations'),
);
