<?php // phpcs:ignore - @generation-checksum CN-GZ-54
/**
 * State City List for GZ - CN.
 *
 * City count: 54
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for GZ - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Anshun', 'wpdev-locations'),
	__('Aoshi', 'wpdev-locations'),
	__('Bahuang', 'wpdev-locations'),
	__('Baishi', 'wpdev-locations'),
	__('Bangdong', 'wpdev-locations'),
	__('Benchu', 'wpdev-locations'),
	__('Bijie', 'wpdev-locations'),
	__('Chadian', 'wpdev-locations'),
	__('Changsha', 'wpdev-locations'),
	__('Chumi', 'wpdev-locations'),
	__('Dabachang', 'wpdev-locations'),
	__('Darong', 'wpdev-locations'),
	__('Dundong', 'wpdev-locations'),
	__('Duyun', 'wpdev-locations'),
	__('Gaoniang', 'wpdev-locations'),
	__('Gaowu', 'wpdev-locations'),
	__('Gaozeng', 'wpdev-locations'),
	__('Guandu', 'wpdev-locations'),
	__('Guiyang', 'wpdev-locations'),
	__('Hongzhou', 'wpdev-locations'),
	__('Huaqiu', 'wpdev-locations'),
	__('Lantian', 'wpdev-locations'),
	__('Liangcunchang', 'wpdev-locations'),
	__('Liupanshui', 'wpdev-locations'),
	__('Longlisuo', 'wpdev-locations'),
	__('Loushanguan', 'wpdev-locations'),
	__('Maoping', 'wpdev-locations'),
	__('Ouyang', 'wpdev-locations'),
	__('Pingjiang', 'wpdev-locations'),
	__('Qiandongnan Miao and Dong Autonomous Prefecture', 'wpdev-locations'),
	__('Qianxinan Bouyeizu Miaozu Zizhizhou', 'wpdev-locations'),
	__('Qimeng', 'wpdev-locations'),
	__('Qinglang', 'wpdev-locations'),
	__('Runsong', 'wpdev-locations'),
	__('Sanchahe', 'wpdev-locations'),
	__('Sangmu', 'wpdev-locations'),
	__('Shiqian', 'wpdev-locations'),
	__('Songkan', 'wpdev-locations'),
	__('Tingdong', 'wpdev-locations'),
	__('Tonggu', 'wpdev-locations'),
	__('Tongren', 'wpdev-locations'),
	__('Tongren Diqu', 'wpdev-locations'),
	__('Weining', 'wpdev-locations'),
	__('Wenshui', 'wpdev-locations'),
	__('Xiajiang', 'wpdev-locations'),
	__('Xiaoweizhai', 'wpdev-locations'),
	__('Xinzhan', 'wpdev-locations'),
	__('Xishan', 'wpdev-locations'),
	__('Xujiaba', 'wpdev-locations'),
	__('Yangtou', 'wpdev-locations'),
	__('Youyupu', 'wpdev-locations'),
	__('Zhongchao', 'wpdev-locations'),
	__('Zhujiachang', 'wpdev-locations'),
	__('Zunyi', 'wpdev-locations'),
);
