<?php // phpcs:ignore - @generation-checksum CN-JL-52
/**
 * State City List for JL - CN.
 *
 * City count: 52
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for JL - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Baicheng', 'wpdev-locations'),
	__('Baishan', 'wpdev-locations'),
	__('Baishishan', 'wpdev-locations'),
	__('Changchun', 'wpdev-locations'),
	__('Changling', 'wpdev-locations'),
	__('Chaoyang', 'wpdev-locations'),
	__('Dalai', 'wpdev-locations'),
	__('Dashitou', 'wpdev-locations'),
	__('Dehui', 'wpdev-locations'),
	__('Dongfeng', 'wpdev-locations'),
	__('Dunhua', 'wpdev-locations'),
	__('Erdaojiang', 'wpdev-locations'),
	__('Fuyu', 'wpdev-locations'),
	__('Gongzhuling', 'wpdev-locations'),
	__('Guangming', 'wpdev-locations'),
	__('Helong', 'wpdev-locations'),
	__('Hepingjie', 'wpdev-locations'),
	__('Huadian', 'wpdev-locations'),
	__('Huangnihe', 'wpdev-locations'),
	__('Huinan', 'wpdev-locations'),
	__('Hunchun', 'wpdev-locations'),
	__('Jilin', 'wpdev-locations'),
	__('Jishu', 'wpdev-locations'),
	__('Jiutai', 'wpdev-locations'),
	__('Ji’an', 'wpdev-locations'),
	__('Kaitong', 'wpdev-locations'),
	__('Liaoyuan', 'wpdev-locations'),
	__('Linjiang', 'wpdev-locations'),
	__('Lishu', 'wpdev-locations'),
	__('Liuhe', 'wpdev-locations'),
	__('Longjing', 'wpdev-locations'),
	__('Meihekou', 'wpdev-locations'),
	__('Mingyue', 'wpdev-locations'),
	__('Minzhu', 'wpdev-locations'),
	__('Panshi', 'wpdev-locations'),
	__('Sanchazi', 'wpdev-locations'),
	__('Shuangyang', 'wpdev-locations'),
	__('Shulan', 'wpdev-locations'),
	__('Siping', 'wpdev-locations'),
	__('Songjianghe', 'wpdev-locations'),
	__('Songyuan', 'wpdev-locations'),
	__('Tonghua', 'wpdev-locations'),
	__('Tonghua Shi', 'wpdev-locations'),
	__('Tumen', 'wpdev-locations'),
	__('Wangqing', 'wpdev-locations'),
	__('Xinglongshan', 'wpdev-locations'),
	__('Yanbian Chaoxianzu Zizhizhou', 'wpdev-locations'),
	__('Yanji', 'wpdev-locations'),
	__('Yantongshan', 'wpdev-locations'),
	__('Yushu', 'wpdev-locations'),
	__('Zhengjiatun', 'wpdev-locations'),
	__('Zhenlai', 'wpdev-locations'),
);
