<?php // phpcs:ignore - @generation-checksum CN-JS-13
/**
 * State City List for JS - CN.
 *
 * City count: 13
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for JS - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('ChangZhou', 'wpdev-locations'),
	__('HuaiAn', 'wpdev-locations'),
	__('LianYunGang', 'wpdev-locations'),
	__('NanJing', 'wpdev-locations'),
	__('NanTong', 'wpdev-locations'),
	__('SuQian', 'wpdev-locations'),
	__('SuZhou', 'wpdev-locations'),
	__('TaiZhou', 'wpdev-locations'),
	__('WuXi', 'wpdev-locations'),
	__('XuZhou', 'wpdev-locations'),
	__('YanCheng', 'wpdev-locations'),
	__('YangZhou', 'wpdev-locations'),
	__('ZhenJiang', 'wpdev-locations'),
);
