<?php // phpcs:ignore - @generation-checksum CN-NM-33
/**
 * State City List for NM - CN.
 *
 * City count: 33
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NM - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Baotou', 'wpdev-locations'),
	__('Bayan Nur', 'wpdev-locations'),
	__('Bayannur Shi', 'wpdev-locations'),
	__('Beichengqu', 'wpdev-locations'),
	__('Chifeng', 'wpdev-locations'),
	__('Dongsheng', 'wpdev-locations'),
	__('Erenhot', 'wpdev-locations'),
	__('E’erguna', 'wpdev-locations'),
	__('Genhe', 'wpdev-locations'),
	__('Hailar', 'wpdev-locations'),
	__('Hohhot', 'wpdev-locations'),
	__('Hulunbuir Region', 'wpdev-locations'),
	__('Jalai Nur', 'wpdev-locations'),
	__('Jiagedaqi', 'wpdev-locations'),
	__('Jining', 'wpdev-locations'),
	__('Manzhouli', 'wpdev-locations'),
	__('Mositai', 'wpdev-locations'),
	__('Mujiayingzi', 'wpdev-locations'),
	__('Ordos', 'wpdev-locations'),
	__('Ordos Shi', 'wpdev-locations'),
	__('Oroqen Zizhiqi', 'wpdev-locations'),
	__('Pingzhuang', 'wpdev-locations'),
	__('Salaqi', 'wpdev-locations'),
	__('Shiguai', 'wpdev-locations'),
	__('Tongliao', 'wpdev-locations'),
	__('Ulanhot', 'wpdev-locations'),
	__('Wenquan', 'wpdev-locations'),
	__('Wuda', 'wpdev-locations'),
	__('Wuhai', 'wpdev-locations'),
	__('Xilin Gol Meng', 'wpdev-locations'),
	__('Xilin Hot', 'wpdev-locations'),
	__('Yakeshi', 'wpdev-locations'),
	__('Zhalantun', 'wpdev-locations'),
);
