<?php // phpcs:ignore - @generation-checksum CN-SC-49
/**
 * State City List for SC - CN.
 *
 * City count: 49
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SC - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aba Zangzu Qiangzu Zizhizhou', 'wpdev-locations'),
	__('Barkam', 'wpdev-locations'),
	__('Bazhong Shi', 'wpdev-locations'),
	__('Changchi', 'wpdev-locations'),
	__('Chengdu', 'wpdev-locations'),
	__('Chonglong', 'wpdev-locations'),
	__('Dadukou', 'wpdev-locations'),
	__('Dazhou', 'wpdev-locations'),
	__('Deyang', 'wpdev-locations'),
	__('Dongxi', 'wpdev-locations'),
	__('Fangting', 'wpdev-locations'),
	__('Fubao', 'wpdev-locations'),
	__('Gaoping', 'wpdev-locations'),
	__('Garzê Zangzu Zizhizhou', 'wpdev-locations'),
	__('Guangyuan', 'wpdev-locations'),
	__('Guang’an', 'wpdev-locations'),
	__('Jiancheng', 'wpdev-locations'),
	__('Jiangyou', 'wpdev-locations'),
	__('Jiannan', 'wpdev-locations'),
	__('Kangding', 'wpdev-locations'),
	__('Langzhong', 'wpdev-locations'),
	__('Leshan', 'wpdev-locations'),
	__('Liangshan Yizu Zizhizhou', 'wpdev-locations'),
	__('Linqiong', 'wpdev-locations'),
	__('Luocheng', 'wpdev-locations'),
	__('Luzhou', 'wpdev-locations'),
	__('Meishan Shi', 'wpdev-locations'),
	__('Mianyang', 'wpdev-locations'),
	__('Nanchong', 'wpdev-locations'),
	__('Nanlong', 'wpdev-locations'),
	__('Neijiang', 'wpdev-locations'),
	__('Panzhihua', 'wpdev-locations'),
	__('Puji', 'wpdev-locations'),
	__('Shuanghejiedao', 'wpdev-locations'),
	__('Suining', 'wpdev-locations'),
	__('Taihe', 'wpdev-locations'),
	__('Taiping', 'wpdev-locations'),
	__('Tianpeng', 'wpdev-locations'),
	__('Tongchuan', 'wpdev-locations'),
	__('Xialiang', 'wpdev-locations'),
	__('Xiantan', 'wpdev-locations'),
	__('Xichang', 'wpdev-locations'),
	__('Xunchang', 'wpdev-locations'),
	__('Yanjiang', 'wpdev-locations'),
	__('Yibin', 'wpdev-locations'),
	__('Yucheng', 'wpdev-locations'),
	__('Zengjia', 'wpdev-locations'),
	__('Zhongba', 'wpdev-locations'),
	__('Zigong', 'wpdev-locations'),
);
