<?php // phpcs:ignore - @generation-checksum CN-SD-90
/**
 * State City List for SD - CN.
 *
 * City count: 90
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SD - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Anqiu', 'wpdev-locations'),
	__('Beizhai', 'wpdev-locations'),
	__('Bianzhuang', 'wpdev-locations'),
	__('Binzhou', 'wpdev-locations'),
	__('Boshan', 'wpdev-locations'),
	__('Changqing', 'wpdev-locations'),
	__('Chengqu', 'wpdev-locations'),
	__('Chengtangcun', 'wpdev-locations'),
	__('Chengyang', 'wpdev-locations'),
	__('Dengying', 'wpdev-locations'),
	__('Dengzhou', 'wpdev-locations'),
	__('Dezhou', 'wpdev-locations'),
	__('Dingtao', 'wpdev-locations'),
	__('Dongcun', 'wpdev-locations'),
	__('Dongdu', 'wpdev-locations'),
	__('Feicheng', 'wpdev-locations'),
	__('Gaomi', 'wpdev-locations'),
	__('Hanting', 'wpdev-locations'),
	__('Heze', 'wpdev-locations'),
	__('Jiamaying', 'wpdev-locations'),
	__('Jiaozhou', 'wpdev-locations'),
	__('Jiehu', 'wpdev-locations'),
	__('Jimo', 'wpdev-locations'),
	__('Jinan', 'wpdev-locations'),
	__('Jining', 'wpdev-locations'),
	__('Juye', 'wpdev-locations'),
	__('Kuiju', 'wpdev-locations'),
	__('Kutao', 'wpdev-locations'),
	__('Laiwu', 'wpdev-locations'),
	__('Laixi', 'wpdev-locations'),
	__('Laiyang', 'wpdev-locations'),
	__('Laizhou', 'wpdev-locations'),
	__('Laocheng', 'wpdev-locations'),
	__('Liaocheng', 'wpdev-locations'),
	__('Linqu', 'wpdev-locations'),
	__('Linyi', 'wpdev-locations'),
	__('Longgang', 'wpdev-locations'),
	__('Mengyin', 'wpdev-locations'),
	__('Mingshui', 'wpdev-locations'),
	__('Mizhou', 'wpdev-locations'),
	__('Nanding', 'wpdev-locations'),
	__('Nanma', 'wpdev-locations'),
	__('Ninghai', 'wpdev-locations'),
	__('Ningyang', 'wpdev-locations'),
	__('Pingdu', 'wpdev-locations'),
	__('Pingyi', 'wpdev-locations'),
	__('Pingyin', 'wpdev-locations'),
	__('Qingdao', 'wpdev-locations'),
	__('Qingnian', 'wpdev-locations'),
	__('Qingshancun', 'wpdev-locations'),
	__('Qingyang', 'wpdev-locations'),
	__('Qingzhou', 'wpdev-locations'),
	__('Qufu', 'wpdev-locations'),
	__('Rizhao', 'wpdev-locations'),
	__('Shancheng', 'wpdev-locations'),
	__('Shanting', 'wpdev-locations'),
	__('Shazikou', 'wpdev-locations'),
	__('Shengli', 'wpdev-locations'),
	__('Shilaorencun', 'wpdev-locations'),
	__('Shizilu', 'wpdev-locations'),
	__('Shouguang', 'wpdev-locations'),
	__('Sishui', 'wpdev-locations'),
	__('Suozhen', 'wpdev-locations'),
	__('Tai’an', 'wpdev-locations'),
	__('Taozhuang', 'wpdev-locations'),
	__('Tianfu', 'wpdev-locations'),
	__('Weifang', 'wpdev-locations'),
	__('Weihai', 'wpdev-locations'),
	__('Wenshang', 'wpdev-locations'),
	__('Xiazhen', 'wpdev-locations'),
	__('Xiazhuang', 'wpdev-locations'),
	__('Xiliguantun', 'wpdev-locations'),
	__('Xindian', 'wpdev-locations'),
	__('Xintai', 'wpdev-locations'),
	__('Yanggu', 'wpdev-locations'),
	__('Yanta', 'wpdev-locations'),
	__('Yantai', 'wpdev-locations'),
	__('Yanzhou', 'wpdev-locations'),
	__('Yatou', 'wpdev-locations'),
	__('Yinzhu', 'wpdev-locations'),
	__('Yishui', 'wpdev-locations'),
	__('Yucheng', 'wpdev-locations'),
	__('Zaozhuang', 'wpdev-locations'),
	__('Zhaoyuan', 'wpdev-locations'),
	__('Zhoucheng', 'wpdev-locations'),
	__('Zhoucun', 'wpdev-locations'),
	__('Zhu Cheng City', 'wpdev-locations'),
	__('Zhuangyuan', 'wpdev-locations'),
	__('Zibo', 'wpdev-locations'),
	__('Zoucheng', 'wpdev-locations'),
);
