<?php // phpcs:ignore - @generation-checksum CN-SX-18
/**
 * State City List for SX - CN.
 *
 * City count: 18
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SX - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Changzhi', 'wpdev-locations'),
	__('Datong', 'wpdev-locations'),
	__('Datong Shi', 'wpdev-locations'),
	__('Gutao', 'wpdev-locations'),
	__('Jiexiu', 'wpdev-locations'),
	__('Jincheng', 'wpdev-locations'),
	__('Jinzhong Shi', 'wpdev-locations'),
	__('Linfen', 'wpdev-locations'),
	__('Lüliang', 'wpdev-locations'),
	__('Shuozhou', 'wpdev-locations'),
	__('Taiyuan', 'wpdev-locations'),
	__('Xintian', 'wpdev-locations'),
	__('Xinzhi', 'wpdev-locations'),
	__('Xinzhou', 'wpdev-locations'),
	__('Yangquan', 'wpdev-locations'),
	__('Yuanping', 'wpdev-locations'),
	__('Yuci', 'wpdev-locations'),
	__('Yuncheng', 'wpdev-locations'),
);
