<?php // phpcs:ignore - @generation-checksum CN-TJ-69
/**
 * State City List for TJ - CN.
 *
 * City count: 69
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TJ - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Badaogu', 'wpdev'),
	__('Baijian', 'wpdev'),
	__('Bamencheng', 'wpdev'),
	__('Bangjun', 'wpdev'),
	__('Beicang', 'wpdev'),
	__('Beihuaidian', 'wpdev'),
	__('Beilizigu', 'wpdev'),
	__('Biaokou', 'wpdev'),
	__('Binhai New Area', 'wpdev'),
	__('Caijiapu', 'wpdev'),
	__('Caodian', 'wpdev'),
	__('Chabaihu', 'wpdev'),
	__('Changtun', 'wpdev'),
	__('Chengtougu', 'wpdev'),
	__('Chitu', 'wpdev'),
	__('Cuijiamatou', 'wpdev'),
	__('Dadunqiu', 'wpdev'),
	__('Dakoutun', 'wpdev'),
	__('Dashentang', 'wpdev'),
	__('Dawangtai', 'wpdev'),
	__('Daxinzhuang', 'wpdev'),
	__('Dazhongzhuang', 'wpdev'),
	__('Dongditou', 'wpdev'),
	__('Dongshigu', 'wpdev'),
	__('Erwangzhuang', 'wpdev'),
	__('Fanzhuang', 'wpdev'),
	__('Fengtai (Ninghe)', 'wpdev'),
	__('Fuzhuang', 'wpdev'),
	__('Gaojingzhuang', 'wpdev'),
	__('Hanjiashu', 'wpdev'),
	__('Hebeitun', 'wpdev'),
	__('Hexiwu', 'wpdev'),
	__('Huangcaotuo', 'wpdev'),
	__('Huantuo', 'wpdev'),
	__('Huogezhuang', 'wpdev'),
	__('Jiangwakou', 'wpdev'),
	__('Lianzhuang', 'wpdev'),
	__('Lintingkou', 'wpdev'),
	__('Liujiading', 'wpdev'),
	__('Liukuaizhuang', 'wpdev'),
	__('Liuzikou', 'wpdev'),
	__('Luotuofangzi', 'wpdev'),
	__('Meichang', 'wpdev'),
	__('Mengquan', 'wpdev'),
	__('Panzhuang', 'wpdev'),
	__('Qingguang', 'wpdev'),
	__('Sangzi', 'wpdev'),
	__('Shangcang', 'wpdev'),
	__('Shimianzhuang', 'wpdev'),
	__('Shuangjiang', 'wpdev'),
	__('Sigaozhuang', 'wpdev'),
	__('Tianjin', 'wpdev'),
	__('Touying', 'wpdev'),
	__('Wangqinzhuang', 'wpdev'),
	__('Weiwangzhuang', 'wpdev'),
	__('Xiawuqi', 'wpdev'),
	__('Xiditou', 'wpdev'),
	__('Xinkaikou', 'wpdev'),
	__('Xitazhuang', 'wpdev'),
	__('Yangjinzhuang', 'wpdev'),
	__('Yangliuqing', 'wpdev'),
	__('Yinliu', 'wpdev'),
	__('Yixingfu', 'wpdev'),
	__('Youguzhuang', 'wpdev'),
	__('Yuelongzhuang', 'wpdev'),
	__('Yuguzhuang', 'wpdev'),
	__('Zaojiacheng', 'wpdev'),
	__('Zhangjiawo', 'wpdev'),
	__('Zhaoguli', 'wpdev'),
);
