<?php // phpcs:ignore - @generation-checksum CN-TW-52
/**
 * State City List for TW - CN.
 *
 * City count: 52
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TW - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Baoying', 'wpdev-locations'),
	__('Changshu City', 'wpdev-locations'),
	__('Changzhou', 'wpdev-locations'),
	__('Chengxiang', 'wpdev-locations'),
	__('Dazhong', 'wpdev-locations'),
	__('Dongkan', 'wpdev-locations'),
	__('Dongtai', 'wpdev-locations'),
	__('Fengxian', 'wpdev-locations'),
	__('Gaogou', 'wpdev-locations'),
	__('Gaoyou', 'wpdev-locations'),
	__('Guiren', 'wpdev-locations'),
	__('Haizhou', 'wpdev-locations'),
	__('Hede', 'wpdev-locations'),
	__("Huai'an", 'wpdev-locations'),
	__('Huai’an Shi', 'wpdev-locations'),
	__('Huilong', 'wpdev-locations'),
	__('Hutang', 'wpdev-locations'),
	__('Jiangyan', 'wpdev-locations'),
	__('Jiangyin', 'wpdev-locations'),
	__('Jingjiang', 'wpdev-locations'),
	__('Jinsha', 'wpdev-locations'),
	__('Juegang', 'wpdev-locations'),
	__('Kunshan', 'wpdev-locations'),
	__('Lianyungang Shi', 'wpdev-locations'),
	__('Licheng', 'wpdev-locations'),
	__('Mudu', 'wpdev-locations'),
	__('Nanjing', 'wpdev-locations'),
	__('Nantong', 'wpdev-locations'),
	__('Pizhou', 'wpdev-locations'),
	__('Qinnan', 'wpdev-locations'),
	__('Rucheng', 'wpdev-locations'),
	__('Sanmao', 'wpdev-locations'),
	__('Songling', 'wpdev-locations'),
	__('Suicheng', 'wpdev-locations'),
	__('Suzhou', 'wpdev-locations'),
	__('Taixing', 'wpdev-locations'),
	__('Taizhou', 'wpdev-locations'),
	__('Tongshan', 'wpdev-locations'),
	__('Wuxi', 'wpdev-locations'),
	__('Xiannü', 'wpdev-locations'),
	__('Xiaolingwei', 'wpdev-locations'),
	__('Xinghua', 'wpdev-locations'),
	__('Xinpu', 'wpdev-locations'),
	__('Yancheng', 'wpdev-locations'),
	__('Yangzhou', 'wpdev-locations'),
	__('Yicheng', 'wpdev-locations'),
	__('Yushan', 'wpdev-locations'),
	__('Zhangjiagang', 'wpdev-locations'),
	__('Zhenjiang', 'wpdev-locations'),
	__('Zhenzhou', 'wpdev-locations'),
	__('Zhongxing', 'wpdev-locations'),
	__('Zhouzhuang', 'wpdev-locations'),
);
