<?php // phpcs:ignore - @generation-checksum BR-AC-22
/**
 * State City List for AC - BR.
 *
 * City count: 22
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AC - BR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Acrelândia', 'wpdev-locations'),
	__('Assis Brasil', 'wpdev-locations'),
	__('Brasiléia', 'wpdev-locations'),
	__('Bujari', 'wpdev-locations'),
	__('Capixaba', 'wpdev-locations'),
	__('Cruzeiro do Sul', 'wpdev-locations'),
	__('Epitaciolândia', 'wpdev-locations'),
	__('Feijó', 'wpdev-locations'),
	__('Jordão', 'wpdev-locations'),
	__('Manoel Urbano', 'wpdev-locations'),
	__('Marechal Thaumaturgo', 'wpdev-locations'),
	__('Mâncio Lima', 'wpdev-locations'),
	__('Plácido de Castro', 'wpdev-locations'),
	__('Porto Acre', 'wpdev-locations'),
	__('Porto Walter', 'wpdev-locations'),
	__('Rio Branco', 'wpdev-locations'),
	__('Rodrigues Alves', 'wpdev-locations'),
	__('Santa Rosa do Purus', 'wpdev-locations'),
	__('Sena Madureira', 'wpdev-locations'),
	__('Senador Guiomard', 'wpdev-locations'),
	__('Tarauacá', 'wpdev-locations'),
	__('Xapuri', 'wpdev-locations'),
);
