<?php // phpcs:ignore - @generation-checksum BR-ES-79
/**
 * State City List for ES - BR.
 *
 * City count: 79
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ES - BR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Afonso Cláudio', 'wpdev-locations'),
	__('Alegre', 'wpdev-locations'),
	__('Alfredo Chaves', 'wpdev-locations'),
	__('Alto Rio Novo', 'wpdev-locations'),
	__('Anchieta', 'wpdev-locations'),
	__('Apiacá', 'wpdev-locations'),
	__('Aracruz', 'wpdev-locations'),
	__('Atílio Vivacqua', 'wpdev-locations'),
	__('Baixo Guandu', 'wpdev-locations'),
	__('Barra de São Francisco', 'wpdev-locations'),
	__('Boa Esperança', 'wpdev-locations'),
	__('Bom Jesus do Norte', 'wpdev-locations'),
	__('Brejetuba', 'wpdev-locations'),
	__('Cachoeiro de Itapemirim', 'wpdev-locations'),
	__('Cariacica', 'wpdev-locations'),
	__('Castelo', 'wpdev-locations'),
	__('Colatina', 'wpdev-locations'),
	__('Conceição da Barra', 'wpdev-locations'),
	__('Conceição do Castelo', 'wpdev-locations'),
	__('Divino de São Lourenço', 'wpdev-locations'),
	__('Domingos Martins', 'wpdev-locations'),
	__('Dores do Rio Preto', 'wpdev-locations'),
	__('Ecoporanga', 'wpdev-locations'),
	__('Fundão', 'wpdev-locations'),
	__('Governador Lindenberg', 'wpdev-locations'),
	__('Guarapari', 'wpdev-locations'),
	__('Guaçuí', 'wpdev-locations'),
	__('Ibatiba', 'wpdev-locations'),
	__('Ibiraçu', 'wpdev-locations'),
	__('Ibitirama', 'wpdev-locations'),
	__('Iconha', 'wpdev-locations'),
	__('Irupi', 'wpdev-locations'),
	__('Itaguaçu', 'wpdev-locations'),
	__('Itapemirim', 'wpdev-locations'),
	__('Itarana', 'wpdev-locations'),
	__('Iúna', 'wpdev-locations'),
	__('Jaguaré', 'wpdev-locations'),
	__('Jerônimo Monteiro', 'wpdev-locations'),
	__('Jetibá', 'wpdev-locations'),
	__('João Neiva', 'wpdev-locations'),
	__('Laranja da Terra', 'wpdev-locations'),
	__('Linhares', 'wpdev-locations'),
	__('Mantenópolis', 'wpdev-locations'),
	__('Marataizes', 'wpdev-locations'),
	__('Marechal Floriano', 'wpdev-locations'),
	__('Marilândia', 'wpdev-locations'),
	__('Mimoso do Sul', 'wpdev-locations'),
	__('Montanha', 'wpdev-locations'),
	__('Mucurici', 'wpdev-locations'),
	__('Muniz Freire', 'wpdev-locations'),
	__('Muqui', 'wpdev-locations'),
	__('Nova Venécia', 'wpdev-locations'),
	__('Pancas', 'wpdev-locations'),
	__('Pedro Canário', 'wpdev-locations'),
	__('Pinheiros', 'wpdev-locations'),
	__('Piúma', 'wpdev-locations'),
	__('Ponto Belo', 'wpdev-locations'),
	__('Presidente Kennedy', 'wpdev-locations'),
	__('Rio Bananal', 'wpdev-locations'),
	__('Rio Novo do Sul', 'wpdev-locations'),
	__('Santa Leopoldina', 'wpdev-locations'),
	__('Santa Maria de Jetibá', 'wpdev-locations'),
	__('Santa Teresa', 'wpdev-locations'),
	__('Serra', 'wpdev-locations'),
	__('Sooretama', 'wpdev-locations'),
	__('São Domingos do Norte', 'wpdev-locations'),
	__('São Gabriel da Palha', 'wpdev-locations'),
	__('São José do Calçado', 'wpdev-locations'),
	__('São Mateus', 'wpdev-locations'),
	__('São Roque do Canaã', 'wpdev-locations'),
	__('Vargem Alta', 'wpdev-locations'),
	__('Venda Nova do Imigrante', 'wpdev-locations'),
	__('Viana', 'wpdev-locations'),
	__('Vila Pavão', 'wpdev-locations'),
	__('Vila Valério', 'wpdev-locations'),
	__('Vila Velha', 'wpdev-locations'),
	__('Vitória', 'wpdev-locations'),
	__('Água Doce do Norte', 'wpdev-locations'),
	__('Águia Branca', 'wpdev-locations'),
);
