<?php // phpcs:ignore - @generation-checksum BR-MS-82
/**
 * State City List for MS - BR.
 *
 * City count: 82
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MS - BR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alcinópolis', 'wpdev-locations'),
	__('Amambai', 'wpdev-locations'),
	__('Anastácio', 'wpdev-locations'),
	__('Anaurilândia', 'wpdev-locations'),
	__('Angélica', 'wpdev-locations'),
	__('Antônio João', 'wpdev-locations'),
	__('Aparecida do Taboado', 'wpdev-locations'),
	__('Aquidauana', 'wpdev-locations'),
	__('Aral Moreira', 'wpdev-locations'),
	__('Bandeirantes', 'wpdev-locations'),
	__('Bataguassu', 'wpdev-locations'),
	__('Bataiporã', 'wpdev-locations'),
	__('Batayporã', 'wpdev-locations'),
	__('Bela Vista', 'wpdev-locations'),
	__('Bodoquena', 'wpdev-locations'),
	__('Bonito', 'wpdev-locations'),
	__('Brasilândia', 'wpdev-locations'),
	__('Caarapó', 'wpdev-locations'),
	__('Camapuã', 'wpdev-locations'),
	__('Campo Grande', 'wpdev-locations'),
	__('Campo Verde', 'wpdev-locations'),
	__('Caracol', 'wpdev-locations'),
	__('Cassilândia', 'wpdev-locations'),
	__('Chapadão do Sul', 'wpdev-locations'),
	__('Corguinho', 'wpdev-locations'),
	__('Coronel Sapucaia', 'wpdev-locations'),
	__('Corumbá', 'wpdev-locations'),
	__('Costa Rica', 'wpdev-locations'),
	__('Coxim', 'wpdev-locations'),
	__('Deodápolis', 'wpdev-locations'),
	__('Dois Irmãos do Buriti', 'wpdev-locations'),
	__('Douradina', 'wpdev-locations'),
	__('Dourados', 'wpdev-locations'),
	__('Eldorado', 'wpdev-locations'),
	__('Figueirão', 'wpdev-locations'),
	__('Fátima do Sul', 'wpdev-locations'),
	__('Glória de Dourados', 'wpdev-locations'),
	__('Guia Lopes da Laguna', 'wpdev-locations'),
	__('Iguatemi', 'wpdev-locations'),
	__('Inocência', 'wpdev-locations'),
	__('Itaporã', 'wpdev-locations'),
	__('Itaquiraí', 'wpdev-locations'),
	__('Ivinhema', 'wpdev-locations'),
	__('Japorã', 'wpdev-locations'),
	__('Jaraguari', 'wpdev-locations'),
	__('Jardim', 'wpdev-locations'),
	__('Jateí', 'wpdev-locations'),
	__('Juti', 'wpdev-locations'),
	__('Ladário', 'wpdev-locations'),
	__('Laguna Carapã', 'wpdev-locations'),
	__('Maracaju', 'wpdev-locations'),
	__('Miranda', 'wpdev-locations'),
	__('Mundo Novo', 'wpdev-locations'),
	__('Naviraí', 'wpdev-locations'),
	__('Nioaque', 'wpdev-locations'),
	__('Nova Alvorada do Sul', 'wpdev-locations'),
	__('Nova Andradina', 'wpdev-locations'),
	__('Novo Horizonte do Sul', 'wpdev-locations'),
	__('Paranaíba', 'wpdev-locations'),
	__('Paranhos', 'wpdev-locations'),
	__('Paraíso das Águas', 'wpdev-locations'),
	__('Pedro Gomes', 'wpdev-locations'),
	__('Ponta Porã', 'wpdev-locations'),
	__('Porto Murtinho', 'wpdev-locations'),
	__('Pôrto Barra do Ivinheima', 'wpdev-locations'),
	__('Ribas do Rio Pardo', 'wpdev-locations'),
	__('Rio Brilhante', 'wpdev-locations'),
	__('Rio Negro', 'wpdev-locations'),
	__('Rio Verde de Mato Grosso', 'wpdev-locations'),
	__('Rochedo', 'wpdev-locations'),
	__('Santa Rita do Pardo', 'wpdev-locations'),
	__('Selvíria', 'wpdev-locations'),
	__('Sete Quedas', 'wpdev-locations'),
	__('Sidrolândia', 'wpdev-locations'),
	__('Sonora', 'wpdev-locations'),
	__('São Gabriel do Oeste', 'wpdev-locations'),
	__('Tacuru', 'wpdev-locations'),
	__('Taquarussu', 'wpdev-locations'),
	__('Terenos', 'wpdev-locations'),
	__('Três Lagoas', 'wpdev-locations'),
	__('Vicentina', 'wpdev-locations'),
	__('Água Clara', 'wpdev-locations'),
);
