<?php // phpcs:ignore - @generation-checksum BR-RJ-94
/**
 * State City List for RJ - BR.
 *
 * City count: 94
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for RJ - BR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Angra dos Reis', 'wpdev-locations'),
	__('Aperibé', 'wpdev-locations'),
	__('Araruama', 'wpdev-locations'),
	__('Areal', 'wpdev-locations'),
	__('Armação dos Búzios', 'wpdev-locations'),
	__('Arraial do Cabo', 'wpdev-locations'),
	__('Barra Mansa', 'wpdev-locations'),
	__('Barra do Piraí', 'wpdev-locations'),
	__('Belford Roxo', 'wpdev-locations'),
	__('Bom Jardim', 'wpdev-locations'),
	__('Bom Jesus do Itabapoana', 'wpdev-locations'),
	__('Cabo Frio', 'wpdev-locations'),
	__('Cachoeiras de Macacu', 'wpdev-locations'),
	__('Cambuci', 'wpdev-locations'),
	__('Campos dos Goytacazes', 'wpdev-locations'),
	__('Cantagalo', 'wpdev-locations'),
	__('Carapebus', 'wpdev-locations'),
	__('Cardoso Moreira', 'wpdev-locations'),
	__('Carmo', 'wpdev-locations'),
	__('Casimiro de Abreu', 'wpdev-locations'),
	__('Comendador Levy Gasparian', 'wpdev-locations'),
	__('Conceição de Macabu', 'wpdev-locations'),
	__('Cordeiro', 'wpdev-locations'),
	__('Duas Barras', 'wpdev-locations'),
	__('Duque de Caxias', 'wpdev-locations'),
	__('Engenheiro Paulo de Frontin', 'wpdev-locations'),
	__('Guapimirim', 'wpdev-locations'),
	__('Iguaba Grande', 'wpdev-locations'),
	__('Ilha Grande', 'wpdev-locations'),
	__('Itaboraí', 'wpdev-locations'),
	__('Itaguaí', 'wpdev-locations'),
	__('Italva', 'wpdev-locations'),
	__('Itaocara', 'wpdev-locations'),
	__('Itaperuna', 'wpdev-locations'),
	__('Itatiaia', 'wpdev-locations'),
	__('Japeri', 'wpdev-locations'),
	__('Laje do Muriaé', 'wpdev-locations'),
	__('Macaé', 'wpdev-locations'),
	__('Macuco', 'wpdev-locations'),
	__('Magé', 'wpdev-locations'),
	__('Mangaratiba', 'wpdev-locations'),
	__('Maricá', 'wpdev-locations'),
	__('Mendes', 'wpdev-locations'),
	__('Mesquita', 'wpdev-locations'),
	__('Miguel Pereira', 'wpdev-locations'),
	__('Miracema', 'wpdev-locations'),
	__('Natividade', 'wpdev-locations'),
	__('Nilópolis', 'wpdev-locations'),
	__('Niterói', 'wpdev-locations'),
	__('Nova Friburgo', 'wpdev-locations'),
	__('Nova Iguaçu', 'wpdev-locations'),
	__('Paracambi', 'wpdev-locations'),
	__('Paraty', 'wpdev-locations'),
	__('Paraíba do Sul', 'wpdev-locations'),
	__('Paty do Alferes', 'wpdev-locations'),
	__('Petrópolis', 'wpdev-locations'),
	__('Pinheiral', 'wpdev-locations'),
	__('Piraí', 'wpdev-locations'),
	__('Porciúncula', 'wpdev-locations'),
	__('Porto Real', 'wpdev-locations'),
	__('Quatis', 'wpdev-locations'),
	__('Queimados', 'wpdev-locations'),
	__('Quissamã', 'wpdev-locations'),
	__('Resende', 'wpdev-locations'),
	__('Rio Bonito', 'wpdev-locations'),
	__('Rio Claro', 'wpdev-locations'),
	__('Rio das Flores', 'wpdev-locations'),
	__('Rio das Ostras', 'wpdev-locations'),
	__('Rio de Janeiro', 'wpdev-locations'),
	__('Santa Maria Madalena', 'wpdev-locations'),
	__('Santo Antônio de Pádua', 'wpdev-locations'),
	__('Sapucaia', 'wpdev-locations'),
	__('Saquarema', 'wpdev-locations'),
	__('Seropédica', 'wpdev-locations'),
	__('Silva Jardim', 'wpdev-locations'),
	__('Sumidouro', 'wpdev-locations'),
	__('São Fidélis', 'wpdev-locations'),
	__('São Francisco de Itabapoana', 'wpdev-locations'),
	__('São Gonçalo', 'wpdev-locations'),
	__('São José de Ubá', 'wpdev-locations'),
	__('São José do Vale do Rio Preto', 'wpdev-locations'),
	__('São João da Barra', 'wpdev-locations'),
	__('São João de Meriti', 'wpdev-locations'),
	__('São Pedro', 'wpdev-locations'),
	__('São Pedro da Aldeia', 'wpdev-locations'),
	__('São Sebastião do Alto', 'wpdev-locations'),
	__('Tanguá', 'wpdev-locations'),
	__('Teresópolis', 'wpdev-locations'),
	__('Trajano de Moraes', 'wpdev-locations'),
	__('Três Rios', 'wpdev-locations'),
	__('Valença', 'wpdev-locations'),
	__('Varre-Sai', 'wpdev-locations'),
	__('Vassouras', 'wpdev-locations'),
	__('Volta Redonda', 'wpdev-locations'),
);
