<?php // phpcs:ignore - @generation-checksum BR-RO-56
/**
 * State City List for RO - BR.
 *
 * City count: 56
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for RO - BR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__("Alta Floresta d'Oeste", 'wpdev-locations'),
	__('Alto Alegre dos Parecis', 'wpdev-locations'),
	__('Alto Paraíso', 'wpdev-locations'),
	__("Alvorada d'Oeste", 'wpdev-locations'),
	__('Ariquemes', 'wpdev-locations'),
	__('Buritis', 'wpdev-locations'),
	__('Cabixi', 'wpdev-locations'),
	__('Cacaulândia', 'wpdev-locations'),
	__('Cacoal', 'wpdev-locations'),
	__('Campo Novo de Rondônia', 'wpdev-locations'),
	__('Candeias do Jamari', 'wpdev-locations'),
	__('Castanheiras', 'wpdev-locations'),
	__('Cerejeiras', 'wpdev-locations'),
	__('Chupinguaia', 'wpdev-locations'),
	__('Colorado do Oeste', 'wpdev-locations'),
	__('Corumbiara', 'wpdev-locations'),
	__('Costa Marques', 'wpdev-locations'),
	__('Cujubim', 'wpdev-locations'),
	__("Espigão d'Oeste", 'wpdev-locations'),
	__('Extrema', 'wpdev-locations'),
	__('Governador Jorge Teixeira', 'wpdev-locations'),
	__('Guajará Mirim', 'wpdev-locations'),
	__('Guajará-Mirim', 'wpdev-locations'),
	__('Itapuã do Oeste', 'wpdev-locations'),
	__('Jaru', 'wpdev-locations'),
	__('Ji Paraná', 'wpdev-locations'),
	__('Ji-Paraná', 'wpdev-locations'),
	__("Machadinho d'Oeste", 'wpdev-locations'),
	__('Ministro Andreazza', 'wpdev-locations'),
	__('Mirante da Serra', 'wpdev-locations'),
	__('Monte Negro', 'wpdev-locations'),
	__("Nova Brasilândia d'Oeste", 'wpdev-locations'),
	__('Nova Mamoré', 'wpdev-locations'),
	__('Nova União', 'wpdev-locations'),
	__('Novo Horizonte do Oeste', 'wpdev-locations'),
	__('Ouro Preto do Oeste', 'wpdev-locations'),
	__('Parecis', 'wpdev-locations'),
	__('Pimenta Bueno', 'wpdev-locations'),
	__('Pimenteiras do Oeste', 'wpdev-locations'),
	__('Porto Velho', 'wpdev-locations'),
	__('Presidente Médici', 'wpdev-locations'),
	__('Primavera de Rondônia', 'wpdev-locations'),
	__('Pôsto Fiscal Rolim de Moura', 'wpdev-locations'),
	__('Rio Crespo', 'wpdev-locations'),
	__('Rolim de Moura', 'wpdev-locations'),
	__("Santa Luzia d'Oeste", 'wpdev-locations'),
	__('Seringueiras', 'wpdev-locations'),
	__("São Felipe d'Oeste", 'wpdev-locations'),
	__('São Francisco do Guaporé', 'wpdev-locations'),
	__('São Miguel do Guaporé', 'wpdev-locations'),
	__('Teixeirópolis', 'wpdev-locations'),
	__('Theobroma', 'wpdev-locations'),
	__('Urupá', 'wpdev-locations'),
	__('Vale do Anari', 'wpdev-locations'),
	__('Vale do Paraíso', 'wpdev-locations'),
	__('Vilhena', 'wpdev-locations'),
);
