<?php // phpcs:ignore - @generation-checksum NE-1-6
/**
 * State City List for 1 - NE.
 *
 * City count: 6
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 1 - NE.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Agadez', 'wpdev-locations'),
	__('Alaghsas', 'wpdev-locations'),
	__('Arlit', 'wpdev-locations'),
	__('Bilma', 'wpdev-locations'),
	__('Département de Bilma', 'wpdev-locations'),
	__('Département de Tchirozérine', 'wpdev-locations'),
);
