<?php // phpcs:ignore - @generation-checksum NE-3-8
/**
 * State City List for 3 - NE.
 *
 * City count: 8
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 3 - NE.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Boboye Department', 'wpdev-locations'),
	__('Dogondoutchi', 'wpdev-locations'),
	__('Dosso', 'wpdev-locations'),
	__('Département de Dogondoutchi', 'wpdev-locations'),
	__('Département de Dosso', 'wpdev-locations'),
	__('Département de Gaya', 'wpdev-locations'),
	__('Département de Loga', 'wpdev-locations'),
	__('Gaya', 'wpdev-locations'),
);
