<?php // phpcs:ignore - @generation-checksum NE-4-12
/**
 * State City List for 4 - NE.
 *
 * City count: 12
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 4 - NE.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aguié', 'wpdev-locations'),
	__('Dakoro', 'wpdev-locations'),
	__('Département de Dakoro', 'wpdev-locations'),
	__('Département de Mayahi', 'wpdev-locations'),
	__('Département de Tessaoua', 'wpdev-locations'),
	__('Département d’Aguié', 'wpdev-locations'),
	__('Guidan Roumdji Department', 'wpdev-locations'),
	__('Madarounfa', 'wpdev-locations'),
	__('Maradi', 'wpdev-locations'),
	__('Mayahi', 'wpdev-locations'),
	__('Tessaoua', 'wpdev-locations'),
	__('Tibiri', 'wpdev-locations'),
);
