<?php // phpcs:ignore - @generation-checksum NE-5-15
/**
 * State City List for 5 - NE.
 *
 * City count: 15
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 5 - NE.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Abalak', 'wpdev-locations'),
	__('Birni N Konni', 'wpdev-locations'),
	__('Bouza', 'wpdev-locations'),
	__("Département d' Illéla", 'wpdev-locations'),
	__('Département de Birni Nkonni', 'wpdev-locations'),
	__('Département de Bouza', 'wpdev-locations'),
	__('Département de Keïta', 'wpdev-locations'),
	__('Département de Madaoua', 'wpdev-locations'),
	__('Département de Tahoua', 'wpdev-locations'),
	__('Département de Tchin-Tabaraden', 'wpdev-locations'),
	__('Illéla', 'wpdev-locations'),
	__('Keïta', 'wpdev-locations'),
	__('Madaoua', 'wpdev-locations'),
	__('Tahoua', 'wpdev-locations'),
	__('Tchintabaraden', 'wpdev-locations'),
);
