<?php // phpcs:ignore - @generation-checksum NE-6-14
/**
 * State City List for 6 - NE.
 *
 * City count: 14
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 6 - NE.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ayorou', 'wpdev-locations'),
	__('Balleyara', 'wpdev-locations'),
	__('Département de Filingué', 'wpdev-locations'),
	__('Département de Ouallam', 'wpdev-locations'),
	__('Département de Say', 'wpdev-locations'),
	__('Filingué', 'wpdev-locations'),
	__('Kollo', 'wpdev-locations'),
	__('Kollo Department', 'wpdev-locations'),
	__('Ouallam', 'wpdev-locations'),
	__('Say', 'wpdev-locations'),
	__('Tera Department', 'wpdev-locations'),
	__('Tillaberi Department', 'wpdev-locations'),
	__('Tillabéri', 'wpdev-locations'),
	__('Téra', 'wpdev-locations'),
);
