<?php // phpcs:ignore - @generation-checksum NE-7-9
/**
 * State City List for 7 - NE.
 *
 * City count: 9
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 7 - NE.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Département de Gouré', 'wpdev-locations'),
	__('Département de Kantché', 'wpdev-locations'),
	__('Département de Tânout', 'wpdev-locations'),
	__('Gouré', 'wpdev-locations'),
	__('Magaria', 'wpdev-locations'),
	__('Matamey', 'wpdev-locations'),
	__('Mirriah', 'wpdev-locations'),
	__('Tanout', 'wpdev-locations'),
	__('Zinder', 'wpdev-locations'),
);
