<?php // phpcs:ignore - @generation-checksum ZA-FS-41
/**
 * State City List for FS - ZA.
 *
 * City count: 41
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for FS - ZA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Allanridge', 'wpdev-locations'),
	__('Bethlehem', 'wpdev-locations'),
	__('Bloemfontein', 'wpdev-locations'),
	__('Bothaville', 'wpdev-locations'),
	__('Botshabelo', 'wpdev-locations'),
	__('Brandfort', 'wpdev-locations'),
	__('Clocolan', 'wpdev-locations'),
	__('Deneysville', 'wpdev-locations'),
	__('Fezile Dabi District Municipality', 'wpdev-locations'),
	__('Frankfort', 'wpdev-locations'),
	__('Harrismith', 'wpdev-locations'),
	__('Heilbron', 'wpdev-locations'),
	__('Hennenman', 'wpdev-locations'),
	__('Hoopstad', 'wpdev-locations'),
	__('Koppies', 'wpdev-locations'),
	__('Kroonstad', 'wpdev-locations'),
	__('Kutloanong', 'wpdev-locations'),
	__('Ladybrand', 'wpdev-locations'),
	__('Lejweleputswa District Municipality', 'wpdev-locations'),
	__('Lindley', 'wpdev-locations'),
	__('Mangaung Metropolitan Municipality', 'wpdev-locations'),
	__('Marquard', 'wpdev-locations'),
	__('Parys', 'wpdev-locations'),
	__('Phuthaditjhaba', 'wpdev-locations'),
	__('Reitz', 'wpdev-locations'),
	__('Sasolburg', 'wpdev-locations'),
	__('Senekal', 'wpdev-locations'),
	__('Thaba Nchu', 'wpdev-locations'),
	__('Thabo Mofutsanyana District Municipality', 'wpdev-locations'),
	__('Theunissen', 'wpdev-locations'),
	__('Ventersburg', 'wpdev-locations'),
	__('Viljoenskroon', 'wpdev-locations'),
	__('Villiers', 'wpdev-locations'),
	__('Virginia', 'wpdev-locations'),
	__('Vrede', 'wpdev-locations'),
	__('Vredefort', 'wpdev-locations'),
	__('Welkom', 'wpdev-locations'),
	__('Wesselsbron', 'wpdev-locations'),
	__('Winburg', 'wpdev-locations'),
	__('Xhariep District Municipality', 'wpdev-locations'),
	__('Zastron', 'wpdev-locations'),
);
