<?php // phpcs:ignore - @generation-checksum ZA-GP-39
/**
 * State City List for GP - ZA.
 *
 * City count: 39
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for GP - ZA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alberton', 'wpdev-locations'),
	__('Benoni', 'wpdev-locations'),
	__('Boksburg', 'wpdev-locations'),
	__('Brakpan', 'wpdev-locations'),
	__('Bronkhorstspruit', 'wpdev-locations'),
	__('Carletonville', 'wpdev-locations'),
	__('Centurion', 'wpdev-locations'),
	__('City of Johannesburg Metropolitan Municipality', 'wpdev-locations'),
	__('City of Tshwane Metropolitan Municipality', 'wpdev-locations'),
	__('Cullinan', 'wpdev-locations'),
	__('Diepsloot', 'wpdev-locations'),
	__('Eastleigh', 'wpdev-locations'),
	__('Eden Glen', 'wpdev-locations'),
	__('Eden Glen Ext 60', 'wpdev-locations'),
	__('Edenvale', 'wpdev-locations'),
	__('Ekangala', 'wpdev-locations'),
	__('Ekurhuleni Metropolitan Municipality', 'wpdev-locations'),
	__('Heidelberg', 'wpdev-locations'),
	__('Johannesburg', 'wpdev-locations'),
	__('Krugersdorp', 'wpdev-locations'),
	__('Mabopane', 'wpdev-locations'),
	__('Midrand', 'wpdev-locations'),
	__('Midstream', 'wpdev-locations'),
	__('Modderfontein', 'wpdev-locations'),
	__('Muldersdriseloop', 'wpdev-locations'),
	__('Nigel', 'wpdev-locations'),
	__('Orange Farm', 'wpdev-locations'),
	__('Pretoria', 'wpdev-locations'),
	__('Randburg', 'wpdev-locations'),
	__('Randfontein', 'wpdev-locations'),
	__('Roodepoort', 'wpdev-locations'),
	__('Sedibeng District Municipality', 'wpdev-locations'),
	__('Soweto', 'wpdev-locations'),
	__('Springs', 'wpdev-locations'),
	__('Tembisa', 'wpdev-locations'),
	__('Vanderbijlpark', 'wpdev-locations'),
	__('Vereeniging', 'wpdev-locations'),
	__('West Rand District Municipality', 'wpdev-locations'),
	__('Westonaria', 'wpdev-locations'),
);
