<?php // phpcs:ignore - @generation-checksum ZA-NC-28
/**
 * State City List for NC - ZA.
 *
 * City count: 28
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NC - ZA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Barkly West', 'wpdev-locations'),
	__('Brandvlei', 'wpdev-locations'),
	__('Calvinia', 'wpdev-locations'),
	__('Carnarvon', 'wpdev-locations'),
	__('Colesberg', 'wpdev-locations'),
	__('Daniëlskuil', 'wpdev-locations'),
	__('De Aar', 'wpdev-locations'),
	__('Frances Baard District Municipality', 'wpdev-locations'),
	__('Fraserburg', 'wpdev-locations'),
	__('John Taolo Gaetsewe District Municipality', 'wpdev-locations'),
	__('Kathu', 'wpdev-locations'),
	__('Kenhardt', 'wpdev-locations'),
	__('Kimberley', 'wpdev-locations'),
	__('Kuruman', 'wpdev-locations'),
	__('Namakwa District Municipality', 'wpdev-locations'),
	__('Noupoort', 'wpdev-locations'),
	__('Orania', 'wpdev-locations'),
	__('Pampierstad', 'wpdev-locations'),
	__('Pixley ka Seme District Municipality', 'wpdev-locations'),
	__('Pofadder', 'wpdev-locations'),
	__('Postmasburg', 'wpdev-locations'),
	__('Prieska', 'wpdev-locations'),
	__('Ritchie', 'wpdev-locations'),
	__('Siyanda District Municipality', 'wpdev-locations'),
	__('Springbok', 'wpdev-locations'),
	__('Upington', 'wpdev-locations'),
	__('Van Wyksvlei', 'wpdev-locations'),
	__('Warrenton', 'wpdev-locations'),
);
