<?php // phpcs:ignore - @generation-checksum ZA-WC-52
/**
 * State City List for WC - ZA.
 *
 * City count: 52
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for WC - ZA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Albertina', 'wpdev-locations'),
	__('Arniston', 'wpdev-locations'),
	__('Atlantis', 'wpdev-locations'),
	__('Beaufort West', 'wpdev-locations'),
	__('Bergvliet', 'wpdev-locations'),
	__('Bredasdorp', 'wpdev-locations'),
	__('Caledon', 'wpdev-locations'),
	__('Calitzdorp', 'wpdev-locations'),
	__('Cape Town', 'wpdev-locations'),
	__('Cape Winelands District Municipality', 'wpdev-locations'),
	__('Central Karoo District Municipality', 'wpdev-locations'),
	__('Ceres', 'wpdev-locations'),
	__('City of Cape Town', 'wpdev-locations'),
	__('Clanwilliam', 'wpdev-locations'),
	__('Claremont', 'wpdev-locations'),
	__('Constantia', 'wpdev-locations'),
	__('De Rust', 'wpdev-locations'),
	__('Eden District Municipality', 'wpdev-locations'),
	__('George', 'wpdev-locations'),
	__('Grabouw', 'wpdev-locations'),
	__('Hardys Memories of Africa', 'wpdev-locations'),
	__('Hermanus', 'wpdev-locations'),
	__('Knysna', 'wpdev-locations'),
	__('Kraaifontein', 'wpdev-locations'),
	__('Ladismith', 'wpdev-locations'),
	__('Lansdowne', 'wpdev-locations'),
	__('Malmesbury', 'wpdev-locations'),
	__('Montagu', 'wpdev-locations'),
	__('Moorreesburg', 'wpdev-locations'),
	__('Mossel Bay', 'wpdev-locations'),
	__('Newlands', 'wpdev-locations'),
	__('Oudtshoorn', 'wpdev-locations'),
	__('Overberg District Municipality', 'wpdev-locations'),
	__('Paarl', 'wpdev-locations'),
	__('Piketberg', 'wpdev-locations'),
	__('Plettenberg Bay', 'wpdev-locations'),
	__('Prince Albert', 'wpdev-locations'),
	__('Retreat', 'wpdev-locations'),
	__('Riversdale', 'wpdev-locations'),
	__('Robertson', 'wpdev-locations'),
	__('Rondebosch', 'wpdev-locations'),
	__('Rosebank', 'wpdev-locations'),
	__('Saldanha', 'wpdev-locations'),
	__('Stellenbosch', 'wpdev-locations'),
	__('Sunset Beach', 'wpdev-locations'),
	__('Swellendam', 'wpdev-locations'),
	__('Vredenburg', 'wpdev-locations'),
	__('Vredendal', 'wpdev-locations'),
	__('Wellington', 'wpdev-locations'),
	__('West Coast District Municipality', 'wpdev-locations'),
	__('Worcester', 'wpdev-locations'),
	__('Zoar', 'wpdev-locations'),
);
