<?php // phpcs:ignore - @generation-checksum CA-MB-43
/**
 * State City List for MB - CA.
 *
 * City count: 43
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MB - CA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Altona', 'wpdev-locations'),
	__('Beausejour', 'wpdev-locations'),
	__('Boissevain', 'wpdev-locations'),
	__('Brandon', 'wpdev-locations'),
	__('Carberry', 'wpdev-locations'),
	__('Carman', 'wpdev-locations'),
	__('Cross Lake 19A', 'wpdev-locations'),
	__('Dauphin', 'wpdev-locations'),
	__('De Salaberry', 'wpdev-locations'),
	__('Deloraine', 'wpdev-locations'),
	__('Flin Flon', 'wpdev-locations'),
	__('Gimli', 'wpdev-locations'),
	__('Grunthal', 'wpdev-locations'),
	__('Headingley', 'wpdev-locations'),
	__('Ile des Chênes', 'wpdev-locations'),
	__('Killarney', 'wpdev-locations'),
	__('La Broquerie', 'wpdev-locations'),
	__('Lac du Bonnet', 'wpdev-locations'),
	__('Landmark', 'wpdev-locations'),
	__('Lorette', 'wpdev-locations'),
	__('Melita', 'wpdev-locations'),
	__('Minnedosa', 'wpdev-locations'),
	__('Moose Lake', 'wpdev-locations'),
	__('Morden', 'wpdev-locations'),
	__('Morris', 'wpdev-locations'),
	__('Neepawa', 'wpdev-locations'),
	__('Niverville', 'wpdev-locations'),
	__('Portage la Prairie', 'wpdev-locations'),
	__('Rivers', 'wpdev-locations'),
	__('Roblin', 'wpdev-locations'),
	__('Selkirk', 'wpdev-locations'),
	__('Shilo', 'wpdev-locations'),
	__('Souris', 'wpdev-locations'),
	__('St. Adolphe', 'wpdev-locations'),
	__('Steinbach', 'wpdev-locations'),
	__('Stonewall', 'wpdev-locations'),
	__('Swan River', 'wpdev-locations'),
	__('The Pas', 'wpdev-locations'),
	__('Thompson', 'wpdev-locations'),
	__('Virden', 'wpdev-locations'),
	__('West St. Paul', 'wpdev-locations'),
	__('Winkler', 'wpdev-locations'),
	__('Winnipeg', 'wpdev-locations'),
);
