<?php // phpcs:ignore - @generation-checksum CA-NL-32
/**
 * State City List for NL - CA.
 *
 * City count: 32
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NL - CA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bay Roberts', 'wpdev-locations'),
	__('Bay St. George South', 'wpdev-locations'),
	__('Bonavista', 'wpdev-locations'),
	__('Botwood', 'wpdev-locations'),
	__('Burgeo', 'wpdev-locations'),
	__('Carbonear', 'wpdev-locations'),
	__('Catalina', 'wpdev-locations'),
	__('Channel-Port aux Basques', 'wpdev-locations'),
	__('Clarenville-Shoal Harbour', 'wpdev-locations'),
	__('Conception Bay South', 'wpdev-locations'),
	__('Corner Brook', 'wpdev-locations'),
	__('Deer Lake', 'wpdev-locations'),
	__('Fogo Island', 'wpdev-locations'),
	__('Gambo', 'wpdev-locations'),
	__('Goulds', 'wpdev-locations'),
	__('Grand Bank', 'wpdev-locations'),
	__('Grand Falls-Windsor', 'wpdev-locations'),
	__('Happy Valley-Goose Bay', 'wpdev-locations'),
	__('Harbour Breton', 'wpdev-locations'),
	__('Labrador City', 'wpdev-locations'),
	__('Lewisporte', 'wpdev-locations'),
	__('Marystown', 'wpdev-locations'),
	__('Mount Pearl', 'wpdev-locations'),
	__('Pasadena', 'wpdev-locations'),
	__('Springdale', 'wpdev-locations'),
	__('St. Anthony', 'wpdev-locations'),
	__("St. John's", 'wpdev-locations'),
	__('Stephenville', 'wpdev-locations'),
	__('Stephenville Crossing', 'wpdev-locations'),
	__('Torbay', 'wpdev-locations'),
	__('Upper Island Cove', 'wpdev-locations'),
	__('Wabana', 'wpdev-locations'),
);
