<?php // phpcs:ignore - @generation-checksum CA-NU-6
/**
 * State City List for NU - CA.
 *
 * City count: 6
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NU - CA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Clyde River', 'wpdev-locations'),
	__('Gjoa Haven', 'wpdev-locations'),
	__('Iqaluit', 'wpdev-locations'),
	__('Kugluktuk', 'wpdev-locations'),
	__('Pangnirtung', 'wpdev-locations'),
	__('Rankin Inlet', 'wpdev-locations'),
);
