<?php // phpcs:ignore - @generation-checksum CA-PE-9
/**
 * State City List for PE - CA.
 *
 * City count: 9
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for PE - CA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alberton', 'wpdev-locations'),
	__('Belfast', 'wpdev-locations'),
	__('Charlottetown', 'wpdev-locations'),
	__('Cornwall', 'wpdev-locations'),
	__('Fallingbrook', 'wpdev-locations'),
	__('Kensington', 'wpdev-locations'),
	__('Montague', 'wpdev-locations'),
	__('Souris', 'wpdev-locations'),
	__('Summerside', 'wpdev-locations'),
);
