<?php // phpcs:ignore - @generation-checksum IN-AN-4
/**
 * State City List for AN - IN.
 *
 * City count: 4
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AN - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bamboo Flat', 'wpdev-locations'),
	__('Nicobar', 'wpdev-locations'),
	__('Port Blair', 'wpdev-locations'),
	__('South Andaman', 'wpdev-locations'),
);
