<?php // phpcs:ignore - @generation-checksum IN-AR-26
/**
 * State City List for AR - IN.
 *
 * City count: 26
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AR - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Along', 'wpdev-locations'),
	__('Anjaw', 'wpdev-locations'),
	__('Basar', 'wpdev-locations'),
	__('Bomdila', 'wpdev-locations'),
	__('Changlang', 'wpdev-locations'),
	__('Dibang Valley', 'wpdev-locations'),
	__('East Kameng', 'wpdev-locations'),
	__('East Siang', 'wpdev-locations'),
	__('Hayuliang', 'wpdev-locations'),
	__('Itanagar', 'wpdev-locations'),
	__('Khonsa', 'wpdev-locations'),
	__('Kurung Kumey', 'wpdev-locations'),
	__('Lohit District', 'wpdev-locations'),
	__('Lower Dibang Valley', 'wpdev-locations'),
	__('Lower Subansiri', 'wpdev-locations'),
	__('Margherita', 'wpdev-locations'),
	__('Naharlagun', 'wpdev-locations'),
	__('Pasighat', 'wpdev-locations'),
	__('Tawang', 'wpdev-locations'),
	__('Tezu', 'wpdev-locations'),
	__('Tirap', 'wpdev-locations'),
	__('Upper Siang', 'wpdev-locations'),
	__('Upper Subansiri', 'wpdev-locations'),
	__('West Kameng', 'wpdev-locations'),
	__('West Siang', 'wpdev-locations'),
	__('Ziro', 'wpdev-locations'),
);
