<?php // phpcs:ignore - @generation-checksum IN-CT-78
/**
 * State City List for CT - IN.
 *
 * City count: 78
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for CT - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akaltara', 'wpdev-locations'),
	__('Ambagarh Chauki', 'wpdev-locations'),
	__('Ambikapur', 'wpdev-locations'),
	__('Arang', 'wpdev-locations'),
	__('Baikunthpur', 'wpdev-locations'),
	__('Balod', 'wpdev-locations'),
	__('Baloda', 'wpdev-locations'),
	__('Baloda Bazar', 'wpdev-locations'),
	__('Basna', 'wpdev-locations'),
	__('Bastar', 'wpdev-locations'),
	__('Bemetara', 'wpdev-locations'),
	__('Bhanpuri', 'wpdev-locations'),
	__('Bhatapara', 'wpdev-locations'),
	__('Bhatgaon', 'wpdev-locations'),
	__('Bhilai', 'wpdev-locations'),
	__('Bijapur', 'wpdev-locations'),
	__('Bilaspur', 'wpdev-locations'),
	__('Champa', 'wpdev-locations'),
	__('Chhuikhadan', 'wpdev-locations'),
	__('Deori', 'wpdev-locations'),
	__('Dhamtari', 'wpdev-locations'),
	__('Dongargaon', 'wpdev-locations'),
	__('Dongargarh', 'wpdev-locations'),
	__('Durg', 'wpdev-locations'),
	__('Gandai', 'wpdev-locations'),
	__('Gariaband', 'wpdev-locations'),
	__('Gaurela', 'wpdev-locations'),
	__('Gharghoda', 'wpdev-locations'),
	__('Gidam', 'wpdev-locations'),
	__('Jagdalpur', 'wpdev-locations'),
	__('Janjgir', 'wpdev-locations'),
	__('Janjgir-Champa', 'wpdev-locations'),
	__('Jashpur', 'wpdev-locations'),
	__('Jashpurnagar', 'wpdev-locations'),
	__('Junagarh', 'wpdev-locations'),
	__('Kabeerdham', 'wpdev-locations'),
	__('Kanker', 'wpdev-locations'),
	__('Katghora', 'wpdev-locations'),
	__('Kawardha', 'wpdev-locations'),
	__('Khairagarh', 'wpdev-locations'),
	__('Khamharia', 'wpdev-locations'),
	__('Kharod', 'wpdev-locations'),
	__('Kharsia', 'wpdev-locations'),
	__('Kirandul', 'wpdev-locations'),
	__('Kondagaon', 'wpdev-locations'),
	__('Korba', 'wpdev-locations'),
	__('Koriya', 'wpdev-locations'),
	__('Kota', 'wpdev-locations'),
	__('Kotaparh', 'wpdev-locations'),
	__('Kumhari', 'wpdev-locations'),
	__('Kurud', 'wpdev-locations'),
	__('Lormi', 'wpdev-locations'),
	__('Mahasamund', 'wpdev-locations'),
	__('Mungeli', 'wpdev-locations'),
	__('Narayanpur', 'wpdev-locations'),
	__('Narharpur', 'wpdev-locations'),
	__('Pandaria', 'wpdev-locations'),
	__('Pandatarai', 'wpdev-locations'),
	__('Pasan', 'wpdev-locations'),
	__('Patan', 'wpdev-locations'),
	__('Pathalgaon', 'wpdev-locations'),
	__('Pendra', 'wpdev-locations'),
	__('Pithora', 'wpdev-locations'),
	__('Raigarh', 'wpdev-locations'),
	__('Raipur', 'wpdev-locations'),
	__('Raj Nandgaon', 'wpdev-locations'),
	__('Raj-Nandgaon', 'wpdev-locations'),
	__('Ramanuj Ganj', 'wpdev-locations'),
	__('Ratanpur', 'wpdev-locations'),
	__('Sakti', 'wpdev-locations'),
	__('Saraipali', 'wpdev-locations'),
	__('Sarangarh', 'wpdev-locations'),
	__('Seorinarayan', 'wpdev-locations'),
	__('Simga', 'wpdev-locations'),
	__('Surguja', 'wpdev-locations'),
	__('Takhatpur', 'wpdev-locations'),
	__('Umarkot', 'wpdev-locations'),
	__('Uttar Bastar Kanker', 'wpdev-locations'),
);
