<?php // phpcs:ignore - @generation-checksum IN-DH-7
/**
 * State City List for DH - IN.
 *
 * City count: 7
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for DH - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Amli', 'wpdev-locations'),
	__('Dadra', 'wpdev-locations'),
	__('Dadra & Nagar Haveli', 'wpdev-locations'),
	__('Daman', 'wpdev-locations'),
	__('Daman District', 'wpdev-locations'),
	__('Diu', 'wpdev-locations'),
	__('Silvassa', 'wpdev-locations'),
);
