<?php // phpcs:ignore - @generation-checksum IN-GA-50
/**
 * State City List for GA - IN.
 *
 * City count: 50
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for GA - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aldona', 'wpdev-locations'),
	__('Arambol', 'wpdev-locations'),
	__('Baga', 'wpdev-locations'),
	__('Bambolim', 'wpdev-locations'),
	__('Bandora', 'wpdev-locations'),
	__('Benaulim', 'wpdev-locations'),
	__('Calangute', 'wpdev-locations'),
	__('Candolim', 'wpdev-locations'),
	__('Carapur', 'wpdev-locations'),
	__('Cavelossim', 'wpdev-locations'),
	__('Chicalim', 'wpdev-locations'),
	__('Chinchinim', 'wpdev-locations'),
	__('Colovale', 'wpdev-locations'),
	__('Colva', 'wpdev-locations'),
	__('Cortalim', 'wpdev-locations'),
	__('Cuncolim', 'wpdev-locations'),
	__('Curchorem', 'wpdev-locations'),
	__('Curti', 'wpdev-locations'),
	__('Davorlim', 'wpdev-locations'),
	__('Dicholi', 'wpdev-locations'),
	__('Goa Velha', 'wpdev-locations'),
	__('Guirim', 'wpdev-locations'),
	__('Jua', 'wpdev-locations'),
	__('Kankon', 'wpdev-locations'),
	__('Madgaon', 'wpdev-locations'),
	__('Mapuca', 'wpdev-locations'),
	__('Morjim', 'wpdev-locations'),
	__('Mormugao', 'wpdev-locations'),
	__('Navelim', 'wpdev-locations'),
	__('North Goa', 'wpdev-locations'),
	__('Palle', 'wpdev-locations'),
	__('Panaji', 'wpdev-locations'),
	__('Pernem', 'wpdev-locations'),
	__('Ponda', 'wpdev-locations'),
	__('Quepem', 'wpdev-locations'),
	__('Queula', 'wpdev-locations'),
	__('Raia', 'wpdev-locations'),
	__('Saligao', 'wpdev-locations'),
	__('Sancoale', 'wpdev-locations'),
	__('Sanguem', 'wpdev-locations'),
	__('Sanquelim', 'wpdev-locations'),
	__('Sanvordem', 'wpdev-locations'),
	__('Serula', 'wpdev-locations'),
	__('Solim', 'wpdev-locations'),
	__('South Goa', 'wpdev-locations'),
	__('Taleigao', 'wpdev-locations'),
	__('Vagator', 'wpdev-locations'),
	__('Valpoy', 'wpdev-locations'),
	__('Varca', 'wpdev-locations'),
	__('Vasco da Gama', 'wpdev-locations'),
);
