<?php // phpcs:ignore - @generation-checksum IN-HP-57
/**
 * State City List for HP - IN.
 *
 * City count: 57
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for HP - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Arki', 'wpdev-locations'),
	__('Baddi', 'wpdev-locations'),
	__('Banjar', 'wpdev-locations'),
	__('Bilaspur', 'wpdev-locations'),
	__('Chamba', 'wpdev-locations'),
	__('Chaupal', 'wpdev-locations'),
	__('Chowari', 'wpdev-locations'),
	__('Chuari Khas', 'wpdev-locations'),
	__('Dagshai', 'wpdev-locations'),
	__('Dalhousie', 'wpdev-locations'),
	__('Daulatpur', 'wpdev-locations'),
	__('Dera Gopipur', 'wpdev-locations'),
	__('Dharamsala', 'wpdev-locations'),
	__('Gagret', 'wpdev-locations'),
	__('Ghumarwin', 'wpdev-locations'),
	__('Hamirpur', 'wpdev-locations'),
	__('Jawala Mukhi', 'wpdev-locations'),
	__('Jogindarnagar', 'wpdev-locations'),
	__('Jubbal', 'wpdev-locations'),
	__('Jutogh', 'wpdev-locations'),
	__('Kalka', 'wpdev-locations'),
	__('Kangar', 'wpdev-locations'),
	__('Kangra', 'wpdev-locations'),
	__('Kasauli', 'wpdev-locations'),
	__('Kinnaur', 'wpdev-locations'),
	__('Kotkhai', 'wpdev-locations'),
	__('Kotla', 'wpdev-locations'),
	__('Kulu', 'wpdev-locations'),
	__('Kyelang', 'wpdev-locations'),
	__('Lahul and Spiti', 'wpdev-locations'),
	__('Manali', 'wpdev-locations'),
	__('Mandi', 'wpdev-locations'),
	__('Nadaun', 'wpdev-locations'),
	__('Nagar', 'wpdev-locations'),
	__('Nagrota', 'wpdev-locations'),
	__('Nahan', 'wpdev-locations'),
	__('Nalagarh', 'wpdev-locations'),
	__('Palampur', 'wpdev-locations'),
	__('Pandoh', 'wpdev-locations'),
	__('Paonta Sahib', 'wpdev-locations'),
	__('Parwanoo', 'wpdev-locations'),
	__('Rajgarh', 'wpdev-locations'),
	__('Rampur', 'wpdev-locations'),
	__('Rohru', 'wpdev-locations'),
	__('Sabathu', 'wpdev-locations'),
	__('Santokhgarh', 'wpdev-locations'),
	__('Sarahan', 'wpdev-locations'),
	__('Sarka Ghat', 'wpdev-locations'),
	__('Seoni', 'wpdev-locations'),
	__('Shimla', 'wpdev-locations'),
	__('Sirmaur', 'wpdev-locations'),
	__('Solan', 'wpdev-locations'),
	__('Sundarnagar', 'wpdev-locations'),
	__('Theog', 'wpdev-locations'),
	__('Tira Sujanpur', 'wpdev-locations'),
	__('Una', 'wpdev-locations'),
	__('Yol', 'wpdev-locations'),
);
