<?php // phpcs:ignore - @generation-checksum IN-MZ-15
/**
 * State City List for MZ - IN.
 *
 * City count: 15
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MZ - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aizawl', 'wpdev-locations'),
	__('Champhai', 'wpdev-locations'),
	__('Darlawn', 'wpdev-locations'),
	__('Khawhai', 'wpdev-locations'),
	__('Kolasib', 'wpdev-locations'),
	__('Kolasib district', 'wpdev-locations'),
	__('Lawngtlai', 'wpdev-locations'),
	__('Lunglei', 'wpdev-locations'),
	__('Mamit', 'wpdev-locations'),
	__('North Vanlaiphai', 'wpdev-locations'),
	__('Saiha', 'wpdev-locations'),
	__('Sairang', 'wpdev-locations'),
	__('Saitlaw', 'wpdev-locations'),
	__('Serchhip', 'wpdev-locations'),
	__('Thenzawl', 'wpdev-locations'),
);
