<?php // phpcs:ignore - @generation-checksum IN-NL-10
/**
 * State City List for NL - IN.
 *
 * City count: 10
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NL - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Dimapur', 'wpdev-locations'),
	__('Kohima', 'wpdev-locations'),
	__('Mokokchung', 'wpdev-locations'),
	__('Mon', 'wpdev-locations'),
	__('Peren', 'wpdev-locations'),
	__('Phek', 'wpdev-locations'),
	__('Tuensang', 'wpdev-locations'),
	__('Tuensang District', 'wpdev-locations'),
	__('Wokha', 'wpdev-locations'),
	__('Zunheboto', 'wpdev-locations'),
);
