<?php // phpcs:ignore - @generation-checksum IN-PY-4
/**
 * State City List for PY - IN.
 *
 * City count: 4
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for PY - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Karaikal', 'wpdev-locations'),
	__('Mahe', 'wpdev-locations'),
	__('Puducherry', 'wpdev-locations'),
	__('Yanam', 'wpdev-locations'),
);
