<?php // phpcs:ignore - @generation-checksum IN-SK-12
/**
 * State City List for SK - IN.
 *
 * City count: 12
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SK - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('East District', 'wpdev-locations'),
	__('Gangtok', 'wpdev-locations'),
	__('Gyalshing', 'wpdev-locations'),
	__('Jorethang', 'wpdev-locations'),
	__('Mangan', 'wpdev-locations'),
	__('Namchi', 'wpdev-locations'),
	__('Naya Bazar', 'wpdev-locations'),
	__('North District', 'wpdev-locations'),
	__('Rangpo', 'wpdev-locations'),
	__('Singtam', 'wpdev-locations'),
	__('South District', 'wpdev-locations'),
	__('West District', 'wpdev-locations'),
);
