/**
 * Phase 24.9 / 24.10 — `doctorProject(dir)` contract.
 *
 * The doctor is the installer's "is this consumer project
 * healthy?" check. It's a SAFE read-only operation: it never
 * throws, never writes, and never auto-fixes. The CLI's
 * `wpdev doctor` command calls it and prints the result.
 *
 * The contract:
 *
 *   doctorProject(dir) → {
 *     ok: boolean,           // true iff errors.length === 0
 *     warnings: string[],    // non-fatal drift
 *     errors: string[],      // fatal — `wpdev update` is recommended
 *   }
 *
 * Checks (one per test, 4 total):
 *
 *  1. `wpdev.json` (the manifest) is present. Missing →
 *     `errors.push("manifest missing")`. This is the only
 *     FATAL check that doesn't need a manifest to detect.
 *
 *  2. Every feature id in `manifest.features` is a known
 *     catalog id (per `getFeatureCatalog()`). Unknown ids →
 *     `errors.push("unknown feature: <id>")` (one per id).
 *     Drift: a project whose manifest was edited by hand to
 *     include a typo'd feature id, OR a project generated by
 *     a NEWER kit that has a feature the OLD kit doesn't
 *     know about. Either way, the doctor flags it and the
 *     user can `wpdev update` (if newer) or roll back the
 *     edit (if typo).
 *
 *  3. `manifest.kitVersion` is not NEWER than the installed
 *     kit's `getDepVersions()`. A manifest newer than the
 *     running kit is a "the kit is older than the project"
 *     mismatch — the user should `wpdev update`. This is a
 *     WARNING, not an error: the project will still work
 *     for the features it uses, it just can't get updates.
 *     The message is: "kit newer than installed deps — run
 *     wpdev update".
 *
 *  4. If `manifest.distMode === "vendored"`, verify the
 *     checksum of `vendor/wp-framework/*` matches what the
 *     kit shipped. The check is a placeholder (skip if the
 *     files aren't present, but the function MUST exist and
 *     MUST be invoked when files are present). The test
 *     asserts the function exists and is wired in — the
 *     full checksum is a Phase 25+ item.
 *
 * Plus a 5th test: a fully-healthy project → empty
 * warnings + empty errors + ok:true. This is the "happy
 * path" guard.
 *
 * SAFE contract: doctorProject never throws. A malformed
 * manifest is a `warnings.push("manifest unreadable: ...")`,
 * NOT a throw — the CLI shows the user the warning and
 * exits non-zero only when errors.length > 0. The "never
 * throws" property is locked by a test that runs doctor on
 * a dir with a malformed manifest.
 */

import { describe, test, expect, beforeEach, afterEach } from "@jest/globals";
import { promises as fs } from "node:fs";
import * as path from "node:path";
import * as os from "node:os";

import { doctorProject } from "../../packages/create-wp-project/src/doctor.js";
import { getDepVersions } from "../../packages/create-wp-project/src/dep-versions.js";
import { getFeatureCatalog } from "../../packages/create-wp-project/src/features.js";

/**
 * Seed a fresh project with a 0.1.0 manifest. The feature
 * set defaults to all-catalog-defaults (so the "unknown
 * feature" check passes), and the kitVersion matches the
 * installed kit's own version (so the "kit newer than
 * installed" warning stays silent).
 */
async function seedHealthy({ kitVersion, distMode = "deps", features } = {}) {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "wpdev-doctor-"));
  const kv = kitVersion !== undefined ? kitVersion : "0.1.0";
  const featureSet = features
    ? { ...features }
    : { ...defaultFeatureSet(), jsLib: "preact" };
  const projectConfig = {
    slug: "test-plugin",
    globalName: "TestPlugin",
    localizeVar: "TestPluginLoc",
    textDomain: "test-plugin",
    hookPrefix: "test_plugin",
    npmScope: "@test",
    depsBundle: "test-plugin-deps.js",
    restNamespace: "test-plugin/v1",
    batchEndpoint: "/batch/v1",
    vendorPrefix: "TestPluginVendor",
    phpMinVersion: featureSet.phpMinVersion || "7.4",
    phpSourceVersion: "8.1",
  };
  if (featureSet.jsLib === "react" || featureSet.jsLib === "preact") {
    projectConfig.uiFramework = featureSet.jsLib;
  }
  const merged = {
    schema: 2,
    kitVersion: kv,
    distMode,
    generatedAt: "2026-01-01T00:00:00.000Z",
    ...projectConfig,
    features: featureSet,
  };
  await fs.writeFile(
    path.join(dir, "wpdev.json"),
    JSON.stringify(merged, null, 2) + "\n",
    "utf8",
  );
  return dir;
}

/** Build an all-default feature set keyed by the catalog. */
function defaultFeatureSet() {
  const out = {};
  for (const f of getFeatureCatalog()) {
    out[f.id] = f.variants[0];
  }
  return out;
}

describe("doctorProject() — check 1: manifest present (Phase 24.9)", () => {
  let tmpDir;
  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "wpdev-doctor-1-"));
  });
  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test("when wpdev.json is missing, errors contains 'manifest missing'", () => {
    const res = doctorProject(tmpDir);
    expect(res.ok).toBe(false);
    expect(res.errors).toContain("manifest missing");
  });
});

describe("doctorProject() — check 1b: unsupported manifest schema", () => {
  let tmpDir;
  beforeEach(async () => {
    tmpDir = await seedHealthy();
    const manifest = JSON.parse(
      await fs.readFile(path.join(tmpDir, "wpdev.json"), "utf8"),
    );
    manifest.schema = 99;
    await fs.writeFile(
      path.join(tmpDir, "wpdev.json"),
      JSON.stringify(manifest, null, 2) + "\n",
      "utf8",
    );
  });
  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test("unsupported schema surfaces as a fatal error", () => {
    const res = doctorProject(tmpDir);
    expect(res.ok).toBe(false);
    expect(
      res.errors.some((e) => /unsupported manifest schema 99/.test(e)),
    ).toBe(true);
  });
});

describe("doctorProject() — check 2: unknown feature ids (Phase 24.9)", () => {
  let tmpDir;
  beforeEach(async () => {
    tmpDir = await seedHealthy({
      features: {
        ...defaultFeatureSet(),
        bogusFeature: "on", // NOT in the catalog
        anotherTypo: "off", // NOT in the catalog
      },
    });
  });
  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test("every unknown feature id is reported as a warning (newer-kit forward compat)", () => {
    const res = doctorProject(tmpDir);
    expect(res.ok).toBe(true);
    expect(
      res.warnings.some((w) =>
        /feature bogusFeature is from a newer kit/.test(w),
      ),
    ).toBe(true);
    expect(
      res.warnings.some((w) =>
        /feature anotherTypo is from a newer kit/.test(w),
      ),
    ).toBe(true);
  });
});

describe("doctorProject() — check 3: kitVersion vs installed deps (Phase 24.10)", () => {
  let tmpDir;
  beforeEach(async () => {
    // Seed with a manifest kitVersion NEWER than the kit's
    // own dep registry reports. Since getDepVersions() reads
    // ranges from the kit's package.json/composer.json (NOT
    // a kit version), we compare against a known kit version
    // constant the doctor reads the same way. The contract
    // is: a project at a HIGHER kitVersion than the running
    // kit ships is a warning.
    //
    // Implementation note: the doctor reads the kit's own
    // version from its own package.json (same way
    // readKitVersion() in src/index.js does). We seed a
    // manifest at a "future" version (e.g. "99.0.0") to
    // force the warning.
    tmpDir = await seedHealthy({ kitVersion: "99.0.0" });
  });
  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test("when manifest.kitVersion is newer than the installed kit, a warning is surfaced", () => {
    const res = doctorProject(tmpDir);
    // The warning is non-fatal — ok is still true iff
    // errors is empty.
    expect(
      res.warnings.some((w) =>
        /kit newer than installed|wpdev update/i.test(w),
      ),
    ).toBe(true);
  });
});

describe("doctorProject() — check 4: vendored framework checksum (Phase 24.10)", () => {
  let tmpDir;
  beforeEach(async () => {
    tmpDir = await seedHealthy({ distMode: "vendored" });
  });
  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test("vendored mode without Plugin.php surfaces a migration warning", async () => {
    const res = doctorProject(tmpDir);
    expect(res.errors).toEqual([]);
    expect(
      res.warnings.some((w) => /src\/Core\/Plugin\.php is missing/.test(w)),
    ).toBe(true);
  });

  test("non-shim src/Core/Plugin.php under vendored manifest produces a stale-copy warning", async () => {
    const corePhp = path.join(tmpDir, "src", "Core", "Plugin.php");
    await fs.mkdir(path.join(tmpDir, "src", "Core"), { recursive: true });
    await fs.writeFile(
      corePhp,
      "<?php namespace WPDev\\Core; class Plugin { public static function boot() {} public static function config() {} }",
      "utf8",
    );
    const res = doctorProject(tmpDir);
    expect(
      res.warnings.some((w) =>
        /stale non-shim Plugin\.php|Legacy vendored/.test(w),
      ),
    ).toBe(true);
  });

  test("shim src/Core/Plugin.php under vendored manifest produces no framework warning", async () => {
    const corePhp = path.join(tmpDir, "src", "Core", "Plugin.php");
    await fs.mkdir(path.join(tmpDir, "src", "Core"), { recursive: true });
    await fs.writeFile(
      corePhp,
      "<?php // shim\nrequire_once __DIR__ . '/../../vendor/wpdev/framework/src/Core/Plugin.php';\n",
      "utf8",
    );
    const res = doctorProject(tmpDir);
    expect(
      res.warnings.some((w) => /stale non-shim|Legacy vendored/.test(w)),
    ).toBe(false);
  });
});

describe("doctorProject() — happy path (Phase 24.10)", () => {
  let tmpDir;
  beforeEach(async () => {
    tmpDir = await seedHealthy();
  });
  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test("a healthy deps-mode manifest returns ok:true with no errors", () => {
    const res = doctorProject(tmpDir);
    expect(res.ok).toBe(true);
    expect(res.errors).toEqual([]);
  });
});

describe("doctorProject() — malformed manifest (Phase 24.10)", () => {
  let tmpDir;
  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "wpdev-doctor-bad-"));
    await fs.writeFile(
      path.join(tmpDir, "wpdev.json"),
      '{ "schema": 1, "kit',
      "utf8",
    );
  });
  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test("malformed JSON in wpdev.json surfaces as a warning (NOT a throw)", () => {
    // The contract: doctorProject NEVER throws. A broken
    // manifest is a warning the user can act on, not a
    // fatal error.
    let res;
    expect(() => {
      res = doctorProject(tmpDir);
    }).not.toThrow();
    expect(res).toBeDefined();
    expect(Array.isArray(res.warnings)).toBe(true);
    expect(
      res.warnings.some((w) => /manifest|unreadable|malformed|json/i.test(w)),
    ).toBe(true);
  });
});

describe("doctorProject() — validateFeatureSet + variant checks (Phase 3)", () => {
  let tmpDir;

  afterEach(async () => {
    if (tmpDir) await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test('faultTolerance:"on" + phpMinVersion:"7.4" surfaces a validation error', async () => {
    tmpDir = await seedHealthy({
      features: {
        ...defaultFeatureSet(),
        faultTolerance: "on",
        phpMinVersion: "7.4",
      },
    });
    const res = doctorProject(tmpDir);
    expect(res.ok).toBe(false);
    expect(
      res.errors.some((e) => /faultTolerance|phpMinVersion/i.test(e)),
    ).toBe(true);
  });

  test('js:"coffeescript" surfaces invalid value error', async () => {
    tmpDir = await seedHealthy({
      features: {
        ...defaultFeatureSet(),
        js: "coffeescript",
      },
    });
    const res = doctorProject(tmpDir);
    expect(res.ok).toBe(false);
    expect(
      res.errors.some((e) =>
        /feature js has invalid value coffeescript/.test(e),
      ),
    ).toBe(true);
  });
});

describe("doctorProject() — owned file drift (Phase 3)", () => {
  let tmpDir;

  afterEach(async () => {
    if (tmpDir) await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test("feature on but owned files missing → warning", async () => {
    tmpDir = await seedHealthy({
      features: { ...defaultFeatureSet(), husky: "on" },
    });
    const res = doctorProject(tmpDir);
    expect(
      res.warnings.some((w) =>
        /feature husky is on but its files are missing/.test(w),
      ),
    ).toBe(true);
  });

  test("feature off but orphan owned files remain → warning", async () => {
    tmpDir = await seedHealthy({
      features: { ...defaultFeatureSet(), husky: "off" },
    });
    await fs.mkdir(path.join(tmpDir, ".husky"), { recursive: true });
    await fs.writeFile(
      path.join(tmpDir, ".husky", "pre-commit"),
      "#!/bin/sh\n",
      "utf8",
    );
    const res = doctorProject(tmpDir);
    expect(
      res.warnings.some((w) =>
        /feature husky is off but orphan files remain/.test(w),
      ),
    ).toBe(true);
  });
});

describe("doctorProject() — config consistency (P1-T1 / P1-T3)", () => {
  let tmpDir;

  afterEach(async () => {
    if (tmpDir) await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test("missing slug in wpdev.json is reported", async () => {
    tmpDir = await seedHealthy();
    const cfgPath = path.join(tmpDir, "wpdev.json");
    const cfg = {
      globalName: "Test",
      localizeVar: "TestLoc",
      textDomain: "test",
      hookPrefix: "test",
      npmScope: "@test",
      depsBundle: "test-deps.js",
      restNamespace: "test/v1",
      batchEndpoint: "/batch/v1",
      vendorPrefix: "TestVendor",
      uiFramework: "preact",
      phpMinVersion: "7.4",
      phpSourceVersion: "8.1",
    };
    await fs.writeFile(cfgPath, JSON.stringify(cfg, null, 2) + "\n", "utf8");
    const res = doctorProject(tmpDir);
    expect(res.ok).toBe(false);
    expect(
      res.errors.some((e) => /Config consistency: missing field slug/.test(e)),
    ).toBe(true);
  });

  test("phpMinVersion drift between manifest and project.config is reported", async () => {
    tmpDir = await seedHealthy();
    const cfgPath = path.join(tmpDir, "wpdev.json");
    await fs.writeFile(
      cfgPath,
      JSON.stringify(
        {
          slug: "test-plugin",
          globalName: "TestPlugin",
          localizeVar: "TestPluginLoc",
          textDomain: "test-plugin",
          hookPrefix: "test_plugin",
          npmScope: "@test",
          depsBundle: "test-plugin-deps.js",
          restNamespace: "test-plugin/v1",
          batchEndpoint: "/batch/v1",
          vendorPrefix: "TestPluginVendor",
          uiFramework: "preact",
          phpMinVersion: "7.4",
          phpSourceVersion: "8.1",
        },
        null,
        2,
      ) + "\n",
      "utf8",
    );
    const manifestPath = path.join(tmpDir, "wpdev.json");
    const manifest = JSON.parse(await fs.readFile(manifestPath, "utf8"));
    manifest.features = { ...manifest.features, phpMinVersion: "8.1" };
    await fs.writeFile(
      manifestPath,
      JSON.stringify(manifest, null, 2) + "\n",
      "utf8",
    );
    const res = doctorProject(tmpDir);
    expect(res.ok).toBe(false);
    expect(res.errors.some((e) => /phpMinVersion drift/i.test(e))).toBe(true);
  });
});

describe("doctorProject() — kit's own version is read live (Phase 24.10)", () => {
  // Sanity check: the doctor's "kitVersion vs installed"
  // comparison is anchored to the KIT'S OWN package.json
  // version, not a hard-coded string. This guards against a
  // future "lock the kit version constant" regression.
  test("the registry used by check 3 is the same Map getDepVersions() returns", () => {
    // No dir needed — the test is structural. We just
    // assert that the kit's getDepVersions() is non-empty
    // (it is — covered by depVersions.test.js) and that
    // the doctor doesn't crash when the manifest is at
    // the SAME version as the kit's own package.json.
    // The healthy-path test above is the actual integration
    // check; this one is a regression guard.
    const m = getDepVersions();
    expect(m.size).toBeGreaterThan(0);
  });
});
