import { describe, test, expect, beforeEach, afterEach } from "@jest/globals";
import { promises as fs } from "node:fs";
import * as path from "node:path";
import * as os from "node:os";

import {
  readManifest,
  writeManifest,
  buildManifest,
  MANIFEST_FILENAME,
} from "../../packages/create-wp-project/src/manifest.js";
import { defaultFeatures } from "../../packages/create-wp-project/src/features.js";

/**
 * Phase 20.7 / 20.8 — readManifest() contract + write→read
 * round-trip.
 *
 * Three contracts are locked here:
 *  1. writeManifest(dir, m) followed by readManifest(dir) returns
 *     an object equal (deep) to m. This proves the writer's output
 *     is the reader's input — the two must stay in lock-step.
 *  2. readManifest(dir) returns `null` when the file is absent.
 *     The installer treats null as "not a wp-starter-kit project",
 *     so the function must not throw on ENOENT.
 *  3. readManifest(dir) throws an Error whose `.message` includes
 *     the absolute file path when the file is present but
 *     malformed JSON. A user who hand-edits the file and breaks
 *     it should be told exactly which file to fix.
 *
 * The reader also accepts the case where the file exists but is
 * an empty string (zero bytes). That is technically "malformed"
 * but a very common user error — treat it as malformed JSON with
 * a clear error, not as a silent success.
 */
describe("readManifest() — round-trip (Phase 20.7)", () => {
  let tmp;
  beforeEach(async () => {
    tmp = await fs.mkdtemp(path.join(os.tmpdir(), "wpdev-roundtrip-"));
  });
  afterEach(async () => {
    await fs.rm(tmp, { recursive: true, force: true });
  });

  test("writeManifest → readManifest returns an equal object (deep)", async () => {
    const m = {
      schema: 1,
      kitVersion: "0.2.0",
      distMode: "vendored",
      generatedAt: "2026-06-15T00:00:00.000Z",
      features: defaultFeatures(),
    };
    await writeManifest(tmp, m);
    const round = readManifest(tmp);
    expect(round).toEqual(m);
  });

  test("buildManifest() output round-trips verbatim", async () => {
    const m = buildManifest({
      kitVersion: "0.2.0",
      features: defaultFeatures(),
      generatedAt: "2026-06-15T00:00:00.000Z",
    });
    await writeManifest(tmp, m);
    const round = readManifest(tmp);
    expect(round).toEqual(m);
  });

  test("round-trip preserves unknown future fields (forward-compat)", async () => {
    // A consumer generated by a future kit version may have fields
    // the current reader doesn't know about. The reader must not
    // strip them — that would silently lose data across a kit
    // upgrade. (See plan.v3.md §0.4: BC is mandatory.)
    const m = {
      schema: 1,
      kitVersion: "0.2.0",
      distMode: "vendored",
      generatedAt: "2026-06-15T00:00:00.000Z",
      features: defaultFeatures(),
      futureField: { nested: "data" },
    };
    await writeManifest(tmp, m);
    const round = readManifest(tmp);
    expect(round.futureField).toEqual({ nested: "data" });
  });
});

describe("readManifest() — missing file (Phase 20.7)", () => {
  test("returns null when the file is absent", () => {
    const dir = path.join(os.tmpdir(), "wpdev-no-such-dir-" + Date.now());
    const r = readManifest(dir);
    expect(r).toBeNull();
  });

  test("returns null when the file is absent (real tmp dir, no wpdev-kit.json)", () => {
    const dir = path.join(os.tmpdir(), "wpdev-empty-dir-" + Date.now());
    require("node:fs").mkdirSync(dir, { recursive: true });
    try {
      expect(readManifest(dir)).toBeNull();
    } finally {
      require("node:fs").rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("readManifest() — malformed file (Phase 20.8)", () => {
  let tmp;
  beforeEach(async () => {
    tmp = await fs.mkdtemp(path.join(os.tmpdir(), "wpdev-malformed-"));
  });
  afterEach(async () => {
    await fs.rm(tmp, { recursive: true, force: true });
  });

  test("throws an Error whose message contains the absolute file path", async () => {
    // Write a clearly-broken file (unterminated string).
    await fs.writeFile(
      path.join(tmp, MANIFEST_FILENAME),
      '{ "schema": 1, "kit',
      "utf8",
    );
    expect(() => readManifest(tmp)).toThrow();
    try {
      readManifest(tmp);
    } catch (e) {
      // The error must surface the path so the user knows which
      // wpdev-kit.json is corrupt.
      expect(e.message).toContain(path.join(tmp, MANIFEST_FILENAME));
      expect(e.message).toMatch(/malformed/i);
    }
  });

  test("throws on an empty file (common user error after bad edit)", async () => {
    await fs.writeFile(path.join(tmp, MANIFEST_FILENAME), "", "utf8");
    expect(() => readManifest(tmp)).toThrow(/malformed|JSON|empty/i);
  });

  test("throws on a file that contains a non-JSON sentinel", async () => {
    await fs.writeFile(
      path.join(tmp, MANIFEST_FILENAME),
      "not json at all",
      "utf8",
    );
    expect(() => readManifest(tmp)).toThrow();
  });
});
