<?php // phpcs:ignore - @generation-checksum MY-02-14
/**
 * State City List for 02 - MY.
 *
 * City count: 14
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 02 - MY.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alor Setar', 'wpdev-locations'),
	__('Ayer Hangat', 'wpdev-locations'),
	__('Bedong', 'wpdev-locations'),
	__('Gurun', 'wpdev-locations'),
	__('Jitra', 'wpdev-locations'),
	__('Kampung Kilim', 'wpdev-locations'),
	__('Kampung Kok', 'wpdev-locations'),
	__('Kuah', 'wpdev-locations'),
	__('Kuala Kedah', 'wpdev-locations'),
	__('Kuala Teriang', 'wpdev-locations'),
	__('Kulim', 'wpdev-locations'),
	__('Langkawi', 'wpdev-locations'),
	__('Padang Mat Sirat', 'wpdev-locations'),
	__('Sungai Petani', 'wpdev-locations'),
);
