<?php // phpcs:ignore - @generation-checksum MY-03-7
/**
 * State City List for 03 - MY.
 *
 * City count: 7
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 03 - MY.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Gua Musang', 'wpdev-locations'),
	__('Kampong Kadok', 'wpdev-locations'),
	__('Kampong Pangkal Kalong', 'wpdev-locations'),
	__('Kota Bharu', 'wpdev-locations'),
	__('Pasir Mas', 'wpdev-locations'),
	__('Peringat', 'wpdev-locations'),
	__('Tumpat', 'wpdev-locations'),
);
