<?php // phpcs:ignore - @generation-checksum MY-07-15
/**
 * State City List for 07 - MY.
 *
 * City count: 15
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 07 - MY.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Batu Feringgi', 'wpdev-locations'),
	__('Bukit Mertajam', 'wpdev-locations'),
	__('Butterworth', 'wpdev-locations'),
	__('George Town', 'wpdev-locations'),
	__('Juru', 'wpdev-locations'),
	__('Kampung Batu Feringgi', 'wpdev-locations'),
	__('Kampung Sungai Ara', 'wpdev-locations'),
	__('Kepala Batas', 'wpdev-locations'),
	__('Nibong Tebal', 'wpdev-locations'),
	__('Perai', 'wpdev-locations'),
	__('Permatang Kuching', 'wpdev-locations'),
	__('Seberang Perai', 'wpdev-locations'),
	__('Tanjung Tokong', 'wpdev-locations'),
	__('Tasek Glugor', 'wpdev-locations'),
	__('Telaga Batu', 'wpdev-locations'),
);
