<?php // phpcs:ignore - @generation-checksum MY-08-14
/**
 * State City List for 08 - MY.
 *
 * City count: 14
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 08 - MY.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bagan Serai', 'wpdev-locations'),
	__('Batu Gajah', 'wpdev-locations'),
	__('Bidur', 'wpdev-locations'),
	__('Ipoh', 'wpdev-locations'),
	__('Kampar', 'wpdev-locations'),
	__('Kampong Dungun', 'wpdev-locations'),
	__('Kuala Kangsar', 'wpdev-locations'),
	__('Lumut', 'wpdev-locations'),
	__('Pantai Remis', 'wpdev-locations'),
	__('Parit Buntar', 'wpdev-locations'),
	__('Simpang Empat', 'wpdev-locations'),
	__('Taiping', 'wpdev-locations'),
	__('Tapah Road', 'wpdev-locations'),
	__('Teluk Intan', 'wpdev-locations'),
);
