<?php // phpcs:ignore - @generation-checksum MY-09-3
/**
 * State City List for 09 - MY.
 *
 * City count: 3
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 09 - MY.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Kangar', 'wpdev-locations'),
	__('Kuala Perlis', 'wpdev-locations'),
	__('Pantai Cenang', 'wpdev-locations'),
);
