<?php // phpcs:ignore - @generation-checksum MY-10-24
/**
 * State City List for 10 - MY.
 *
 * City count: 24
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 10 - MY.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ampang', 'wpdev-locations'),
	__('Bagan Pulau Ketam', 'wpdev-locations'),
	__('Banting', 'wpdev-locations'),
	__('Batang Berjuntai', 'wpdev-locations'),
	__('Batu Arang', 'wpdev-locations'),
	__('Jenjarum', 'wpdev-locations'),
	__('Kampong Baharu Balakong', 'wpdev-locations'),
	__('Kampung Baru Subang', 'wpdev-locations'),
	__('Kampung Tanjung Karang', 'wpdev-locations'),
	__('Klang', 'wpdev-locations'),
	__('Kuala Selangor', 'wpdev-locations'),
	__('Kuang', 'wpdev-locations'),
	__('Ladang Seri Kundang', 'wpdev-locations'),
	__('Pelabuhan Klang', 'wpdev-locations'),
	__('Petaling Jaya', 'wpdev-locations'),
	__('Putra Heights', 'wpdev-locations'),
	__('Rawang', 'wpdev-locations'),
	__('Semenyih', 'wpdev-locations'),
	__('Serendah', 'wpdev-locations'),
	__('Shah Alam', 'wpdev-locations'),
	__('Subang Jaya', 'wpdev-locations'),
	__('Sungai Besar', 'wpdev-locations'),
	__('Sungai Pelek New Village', 'wpdev-locations'),
	__('Tanjung Sepat', 'wpdev-locations'),
);
