<?php // phpcs:ignore - @generation-checksum MY-12-16
/**
 * State City List for 12 - MY.
 *
 * City count: 16
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 12 - MY.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bandar Labuan', 'wpdev-locations'),
	__('Beaufort', 'wpdev-locations'),
	__('Donggongon', 'wpdev-locations'),
	__('Keningau', 'wpdev-locations'),
	__('Kinarut', 'wpdev-locations'),
	__('Kota Belud', 'wpdev-locations'),
	__('Kota Kinabalu', 'wpdev-locations'),
	__('Kudat', 'wpdev-locations'),
	__('Lahad Datu', 'wpdev-locations'),
	__('Papar', 'wpdev-locations'),
	__('Putatan', 'wpdev-locations'),
	__('Ranau', 'wpdev-locations'),
	__('Sandakan', 'wpdev-locations'),
	__('Semporna', 'wpdev-locations'),
	__('Taman Rajawali', 'wpdev-locations'),
	__('Tawau', 'wpdev-locations'),
);
