<?php // phpcs:ignore - @generation-checksum MY-13-14
/**
 * State City List for 13 - MY.
 *
 * City count: 14
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 13 - MY.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bintulu', 'wpdev-locations'),
	__('Data Kakus', 'wpdev-locations'),
	__('Kapit', 'wpdev-locations'),
	__('Kuching', 'wpdev-locations'),
	__('Lawas', 'wpdev-locations'),
	__('Lidung Jelo', 'wpdev-locations'),
	__('Limbang', 'wpdev-locations'),
	__('Long Ampan Aing or Abanang', 'wpdev-locations'),
	__('Marudi', 'wpdev-locations'),
	__('Miri', 'wpdev-locations'),
	__('Mukah', 'wpdev-locations'),
	__('Sarikei', 'wpdev-locations'),
	__('Sibu', 'wpdev-locations'),
	__('Simanggang', 'wpdev-locations'),
);
