<?php // phpcs:ignore - @generation-checksum JP-01-81
/**
 * State City List for 01 - JP.
 *
 * City count: 81
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 01 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Abashiri', 'wpdev-locations'),
	__('Abashiri Shi', 'wpdev-locations'),
	__('Akabira', 'wpdev-locations'),
	__('Akabira-shi', 'wpdev-locations'),
	__('Asahikawa', 'wpdev-locations'),
	__('Ashibetsu', 'wpdev-locations'),
	__('Ashibetsu-shi', 'wpdev-locations'),
	__('Bibai', 'wpdev-locations'),
	__('Chitose', 'wpdev-locations'),
	__('Chitose Shi', 'wpdev-locations'),
	__('Date', 'wpdev-locations'),
	__('Date-shi', 'wpdev-locations'),
	__('Ebetsu', 'wpdev-locations'),
	__('Eniwa-shi', 'wpdev-locations'),
	__('Fukagawa', 'wpdev-locations'),
	__('Fukagawa-shi', 'wpdev-locations'),
	__('Furano-shi', 'wpdev-locations'),
	__('Hakodate', 'wpdev-locations'),
	__('Hakodate Shi', 'wpdev-locations'),
	__('Hokuto', 'wpdev-locations'),
	__('Hokuto-shi', 'wpdev-locations'),
	__('Honchō', 'wpdev-locations'),
	__('Ishikari', 'wpdev-locations'),
	__('Ishikari-shi', 'wpdev-locations'),
	__('Iwamizawa', 'wpdev-locations'),
	__('Iwamizawa-shi', 'wpdev-locations'),
	__('Iwanai', 'wpdev-locations'),
	__('Kamiiso', 'wpdev-locations'),
	__('Kamikawa', 'wpdev-locations'),
	__('Kitahiroshima', 'wpdev-locations'),
	__('Kitahiroshima-shi', 'wpdev-locations'),
	__('Kitami', 'wpdev-locations'),
	__('Ktiami Shi', 'wpdev-locations'),
	__('Kushiro', 'wpdev-locations'),
	__('Kushiro Shi', 'wpdev-locations'),
	__('Makubetsu', 'wpdev-locations'),
	__('Mikasa', 'wpdev-locations'),
	__('Mikasa-shi', 'wpdev-locations'),
	__('Mombetsu', 'wpdev-locations'),
	__('Monbetsu Shi', 'wpdev-locations'),
	__('Motomachi', 'wpdev-locations'),
	__('Muroran', 'wpdev-locations'),
	__('Muroran-shi', 'wpdev-locations'),
	__('Nayoro', 'wpdev-locations'),
	__('Nayoro Shi', 'wpdev-locations'),
	__('Nemuro', 'wpdev-locations'),
	__('Nemuro-shi', 'wpdev-locations'),
	__('Niseko Town', 'wpdev-locations'),
	__('Noboribetsu', 'wpdev-locations'),
	__('Noboribetsu-shi', 'wpdev-locations'),
	__('Obihiro', 'wpdev-locations'),
	__('Obihiro Shi', 'wpdev-locations'),
	__('Otaru', 'wpdev-locations'),
	__('Otaru-shi', 'wpdev-locations'),
	__('Otofuke', 'wpdev-locations'),
	__('Rebun Gun', 'wpdev-locations'),
	__('Rishiri Gun', 'wpdev-locations'),
	__('Rishiri Town', 'wpdev-locations'),
	__('Rumoi', 'wpdev-locations'),
	__('Rumoi-shi', 'wpdev-locations'),
	__('Sapporo', 'wpdev-locations'),
	__('Sapporo-shi', 'wpdev-locations'),
	__('Shibetsu', 'wpdev-locations'),
	__('Shibetsu Shi', 'wpdev-locations'),
	__('Shimo-furano', 'wpdev-locations'),
	__('Shiraoi', 'wpdev-locations'),
	__('Shizunai-furukawachō', 'wpdev-locations'),
	__('Sunagawa', 'wpdev-locations'),
	__('Sunagawa-shi', 'wpdev-locations'),
	__('Takikawa', 'wpdev-locations'),
	__('Takikawa-shi', 'wpdev-locations'),
	__('Tomakomai', 'wpdev-locations'),
	__('Tomakomai Shi', 'wpdev-locations'),
	__('Tōbetsu', 'wpdev-locations'),
	__('Utashinai', 'wpdev-locations'),
	__('Utashinai-shi', 'wpdev-locations'),
	__('Wakkanai', 'wpdev-locations'),
	__('Wakkanai Shi', 'wpdev-locations'),
	__('Yoichi', 'wpdev-locations'),
	__('Yūbari', 'wpdev-locations'),
	__('Yūbari-shi', 'wpdev-locations'),
);
