<?php // phpcs:ignore - @generation-checksum JP-02-21
/**
 * State City List for 02 - JP.
 *
 * City count: 21
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 02 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aomori', 'wpdev-locations'),
	__('Aomori Shi', 'wpdev-locations'),
	__('Goshogawara', 'wpdev-locations'),
	__('Goshogawara Shi', 'wpdev-locations'),
	__('Hachinohe', 'wpdev-locations'),
	__('Hachinohe Shi', 'wpdev-locations'),
	__('Hirakawa', 'wpdev-locations'),
	__('Hirakawa Shi', 'wpdev-locations'),
	__('Hirosaki', 'wpdev-locations'),
	__('Hirosaki Shi', 'wpdev-locations'),
	__('Kuroishi', 'wpdev-locations'),
	__('Kuroishi Shi', 'wpdev-locations'),
	__('Misawa', 'wpdev-locations'),
	__('Misawa Shi', 'wpdev-locations'),
	__('Mutsu', 'wpdev-locations'),
	__('Mutsu-shi', 'wpdev-locations'),
	__('Namioka', 'wpdev-locations'),
	__('Shimokizukuri', 'wpdev-locations'),
	__('Towada Shi', 'wpdev-locations'),
	__('Tsugaru', 'wpdev-locations'),
	__('Tsugaru Shi', 'wpdev-locations'),
);
