<?php // phpcs:ignore - @generation-checksum JP-03-32
/**
 * State City List for 03 - JP.
 *
 * City count: 32
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 03 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Hachimantai', 'wpdev-locations'),
	__('Hachimantai Shi', 'wpdev-locations'),
	__('Hanamaki', 'wpdev-locations'),
	__('Hanamaki Shi', 'wpdev-locations'),
	__('Ichinohe', 'wpdev-locations'),
	__('Ichinoseki', 'wpdev-locations'),
	__('Ichinoseki-shi', 'wpdev-locations'),
	__('Iwate-gun', 'wpdev-locations'),
	__('Kamaishi', 'wpdev-locations'),
	__('Kamaishi-shi', 'wpdev-locations'),
	__('Kitakami', 'wpdev-locations'),
	__('Kitakami-shi', 'wpdev-locations'),
	__('Kuji', 'wpdev-locations'),
	__('Kuji-shi', 'wpdev-locations'),
	__('Miyako', 'wpdev-locations'),
	__('Miyako-shi', 'wpdev-locations'),
	__('Mizusawa', 'wpdev-locations'),
	__('Morioka', 'wpdev-locations'),
	__('Morioka-shi', 'wpdev-locations'),
	__('Ninohe', 'wpdev-locations'),
	__('Ninohe Shi', 'wpdev-locations'),
	__('Rikuzentakata-shi', 'wpdev-locations'),
	__('Shizukuishi', 'wpdev-locations'),
	__('Takizawa-shi', 'wpdev-locations'),
	__('Tōno', 'wpdev-locations'),
	__('Tōno-shi', 'wpdev-locations'),
	__('Yamada', 'wpdev-locations'),
	__('Ōfunato', 'wpdev-locations'),
	__('Ōfunato-shi', 'wpdev-locations'),
	__('Ōshū', 'wpdev-locations'),
	__('Ōshū-shi', 'wpdev-locations'),
	__('Ōtsuchi', 'wpdev-locations'),
);
