<?php // phpcs:ignore - @generation-checksum JP-05-27
/**
 * State City List for 05 - JP.
 *
 * City count: 27
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 05 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akita', 'wpdev-locations'),
	__('Akita Shi', 'wpdev-locations'),
	__('Daisen', 'wpdev-locations'),
	__('Daisen-shi', 'wpdev-locations'),
	__('Hanawa', 'wpdev-locations'),
	__('Kakunodatemachi', 'wpdev-locations'),
	__('Katagami', 'wpdev-locations'),
	__('Katagami-shi', 'wpdev-locations'),
	__('Kazuno Shi', 'wpdev-locations'),
	__('Kitaakita-shi', 'wpdev-locations'),
	__('Nikaho-shi', 'wpdev-locations'),
	__('Noshiro', 'wpdev-locations'),
	__('Noshiro Shi', 'wpdev-locations'),
	__('Oga', 'wpdev-locations'),
	__('Oga-shi', 'wpdev-locations'),
	__('Semboku-shi', 'wpdev-locations'),
	__('Takanosu', 'wpdev-locations'),
	__('Tennō', 'wpdev-locations'),
	__('Yokote', 'wpdev-locations'),
	__('Yokote-shi', 'wpdev-locations'),
	__('Yurihonjō', 'wpdev-locations'),
	__('Yurihonjō-shi', 'wpdev-locations'),
	__('Yuzawa', 'wpdev-locations'),
	__('Yuzawa-shi', 'wpdev-locations'),
	__('Ōdate', 'wpdev-locations'),
	__('Ōdate-shi', 'wpdev-locations'),
	__('Ōmagari', 'wpdev-locations'),
);
