<?php // phpcs:ignore - @generation-checksum JP-06-27
/**
 * State City List for 06 - JP.
 *
 * City count: 27
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 06 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Higashine', 'wpdev-locations'),
	__('Higashine Shi', 'wpdev-locations'),
	__('Kaminoyama', 'wpdev-locations'),
	__('Kaminoyama-shi', 'wpdev-locations'),
	__('Murayama', 'wpdev-locations'),
	__('Murayama Shi', 'wpdev-locations'),
	__('Nagai', 'wpdev-locations'),
	__('Nagai-shi', 'wpdev-locations'),
	__('Nanyō Shi', 'wpdev-locations'),
	__('Obanazawa', 'wpdev-locations'),
	__('Obanazawa Shi', 'wpdev-locations'),
	__('Sagae', 'wpdev-locations'),
	__('Sagae-shi', 'wpdev-locations'),
	__('Sakata', 'wpdev-locations'),
	__('Sakata Shi', 'wpdev-locations'),
	__('Shinjō', 'wpdev-locations'),
	__('Shinjō Shi', 'wpdev-locations'),
	__('Takahata', 'wpdev-locations'),
	__('Tendō', 'wpdev-locations'),
	__('Tendō Shi', 'wpdev-locations'),
	__('Tsuruoka', 'wpdev-locations'),
	__('Tsuruoka Shi', 'wpdev-locations'),
	__('Yamagata', 'wpdev-locations'),
	__('Yamagata Shi', 'wpdev-locations'),
	__('Yonezawa', 'wpdev-locations'),
	__('Yonezawa Shi', 'wpdev-locations'),
	__('Yuza', 'wpdev-locations'),
);
