<?php // phpcs:ignore - @generation-checksum JP-08-72
/**
 * State City List for 08 - JP.
 *
 * City count: 72
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 08 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ami', 'wpdev-locations'),
	__('Bandō', 'wpdev-locations'),
	__('Bandō-shi', 'wpdev-locations'),
	__('Chikusei', 'wpdev-locations'),
	__('Chikusei-shi', 'wpdev-locations'),
	__('Daigo', 'wpdev-locations'),
	__('Edosaki', 'wpdev-locations'),
	__('Fujishiro', 'wpdev-locations'),
	__('Funaishikawa', 'wpdev-locations'),
	__('Hitachi', 'wpdev-locations'),
	__('Hitachi-Naka', 'wpdev-locations'),
	__('Hitachi-ota', 'wpdev-locations'),
	__('Hitachi-shi', 'wpdev-locations'),
	__('Hitachinaka-shi', 'wpdev-locations'),
	__('Hitachiōmiya-shi', 'wpdev-locations'),
	__('Hitachiōta-shi', 'wpdev-locations'),
	__('Hokota-shi', 'wpdev-locations'),
	__('Inashiki', 'wpdev-locations'),
	__('Inashiki-shi', 'wpdev-locations'),
	__('Ishige', 'wpdev-locations'),
	__('Ishioka', 'wpdev-locations'),
	__('Ishioka-shi', 'wpdev-locations'),
	__('Itako', 'wpdev-locations'),
	__('Itako-shi', 'wpdev-locations'),
	__('Iwai', 'wpdev-locations'),
	__('Iwase', 'wpdev-locations'),
	__('Jōsō-shi', 'wpdev-locations'),
	__('Kamisu-shi', 'wpdev-locations'),
	__('Kasama', 'wpdev-locations'),
	__('Kasama-shi', 'wpdev-locations'),
	__('Kashima-shi', 'wpdev-locations'),
	__('Kasumigaura', 'wpdev-locations'),
	__('Kasumigaura-shi', 'wpdev-locations'),
	__('Katsuta', 'wpdev-locations'),
	__('Kitaibaraki', 'wpdev-locations'),
	__('Kitaibaraki-shi', 'wpdev-locations'),
	__('Koga', 'wpdev-locations'),
	__('Koga-shi', 'wpdev-locations'),
	__('Makabe', 'wpdev-locations'),
	__('Mito', 'wpdev-locations'),
	__('Mito-shi', 'wpdev-locations'),
	__('Mitsukaidō', 'wpdev-locations'),
	__('Moriya', 'wpdev-locations'),
	__('Moriya-shi', 'wpdev-locations'),
	__('Naka', 'wpdev-locations'),
	__('Naka-gun', 'wpdev-locations'),
	__('Namegata', 'wpdev-locations'),
	__('Namegata-shi', 'wpdev-locations'),
	__('Okunoya', 'wpdev-locations'),
	__('Omitama-shi', 'wpdev-locations'),
	__('Ryūgasaki', 'wpdev-locations'),
	__('Ryūgasaki-shi', 'wpdev-locations'),
	__('Sakai', 'wpdev-locations'),
	__('Sakuragawa', 'wpdev-locations'),
	__('Sakuragawa-shi', 'wpdev-locations'),
	__('Shimodate', 'wpdev-locations'),
	__('Shimotsuma-shi', 'wpdev-locations'),
	__('Takahagi', 'wpdev-locations'),
	__('Tomobe', 'wpdev-locations'),
	__('Toride', 'wpdev-locations'),
	__('Toride-shi', 'wpdev-locations'),
	__('Tsuchiura-shi', 'wpdev-locations'),
	__('Tsukuba', 'wpdev-locations'),
	__('Tsukuba-shi', 'wpdev-locations'),
	__('Tsukubamirai', 'wpdev-locations'),
	__('Tsukubamirai-shi', 'wpdev-locations'),
	__('Ushiku', 'wpdev-locations'),
	__('Ushiku-shi', 'wpdev-locations'),
	__('Yūki', 'wpdev-locations'),
	__('Yūki-shi', 'wpdev-locations'),
	__('Ōarai', 'wpdev-locations'),
	__('Ōmiya', 'wpdev-locations'),
);
