<?php // phpcs:ignore - @generation-checksum JP-11-83
/**
 * State City List for 11 - JP.
 *
 * City count: 83
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 11 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ageo Shi', 'wpdev-locations'),
	__('Ageoshimo', 'wpdev-locations'),
	__('Asaka', 'wpdev-locations'),
	__('Asaka-shi', 'wpdev-locations'),
	__('Chichibu', 'wpdev-locations'),
	__('Chichibu-shi', 'wpdev-locations'),
	__('Fujimi-shi', 'wpdev-locations'),
	__('Fujimino Shi', 'wpdev-locations'),
	__('Fukaya-shi', 'wpdev-locations'),
	__('Fukayachō', 'wpdev-locations'),
	__('Fukiage-fujimi', 'wpdev-locations'),
	__('Gyōda', 'wpdev-locations'),
	__('Hannō', 'wpdev-locations'),
	__('Hannō-shi', 'wpdev-locations'),
	__('Hanyū', 'wpdev-locations'),
	__('Hanyū-shi', 'wpdev-locations'),
	__('Hasuda', 'wpdev-locations'),
	__('Hasuda-shi', 'wpdev-locations'),
	__('Hatogaya-honchō', 'wpdev-locations'),
	__('Hidaka-shi', 'wpdev-locations'),
	__('Higashimatsuyama Shi', 'wpdev-locations'),
	__('Hiki-gun', 'wpdev-locations'),
	__('Honjō', 'wpdev-locations'),
	__('Honjō Shi', 'wpdev-locations'),
	__('Iruma-shi', 'wpdev-locations'),
	__('Iwatsuki', 'wpdev-locations'),
	__('Kamifukuoka', 'wpdev-locations'),
	__('Kasukabe', 'wpdev-locations'),
	__('Kasukabe Shi', 'wpdev-locations'),
	__('Kawagoe', 'wpdev-locations'),
	__('Kawagoe-shi', 'wpdev-locations'),
	__('Kawaguchi', 'wpdev-locations'),
	__('Kawaguchi-shi', 'wpdev-locations'),
	__('Kazo', 'wpdev-locations'),
	__('Kazo-shi', 'wpdev-locations'),
	__('Kisai', 'wpdev-locations'),
	__('Kitamoto Shi', 'wpdev-locations'),
	__('Kodamachō-kodamaminami', 'wpdev-locations'),
	__('Konosu-Shi', 'wpdev-locations'),
	__('Koshigaya Shi', 'wpdev-locations'),
	__('Kuki-shi', 'wpdev-locations'),
	__('Kukichūō', 'wpdev-locations'),
	__('Kumagaya Shi', 'wpdev-locations'),
	__('Kurihashi', 'wpdev-locations'),
	__('Kōnosu', 'wpdev-locations'),
	__('Menuma', 'wpdev-locations'),
	__('Misato Shi', 'wpdev-locations'),
	__('Morohongō', 'wpdev-locations'),
	__('Niiza-shi', 'wpdev-locations'),
	__('Ogawa', 'wpdev-locations'),
	__('Okegawa', 'wpdev-locations'),
	__('Okegawa-shi', 'wpdev-locations'),
	__('Saitama', 'wpdev-locations'),
	__('Saitama-shi', 'wpdev-locations'),
	__('Sakado', 'wpdev-locations'),
	__('Sakado-shi', 'wpdev-locations'),
	__('Satte', 'wpdev-locations'),
	__('Satte Shi', 'wpdev-locations'),
	__('Sayama', 'wpdev-locations'),
	__('Shiki', 'wpdev-locations'),
	__('Shiki Shi', 'wpdev-locations'),
	__('Shimotoda', 'wpdev-locations'),
	__('Shiraoka', 'wpdev-locations'),
	__('Shiraoka-shi', 'wpdev-locations'),
	__('Shōbu', 'wpdev-locations'),
	__('Sugito', 'wpdev-locations'),
	__('Sōka', 'wpdev-locations'),
	__('Sōka Shi', 'wpdev-locations'),
	__('Toda-shi', 'wpdev-locations'),
	__('Tokorozawa', 'wpdev-locations'),
	__('Tokorozawa-shi', 'wpdev-locations'),
	__('Tsurugashima-shi', 'wpdev-locations'),
	__('Wako', 'wpdev-locations'),
	__('Wakō-shi', 'wpdev-locations'),
	__('Warabi-shi', 'wpdev-locations'),
	__('Yashio', 'wpdev-locations'),
	__('Yashio-shi', 'wpdev-locations'),
	__('Yono', 'wpdev-locations'),
	__('Yorii', 'wpdev-locations'),
	__('Yoshikawa', 'wpdev-locations'),
	__('Yoshikawa Shi', 'wpdev-locations'),
	__('Ōi', 'wpdev-locations'),
	__('Ōsato-gun', 'wpdev-locations'),
);
