<?php // phpcs:ignore - @generation-checksum JP-12-65
/**
 * State City List for 12 - JP.
 *
 * City count: 65
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 12 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Abiko', 'wpdev-locations'),
	__('Abiko-shi', 'wpdev-locations'),
	__('Asahi-shi', 'wpdev-locations'),
	__('Chiba', 'wpdev-locations'),
	__('Chōshi-shi', 'wpdev-locations'),
	__('Funabashi-shi', 'wpdev-locations'),
	__('Futtsu', 'wpdev-locations'),
	__('Hasaki', 'wpdev-locations'),
	__('Honchō', 'wpdev-locations'),
	__('Ichihara', 'wpdev-locations'),
	__('Ichihara Shi', 'wpdev-locations'),
	__('Ichikawa Shi', 'wpdev-locations'),
	__('Inzai-shi', 'wpdev-locations'),
	__('Isumi', 'wpdev-locations'),
	__('Isumi Shi', 'wpdev-locations'),
	__('Kamagaya Shi', 'wpdev-locations'),
	__('Kamogawa', 'wpdev-locations'),
	__('Kamogawa-shi', 'wpdev-locations'),
	__('Kashiwa', 'wpdev-locations'),
	__('Kashiwa Shi', 'wpdev-locations'),
	__('Katori-shi', 'wpdev-locations'),
	__('Katsuura', 'wpdev-locations'),
	__('Katsuura-shi', 'wpdev-locations'),
	__('Kimitsu', 'wpdev-locations'),
	__('Kisarazu', 'wpdev-locations'),
	__('Kisarazu Shi', 'wpdev-locations'),
	__('Matsudo Shi', 'wpdev-locations'),
	__('Minamibōsō Shi', 'wpdev-locations'),
	__('Mobara', 'wpdev-locations'),
	__('Mobara Shi', 'wpdev-locations'),
	__('Nagareyama', 'wpdev-locations'),
	__('Nagareyama-shi', 'wpdev-locations'),
	__('Narashino-shi', 'wpdev-locations'),
	__('Narita', 'wpdev-locations'),
	__('Narita-shi', 'wpdev-locations'),
	__('Narutō', 'wpdev-locations'),
	__('Noda', 'wpdev-locations'),
	__('Noda-shi', 'wpdev-locations'),
	__('Omigawa', 'wpdev-locations'),
	__('Sakura', 'wpdev-locations'),
	__('Sakura-shi', 'wpdev-locations'),
	__('Sambu-gun', 'wpdev-locations'),
	__('Sanmu', 'wpdev-locations'),
	__('Sanmu-shi', 'wpdev-locations'),
	__('Sawara', 'wpdev-locations'),
	__('Shiroi', 'wpdev-locations'),
	__('Shiroi-shi', 'wpdev-locations'),
	__('Shisui', 'wpdev-locations'),
	__('Sodegaura-shi', 'wpdev-locations'),
	__('Sōsa-shi', 'wpdev-locations'),
	__('Tateyama', 'wpdev-locations'),
	__('Tateyama-shi', 'wpdev-locations'),
	__('Tomisato-shi', 'wpdev-locations'),
	__('Tōgane', 'wpdev-locations'),
	__('Tōgane-shi', 'wpdev-locations'),
	__('Urayasu-shi', 'wpdev-locations'),
	__('Yachimata', 'wpdev-locations'),
	__('Yachimata-shi', 'wpdev-locations'),
	__('Yachiyo-shi', 'wpdev-locations'),
	__('Yotsukaidō', 'wpdev-locations'),
	__('Yotsukaidō-shi', 'wpdev-locations'),
	__('Yōkaichiba', 'wpdev-locations'),
	__('Ōami', 'wpdev-locations'),
	__('Ōamishirasato-shi', 'wpdev-locations'),
	__('Ōhara', 'wpdev-locations'),
);
