<?php // phpcs:ignore - @generation-checksum JP-13-63
/**
 * State City List for 13 - JP.
 *
 * City count: 63
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 13 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Adachi Ku', 'wpdev-locations'),
	__('Akiruno-shi', 'wpdev-locations'),
	__('Akishima-shi', 'wpdev-locations'),
	__('Arakawa Ku', 'wpdev-locations'),
	__('Bunkyō-ku', 'wpdev-locations'),
	__('Chiyoda-ku', 'wpdev-locations'),
	__('Chōfu', 'wpdev-locations'),
	__('Chōfu-shi', 'wpdev-locations'),
	__('Chūō Ku', 'wpdev-locations'),
	__('Edogawa Ku', 'wpdev-locations'),
	__('Fuchū-shi', 'wpdev-locations'),
	__('Fussa', 'wpdev-locations'),
	__('Hachiōji', 'wpdev-locations'),
	__('Hamura-shi', 'wpdev-locations'),
	__('Higashi-murayama-shi', 'wpdev-locations'),
	__('Higashikurume-shi', 'wpdev-locations'),
	__('Higashimurayama', 'wpdev-locations'),
	__('Higashiyamato', 'wpdev-locations'),
	__('Higashiyamato-shi', 'wpdev-locations'),
	__('Hino', 'wpdev-locations'),
	__('Hino-shi', 'wpdev-locations'),
	__('Inagi-shi', 'wpdev-locations'),
	__('Itabashi-ku', 'wpdev-locations'),
	__('Itsukaichi', 'wpdev-locations'),
	__('Kamirenjaku', 'wpdev-locations'),
	__('Katsushika Ku', 'wpdev-locations'),
	__('Kita-ku', 'wpdev-locations'),
	__('Kiyose-shi', 'wpdev-locations'),
	__('Kodaira-shi', 'wpdev-locations'),
	__('Koganei-shi', 'wpdev-locations'),
	__('Kokubunji', 'wpdev-locations'),
	__('Kokubunji-shi', 'wpdev-locations'),
	__('Komae-shi', 'wpdev-locations'),
	__('Kunitachi-shi', 'wpdev-locations'),
	__('Kōtō-ku', 'wpdev-locations'),
	__('Machida', 'wpdev-locations'),
	__('Machida-shi', 'wpdev-locations'),
	__('Meguro-ku', 'wpdev-locations'),
	__('Minato-ku', 'wpdev-locations'),
	__('Mitaka-shi', 'wpdev-locations'),
	__('Musashimurayama-shi', 'wpdev-locations'),
	__('Musashino', 'wpdev-locations'),
	__('Musashino-shi', 'wpdev-locations'),
	__('Nakano-ku', 'wpdev-locations'),
	__('Nerima-ku', 'wpdev-locations'),
	__('Nishi-Tokyo-shi', 'wpdev-locations'),
	__('Nishitōkyō-shi', 'wpdev-locations'),
	__('Setagaya-ku', 'wpdev-locations'),
	__('Shibuya-ku', 'wpdev-locations'),
	__('Shinagawa-ku', 'wpdev-locations'),
	__('Shinjuku-ku', 'wpdev-locations'),
	__('Suginami-ku', 'wpdev-locations'),
	__('Sumida-ku', 'wpdev-locations'),
	__('Tachikawa-shi', 'wpdev-locations'),
	__('Taitō-ku', 'wpdev-locations'),
	__('Tama-shi', 'wpdev-locations'),
	__('Tanashichō', 'wpdev-locations'),
	__('Tokyo', 'wpdev-locations'),
	__('Toshima-ku', 'wpdev-locations'),
	__('Urayasu', 'wpdev-locations'),
	__('Ōme', 'wpdev-locations'),
	__('Ōme-shi', 'wpdev-locations'),
	__('Ōta-ku', 'wpdev-locations'),
);
