<?php // phpcs:ignore - @generation-checksum JP-15-46
/**
 * State City List for 15 - JP.
 *
 * City count: 46
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 15 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Agano Shi', 'wpdev-locations'),
	__('Arai', 'wpdev-locations'),
	__('Gosen', 'wpdev-locations'),
	__('Gosen Shi', 'wpdev-locations'),
	__('Itoigawa', 'wpdev-locations'),
	__('Itoigawa Shi', 'wpdev-locations'),
	__('Jōetsu', 'wpdev-locations'),
	__('Jōetsu Shi', 'wpdev-locations'),
	__('Kameda-honchō', 'wpdev-locations'),
	__('Kamo', 'wpdev-locations'),
	__('Kamo Shi', 'wpdev-locations'),
	__('Kashiwazaki', 'wpdev-locations'),
	__('Kashiwazaki Shi', 'wpdev-locations'),
	__('Maki', 'wpdev-locations'),
	__('Minamiuonuma Shi', 'wpdev-locations'),
	__('Mitsuke', 'wpdev-locations'),
	__('Mitsuke Shi', 'wpdev-locations'),
	__('Muikamachi', 'wpdev-locations'),
	__('Murakami Shi', 'wpdev-locations'),
	__('Muramatsu', 'wpdev-locations'),
	__('Myoko-shi', 'wpdev-locations'),
	__('Nagaoka', 'wpdev-locations'),
	__('Nagaoka Shi', 'wpdev-locations'),
	__('Niigata', 'wpdev-locations'),
	__('Niigata Shi', 'wpdev-locations'),
	__('Niitsu-honchō', 'wpdev-locations'),
	__('Ojiya', 'wpdev-locations'),
	__('Ojiya-shi', 'wpdev-locations'),
	__('Ryōtsu-minato', 'wpdev-locations'),
	__('Sado Shi', 'wpdev-locations'),
	__('Sanjō Shi', 'wpdev-locations'),
	__('Shibata', 'wpdev-locations'),
	__('Shibata Shi', 'wpdev-locations'),
	__('Shiozawa', 'wpdev-locations'),
	__('Shirone', 'wpdev-locations'),
	__('Suibara', 'wpdev-locations'),
	__('Tainai', 'wpdev-locations'),
	__('Tainai Shi', 'wpdev-locations'),
	__('Tochio-honchō', 'wpdev-locations'),
	__('Tsubame', 'wpdev-locations'),
	__('Tsubame Shi', 'wpdev-locations'),
	__('Tōkamachi', 'wpdev-locations'),
	__('Tōkamachi-shi', 'wpdev-locations'),
	__('Uonuma', 'wpdev-locations'),
	__('Uonuma Shi', 'wpdev-locations'),
	__('Yoshida-kasugachō', 'wpdev-locations'),
);
