<?php // phpcs:ignore - @generation-checksum JP-17-18
/**
 * State City List for 17 - JP.
 *
 * City count: 18
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 17 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Hakui', 'wpdev-locations'),
	__('Hakui Shi', 'wpdev-locations'),
	__('Hakusan Shi', 'wpdev-locations'),
	__('Kaga Shi', 'wpdev-locations'),
	__('Kahoku Shi', 'wpdev-locations'),
	__('Kanazawa', 'wpdev-locations'),
	__('Kanazawa-shi', 'wpdev-locations'),
	__('Komatsu', 'wpdev-locations'),
	__('Matsutō', 'wpdev-locations'),
	__('Nanao Shi', 'wpdev-locations'),
	__('Nomi Shi', 'wpdev-locations'),
	__('Nonoichi', 'wpdev-locations'),
	__('Nonoichi-shi', 'wpdev-locations'),
	__('Suzu', 'wpdev-locations'),
	__('Suzu Shi', 'wpdev-locations'),
	__('Tsubata', 'wpdev-locations'),
	__('Tsurugi-asahimachi', 'wpdev-locations'),
	__('Wajima Shi', 'wpdev-locations'),
);
