<?php // phpcs:ignore - @generation-checksum JP-18-19
/**
 * State City List for 18 - JP.
 *
 * City count: 19
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 18 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Asahi', 'wpdev-locations'),
	__('Awara-shi', 'wpdev-locations'),
	__('Echizen-shi', 'wpdev-locations'),
	__('Fukui-shi', 'wpdev-locations'),
	__('Katsuyama', 'wpdev-locations'),
	__('Katsuyama Shi', 'wpdev-locations'),
	__('Maruoka', 'wpdev-locations'),
	__('Mikuni', 'wpdev-locations'),
	__('Obama', 'wpdev-locations'),
	__('Obama-shi', 'wpdev-locations'),
	__('Ono', 'wpdev-locations'),
	__('Sabae', 'wpdev-locations'),
	__('Sabae-shi', 'wpdev-locations'),
	__('Sakai-shi', 'wpdev-locations'),
	__('Takefu', 'wpdev-locations'),
	__('Tsuruga', 'wpdev-locations'),
	__('Tsuruga-shi', 'wpdev-locations'),
	__('Ōi-gun', 'wpdev-locations'),
	__('Ōno-shi', 'wpdev-locations'),
);
