<?php // phpcs:ignore - @generation-checksum JP-19-23
/**
 * State City List for 19 - JP.
 *
 * City count: 23
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 19 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Chūō-shi', 'wpdev-locations'),
	__('Enzan', 'wpdev-locations'),
	__('Fuefuki-shi', 'wpdev-locations'),
	__('Fuji-yoshida Shi', 'wpdev-locations'),
	__('Fujikawaguchiko', 'wpdev-locations'),
	__('Fujiyoshida', 'wpdev-locations'),
	__('Hokuto', 'wpdev-locations'),
	__('Hokuto-shi', 'wpdev-locations'),
	__('Isawa', 'wpdev-locations'),
	__('Kai-shi', 'wpdev-locations'),
	__('Kōfu', 'wpdev-locations'),
	__('Kōfu-shi', 'wpdev-locations'),
	__('Kōshū-shi', 'wpdev-locations'),
	__('Minami Alps-shi', 'wpdev-locations'),
	__('Nirasaki', 'wpdev-locations'),
	__('Nirasaki-shi', 'wpdev-locations'),
	__('Ryūō', 'wpdev-locations'),
	__('Tsuru-shi', 'wpdev-locations'),
	__('Uenohara', 'wpdev-locations'),
	__('Uenohara-shi', 'wpdev-locations'),
	__('Yamanashi-shi', 'wpdev-locations'),
	__('Ōtsuki', 'wpdev-locations'),
	__('Ōtsuki-shi', 'wpdev-locations'),
);
