<?php // phpcs:ignore - @generation-checksum JP-23-70
/**
 * State City List for 23 - JP.
 *
 * City count: 70
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 23 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aisai-shi', 'wpdev-locations'),
	__('Ama-gun', 'wpdev-locations'),
	__('Anjō-shi', 'wpdev-locations'),
	__('Chiryū', 'wpdev-locations'),
	__('Chiryū-shi', 'wpdev-locations'),
	__('Chita', 'wpdev-locations'),
	__('Chita-shi', 'wpdev-locations'),
	__('Gamagōri', 'wpdev-locations'),
	__('Gamagōri-shi', 'wpdev-locations'),
	__('Handa', 'wpdev-locations'),
	__('Handa-shi', 'wpdev-locations'),
	__('Hekinan', 'wpdev-locations'),
	__('Hekinan-shi', 'wpdev-locations'),
	__('Ichinomiya', 'wpdev-locations'),
	__('Ichinomiya-shi', 'wpdev-locations'),
	__('Inazawa', 'wpdev-locations'),
	__('Inazawa-shi', 'wpdev-locations'),
	__('Inuyama', 'wpdev-locations'),
	__('Inuyama-shi', 'wpdev-locations'),
	__('Ishiki', 'wpdev-locations'),
	__('Iwakura', 'wpdev-locations'),
	__('Iwakura-shi', 'wpdev-locations'),
	__('Kanie', 'wpdev-locations'),
	__('Kariya', 'wpdev-locations'),
	__('Kariya-shi', 'wpdev-locations'),
	__('Kasugai', 'wpdev-locations'),
	__('Kasugai-shi', 'wpdev-locations'),
	__('Kitanagoya', 'wpdev-locations'),
	__('Kitanagoya-shi', 'wpdev-locations'),
	__('Kiyosu-shi', 'wpdev-locations'),
	__('Komaki', 'wpdev-locations'),
	__('Komaki-shi', 'wpdev-locations'),
	__('Kozakai-chō', 'wpdev-locations'),
	__('Kuroda', 'wpdev-locations'),
	__('Kōnan', 'wpdev-locations'),
	__('Kōnan-shi', 'wpdev-locations'),
	__('Miyoshi-shi', 'wpdev-locations'),
	__('Nagakute-shi', 'wpdev-locations'),
	__('Nagoya', 'wpdev-locations'),
	__('Nishio', 'wpdev-locations'),
	__('Nishio-shi', 'wpdev-locations'),
	__('Nisshin-shi', 'wpdev-locations'),
	__('Okazaki-shi', 'wpdev-locations'),
	__('Owariasahi-shi', 'wpdev-locations'),
	__('Seto', 'wpdev-locations'),
	__('Seto-shi', 'wpdev-locations'),
	__('Shinshiro', 'wpdev-locations'),
	__('Shinshiro-shi', 'wpdev-locations'),
	__('Sobue', 'wpdev-locations'),
	__('Tahara', 'wpdev-locations'),
	__('Tahara-shi', 'wpdev-locations'),
	__('Takahama', 'wpdev-locations'),
	__('Takahama-shi', 'wpdev-locations'),
	__('Taketoyo', 'wpdev-locations'),
	__('Tokoname', 'wpdev-locations'),
	__('Tokoname-shi', 'wpdev-locations'),
	__('Toyoake', 'wpdev-locations'),
	__('Toyoake-shi', 'wpdev-locations'),
	__('Toyohama', 'wpdev-locations'),
	__('Toyohashi', 'wpdev-locations'),
	__('Toyohashi-shi', 'wpdev-locations'),
	__('Toyokawa', 'wpdev-locations'),
	__('Toyokawa-shi', 'wpdev-locations'),
	__('Toyota-shi', 'wpdev-locations'),
	__('Tsushima', 'wpdev-locations'),
	__('Tsushima-shi', 'wpdev-locations'),
	__('Tōkai-shi', 'wpdev-locations'),
	__('Yatomi-shi', 'wpdev-locations'),
	__('Ōbu', 'wpdev-locations'),
	__('Ōbu-shi', 'wpdev-locations'),
);
