<?php // phpcs:ignore - @generation-checksum JP-24-28
/**
 * State City List for 24 - JP.
 *
 * City count: 28
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 24 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Hisai-motomachi', 'wpdev-locations'),
	__('Iga-shi', 'wpdev-locations'),
	__('Inabe', 'wpdev-locations'),
	__('Inabe-shi', 'wpdev-locations'),
	__('Ise', 'wpdev-locations'),
	__('Ise-shi', 'wpdev-locations'),
	__('Kameyama', 'wpdev-locations'),
	__('Kameyama Shi', 'wpdev-locations'),
	__('Kawage', 'wpdev-locations'),
	__('Komono', 'wpdev-locations'),
	__('Kumano', 'wpdev-locations'),
	__('Kumano-shi', 'wpdev-locations'),
	__('Kuwana', 'wpdev-locations'),
	__('Kuwana-shi', 'wpdev-locations'),
	__('Matsuzaka-shi', 'wpdev-locations'),
	__('Nabari', 'wpdev-locations'),
	__('Nabari-shi', 'wpdev-locations'),
	__('Owase', 'wpdev-locations'),
	__('Shima', 'wpdev-locations'),
	__('Shima-shi', 'wpdev-locations'),
	__('Suzuka', 'wpdev-locations'),
	__('Suzuka-shi', 'wpdev-locations'),
	__('Toba', 'wpdev-locations'),
	__('Toba-shi', 'wpdev-locations'),
	__('Tsu', 'wpdev-locations'),
	__('Tsu-shi', 'wpdev-locations'),
	__('Ueno-ebisumachi', 'wpdev-locations'),
	__('Yokkaichi-shi', 'wpdev-locations'),
);
