<?php // phpcs:ignore - @generation-checksum JP-25-24
/**
 * State City List for 25 - JP.
 *
 * City count: 24
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 25 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Higashiōmi-shi', 'wpdev-locations'),
	__('Hikone', 'wpdev-locations'),
	__('Hikone-shi', 'wpdev-locations'),
	__('Hino', 'wpdev-locations'),
	__('Kitahama', 'wpdev-locations'),
	__('Konan-shi', 'wpdev-locations'),
	__('Kusatsu', 'wpdev-locations'),
	__('Kusatsu-shi', 'wpdev-locations'),
	__('Kōka-shi', 'wpdev-locations'),
	__('Maibara', 'wpdev-locations'),
	__('Maibara-shi', 'wpdev-locations'),
	__('Minakuchichō-matoba', 'wpdev-locations'),
	__('Moriyama', 'wpdev-locations'),
	__('Moriyama-shi', 'wpdev-locations'),
	__('Nagahama', 'wpdev-locations'),
	__('Nagahama-shi', 'wpdev-locations'),
	__('Rittō-shi', 'wpdev-locations'),
	__('Takashima', 'wpdev-locations'),
	__('Takashima-shi', 'wpdev-locations'),
	__('Yasu-shi', 'wpdev-locations'),
	__('Youkaichi', 'wpdev-locations'),
	__('Ōmihachiman', 'wpdev-locations'),
	__('Ōmihachiman-shi', 'wpdev-locations'),
	__('Ōtsu-shi', 'wpdev-locations'),
);
