<?php // phpcs:ignore - @generation-checksum JP-27-57
/**
 * State City List for 27 - JP.
 *
 * City count: 57
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 27 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Daitō Shi', 'wpdev-locations'),
	__('Daitōchō', 'wpdev-locations'),
	__('Fujiidera-shi', 'wpdev-locations'),
	__('Habikino-shi', 'wpdev-locations'),
	__('Hannan', 'wpdev-locations'),
	__('Hannan Shi', 'wpdev-locations'),
	__('Higashiōsaka Shi', 'wpdev-locations'),
	__('Hirakata', 'wpdev-locations'),
	__('Hirakata Shi', 'wpdev-locations'),
	__('Ibaraki', 'wpdev-locations'),
	__('Ibaraki Shi', 'wpdev-locations'),
	__('Ikeda', 'wpdev-locations'),
	__('Ikeda Shi', 'wpdev-locations'),
	__('Izumi', 'wpdev-locations'),
	__('Izumi Shi', 'wpdev-locations'),
	__('Izumisano', 'wpdev-locations'),
	__('Izumisano Shi', 'wpdev-locations'),
	__('Izumiōtsu', 'wpdev-locations'),
	__('Izumiōtsu Shi', 'wpdev-locations'),
	__('Kadoma', 'wpdev-locations'),
	__('Kadoma Shi', 'wpdev-locations'),
	__('Kaizuka', 'wpdev-locations'),
	__('Kaizuka Shi', 'wpdev-locations'),
	__('Kashihara', 'wpdev-locations'),
	__('Kashiwara-shi', 'wpdev-locations'),
	__('Katano Shi', 'wpdev-locations'),
	__('Kawachi-nagano Shi', 'wpdev-locations'),
	__('Kishiwada', 'wpdev-locations'),
	__('Kishiwada Shi', 'wpdev-locations'),
	__('Matsubara', 'wpdev-locations'),
	__('Matsubara-shi', 'wpdev-locations'),
	__('Mino', 'wpdev-locations'),
	__('Minoo Shi', 'wpdev-locations'),
	__('Mishima-gun', 'wpdev-locations'),
	__('Moriguchi', 'wpdev-locations'),
	__('Neyagawa', 'wpdev-locations'),
	__('Neyagawa Shi', 'wpdev-locations'),
	__('Osaka', 'wpdev-locations'),
	__('Sakai', 'wpdev-locations'),
	__('Sakai Shi', 'wpdev-locations'),
	__('Sennan Shi', 'wpdev-locations'),
	__('Settsu Shi', 'wpdev-locations'),
	__('Shijonawate Shi', 'wpdev-locations'),
	__('Suita', 'wpdev-locations'),
	__('Suita Shi', 'wpdev-locations'),
	__('Tajiri', 'wpdev-locations'),
	__('Takaishi', 'wpdev-locations'),
	__('Takaishi Shi', 'wpdev-locations'),
	__('Takatsuki', 'wpdev-locations'),
	__('Takatsuki Shi', 'wpdev-locations'),
	__('Tondabayashi Shi', 'wpdev-locations'),
	__('Tondabayashichō', 'wpdev-locations'),
	__('Toyonaka', 'wpdev-locations'),
	__('Toyonaka Shi', 'wpdev-locations'),
	__('Yao', 'wpdev-locations'),
	__('Yao-shi', 'wpdev-locations'),
	__('Ōsaka-sayama Shi', 'wpdev-locations'),
);
