<?php // phpcs:ignore - @generation-checksum JP-28-53
/**
 * State City List for 28 - JP.
 *
 * City count: 53
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 28 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aioi', 'wpdev-locations'),
	__('Aioi Shi', 'wpdev-locations'),
	__('Akashi', 'wpdev-locations'),
	__('Akashi Shi', 'wpdev-locations'),
	__('Amagasaki Shi', 'wpdev-locations'),
	__('Asago-shi', 'wpdev-locations'),
	__('Ashiya', 'wpdev-locations'),
	__('Ashiya Shi', 'wpdev-locations'),
	__('Awaji Shi', 'wpdev-locations'),
	__('Fukura', 'wpdev-locations'),
	__('Himeji', 'wpdev-locations'),
	__('Himeji Shi', 'wpdev-locations'),
	__('Itami', 'wpdev-locations'),
	__('Itami Shi', 'wpdev-locations'),
	__('Kakogawa Shi', 'wpdev-locations'),
	__('Kakogawachō-honmachi', 'wpdev-locations'),
	__('Kariya', 'wpdev-locations'),
	__('Kasai Shi', 'wpdev-locations'),
	__('Katō Shi', 'wpdev-locations'),
	__('Kawanishi', 'wpdev-locations'),
	__('Kawanishi Shi', 'wpdev-locations'),
	__('Kobe', 'wpdev-locations'),
	__('Miki', 'wpdev-locations'),
	__('Miki Shi', 'wpdev-locations'),
	__('Minamiawaji Shi', 'wpdev-locations'),
	__('Nishinomiya Shi', 'wpdev-locations'),
	__('Nishinomiya-hama', 'wpdev-locations'),
	__('Nishiwaki', 'wpdev-locations'),
	__('Nishiwaki-shi', 'wpdev-locations'),
	__('Ono', 'wpdev-locations'),
	__('Ono Shi', 'wpdev-locations'),
	__('Sanda Shi', 'wpdev-locations'),
	__('Sandachō', 'wpdev-locations'),
	__('Sasayama', 'wpdev-locations'),
	__('Sasayama-shi', 'wpdev-locations'),
	__('Shirahamachō-usazakiminami', 'wpdev-locations'),
	__('Shisō-shi', 'wpdev-locations'),
	__('Sumoto', 'wpdev-locations'),
	__('Sumoto Shi', 'wpdev-locations'),
	__('Taka-gun', 'wpdev-locations'),
	__('Takarazuka', 'wpdev-locations'),
	__('Takarazuka Shi', 'wpdev-locations'),
	__('Takasago Shi', 'wpdev-locations'),
	__('Tanba-shi', 'wpdev-locations'),
	__('Tatsuno-shi', 'wpdev-locations'),
	__('Tatsunochō-tominaga', 'wpdev-locations'),
	__('Toyooka', 'wpdev-locations'),
	__('Toyooka-shi', 'wpdev-locations'),
	__('Yabu', 'wpdev-locations'),
	__('Yabu-shi', 'wpdev-locations'),
	__('Yamazakichō-nakabirose', 'wpdev-locations'),
	__('Yashiro', 'wpdev-locations'),
	__('Yonedacho Sendo', 'wpdev-locations'),
);
