<?php // phpcs:ignore - @generation-checksum JP-29-21
/**
 * State City List for 29 - JP.
 *
 * City count: 21
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 29 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Gojō', 'wpdev-locations'),
	__('Gojō-shi', 'wpdev-locations'),
	__('Gose', 'wpdev-locations'),
	__('Haibara-akanedai', 'wpdev-locations'),
	__('Hōryūji', 'wpdev-locations'),
	__('Ikoma', 'wpdev-locations'),
	__('Ikoma-shi', 'wpdev-locations'),
	__('Kashiba-shi', 'wpdev-locations'),
	__('Kashihara-shi', 'wpdev-locations'),
	__('Katsuragi', 'wpdev-locations'),
	__('Katsuragi Shi', 'wpdev-locations'),
	__('Nara-shi', 'wpdev-locations'),
	__('Sakurai', 'wpdev-locations'),
	__('Sakurai-shi', 'wpdev-locations'),
	__('Tawaramoto', 'wpdev-locations'),
	__('Tenri', 'wpdev-locations'),
	__('Tenri-shi', 'wpdev-locations'),
	__('Uda Shi', 'wpdev-locations'),
	__('Yamatokōriyama-shi', 'wpdev-locations'),
	__('Yamatotakada-shi', 'wpdev-locations'),
	__('Yoshino-chō', 'wpdev-locations'),
);
