<?php // phpcs:ignore - @generation-checksum JP-30-16
/**
 * State City List for 30 - JP.
 *
 * City count: 16
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 30 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Arida Shi', 'wpdev-locations'),
	__('Gobō', 'wpdev-locations'),
	__('Hashimoto', 'wpdev-locations'),
	__('Hashimoto Shi', 'wpdev-locations'),
	__('Iwade', 'wpdev-locations'),
	__('Iwade Shi', 'wpdev-locations'),
	__('Kainan', 'wpdev-locations'),
	__('Kainan Shi', 'wpdev-locations'),
	__('Kinokawa Shi', 'wpdev-locations'),
	__('Kōya', 'wpdev-locations'),
	__('Minato', 'wpdev-locations'),
	__('Shingū', 'wpdev-locations'),
	__('Shingū-shi', 'wpdev-locations'),
	__('Tanabe-shi', 'wpdev-locations'),
	__('Wakayama', 'wpdev-locations'),
	__('Wakayama Shi', 'wpdev-locations'),
);
