<?php // phpcs:ignore - @generation-checksum JP-33-25
/**
 * State City List for 33 - JP.
 *
 * City count: 25
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 33 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akaiwa Shi', 'wpdev-locations'),
	__('Asakuchi Shi', 'wpdev-locations'),
	__('Bizen Shi', 'wpdev-locations'),
	__('Ibara', 'wpdev-locations'),
	__('Ibara Shi', 'wpdev-locations'),
	__('Kamogatachō-kamogata', 'wpdev-locations'),
	__('Kasaoka', 'wpdev-locations'),
	__('Kasaoka Shi', 'wpdev-locations'),
	__('Kurashiki', 'wpdev-locations'),
	__('Kurashiki Shi', 'wpdev-locations'),
	__('Maniwa-shi', 'wpdev-locations'),
	__('Mimasaka-shi', 'wpdev-locations'),
	__('Niimi', 'wpdev-locations'),
	__('Niimi Shi', 'wpdev-locations'),
	__('Okayama', 'wpdev-locations'),
	__('Okayama Shi', 'wpdev-locations'),
	__('Setouchi Shi', 'wpdev-locations'),
	__('Sōja', 'wpdev-locations'),
	__('Sōja Shi', 'wpdev-locations'),
	__('Takahashi', 'wpdev-locations'),
	__('Takahashi Shi', 'wpdev-locations'),
	__('Tamano', 'wpdev-locations'),
	__('Tamano Shi', 'wpdev-locations'),
	__('Tsuyama', 'wpdev-locations'),
	__('Tsuyama-shi', 'wpdev-locations'),
);
