<?php // phpcs:ignore - @generation-checksum JP-34-30
/**
 * State City List for 34 - JP.
 *
 * City count: 30
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 34 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aki-takata Shi', 'wpdev-locations'),
	__('Etajima-shi', 'wpdev-locations'),
	__('Fuchū-shi', 'wpdev-locations'),
	__('Fuchūchō', 'wpdev-locations'),
	__('Fukuyama', 'wpdev-locations'),
	__('Fukuyama Shi', 'wpdev-locations'),
	__('Hatsukaichi', 'wpdev-locations'),
	__('Hatsukaichi-shi', 'wpdev-locations'),
	__('Higashihiroshima Shi', 'wpdev-locations'),
	__('Hiroshima', 'wpdev-locations'),
	__('Hiroshima-shi', 'wpdev-locations'),
	__('Innoshima', 'wpdev-locations'),
	__('Kannabechō-yahiro', 'wpdev-locations'),
	__('Kure', 'wpdev-locations'),
	__('Kure-shi', 'wpdev-locations'),
	__('Mihara', 'wpdev-locations'),
	__('Mihara Shi', 'wpdev-locations'),
	__('Miyajima', 'wpdev-locations'),
	__('Miyoshi', 'wpdev-locations'),
	__('Miyoshi Shi', 'wpdev-locations'),
	__('Onomichi', 'wpdev-locations'),
	__('Onomichi-shi', 'wpdev-locations'),
	__('Shin’ichi', 'wpdev-locations'),
	__('Shōbara', 'wpdev-locations'),
	__('Shōbara-shi', 'wpdev-locations'),
	__('Takehara', 'wpdev-locations'),
	__('Takehara-shi', 'wpdev-locations'),
	__('Ōno-hara', 'wpdev-locations'),
	__('Ōtake', 'wpdev-locations'),
	__('Ōtake-shi', 'wpdev-locations'),
);
