<?php // phpcs:ignore - @generation-checksum JP-36-17
/**
 * State City List for 36 - JP.
 *
 * City count: 17
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 36 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Anan Shi', 'wpdev-locations'),
	__('Awa-shi', 'wpdev-locations'),
	__('Ikedachō', 'wpdev-locations'),
	__('Ishii', 'wpdev-locations'),
	__('Kamojimachō-jōgejima', 'wpdev-locations'),
	__('Katsuura Gun', 'wpdev-locations'),
	__('Komatsushima Shi', 'wpdev-locations'),
	__('Komatsushimachō', 'wpdev-locations'),
	__('Mima Shi', 'wpdev-locations'),
	__('Miyoshi Shi', 'wpdev-locations'),
	__('Miyoshi-gun', 'wpdev-locations'),
	__('Naruto-shi', 'wpdev-locations'),
	__('Narutochō-mitsuishi', 'wpdev-locations'),
	__('Tokushima', 'wpdev-locations'),
	__('Tokushima Shi', 'wpdev-locations'),
	__('Wakimachi', 'wpdev-locations'),
	__('Yoshinogawa Shi', 'wpdev-locations'),
);
