<?php // phpcs:ignore - @generation-checksum JP-40-56
/**
 * State City List for 40 - JP.
 *
 * City count: 56
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 40 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Amagi', 'wpdev-locations'),
	__('Asakura Shi', 'wpdev-locations'),
	__('Buzen', 'wpdev-locations'),
	__('Buzen-shi', 'wpdev-locations'),
	__('Chikugo Shi', 'wpdev-locations'),
	__('Chikushino-shi', 'wpdev-locations'),
	__('Dazaifu-shi', 'wpdev-locations'),
	__('Fukuoka', 'wpdev-locations'),
	__('Fukuoka-shi', 'wpdev-locations'),
	__('Fukutsu Shi', 'wpdev-locations'),
	__('Iizuka', 'wpdev-locations'),
	__('Iizuka Shi', 'wpdev-locations'),
	__('Itoshima-shi', 'wpdev-locations'),
	__('Kama Shi', 'wpdev-locations'),
	__('Kanda', 'wpdev-locations'),
	__('Kasuga Shi', 'wpdev-locations'),
	__('Kawasaki', 'wpdev-locations'),
	__('Kitakyushu', 'wpdev-locations'),
	__('Koga', 'wpdev-locations'),
	__('Koga-shi', 'wpdev-locations'),
	__('Kurume', 'wpdev-locations'),
	__('Kurume Shi', 'wpdev-locations'),
	__('Maebaru-chūō', 'wpdev-locations'),
	__('Miyama Shi', 'wpdev-locations'),
	__('Miyata', 'wpdev-locations'),
	__('Miyawaka Shi', 'wpdev-locations'),
	__('Munakata-shi', 'wpdev-locations'),
	__('Nakama', 'wpdev-locations'),
	__('Nakama Shi', 'wpdev-locations'),
	__('Nishifukuma', 'wpdev-locations'),
	__('Nōgata', 'wpdev-locations'),
	__('Nōgata Shi', 'wpdev-locations'),
	__('Ogōri-shi', 'wpdev-locations'),
	__('Onga-gun', 'wpdev-locations'),
	__('Sasaguri', 'wpdev-locations'),
	__('Setakamachi-takayanagi', 'wpdev-locations'),
	__('Shiida', 'wpdev-locations'),
	__('Shingū', 'wpdev-locations'),
	__('Tagawa', 'wpdev-locations'),
	__('Tagawa Shi', 'wpdev-locations'),
	__('Tanushimarumachi-toyoki', 'wpdev-locations'),
	__('Tsuiki', 'wpdev-locations'),
	__('Ukiha Shi', 'wpdev-locations'),
	__('Umi', 'wpdev-locations'),
	__('Yame Shi', 'wpdev-locations'),
	__('Yanagawa', 'wpdev-locations'),
	__('Yanagawa Shi', 'wpdev-locations'),
	__('Yoshitomi', 'wpdev-locations'),
	__('Yukuhashi', 'wpdev-locations'),
	__('Yukuhashi Shi', 'wpdev-locations'),
	__('Ōkawa', 'wpdev-locations'),
	__('Ōkawa-shi', 'wpdev-locations'),
	__('Ōmuta', 'wpdev-locations'),
	__('Ōmuta Shi', 'wpdev-locations'),
	__('Ōnojō', 'wpdev-locations'),
	__('Ōnojō Shi', 'wpdev-locations'),
);
