<?php // phpcs:ignore - @generation-checksum JP-42-22
/**
 * State City List for 42 - JP.
 *
 * City count: 22
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 42 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Fukuechō', 'wpdev-locations'),
	__('Gotō Shi', 'wpdev-locations'),
	__('Hirado', 'wpdev-locations'),
	__('Hirado Shi', 'wpdev-locations'),
	__('Iki Shi', 'wpdev-locations'),
	__('Isahaya', 'wpdev-locations'),
	__('Isahaya-shi', 'wpdev-locations'),
	__('Matsuura', 'wpdev-locations'),
	__('Matsuura Shi', 'wpdev-locations'),
	__('Minamishimabara-shi', 'wpdev-locations'),
	__('Nagasaki', 'wpdev-locations'),
	__('Nagasaki-shi', 'wpdev-locations'),
	__('Obita', 'wpdev-locations'),
	__('Saikai-shi', 'wpdev-locations'),
	__('Sasebo Shi', 'wpdev-locations'),
	__('Shimabara', 'wpdev-locations'),
	__('Shimabara-shi', 'wpdev-locations'),
	__('Togitsu', 'wpdev-locations'),
	__('Tsushima Shi', 'wpdev-locations'),
	__('Unzen-shi', 'wpdev-locations'),
	__('Ōmura', 'wpdev-locations'),
	__('Ōmura-shi', 'wpdev-locations'),
);
