<?php

// autoload_classmap.php @generated by WPDev dependency migration

$vendorDir = dirname( __DIR__ );
$baseDir   = dirname( $vendorDir );

return array(
	'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
