<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitwpdevDependencies
{
    public static $files = array (
    );

    public static $prefixLengthsPsr4 = array (
    );

    public static $prefixDirsPsr4 = array (
    );

    public static $classMap = array (
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitwpdevDependencies::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitwpdevDependencies::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitwpdevDependencies::$classMap;

        }, null, ClassLoader::class);
    }
}
