<?php

// autoload_psr4.php @generated by WPDev dependency migration

$vendorDir = dirname( __DIR__ );
$baseDir   = dirname( $vendorDir );

return array(
	'WPDev\\Contracts\\' => array(
		$baseDir . '/modules/core/src/contracts',
	),
);
