<?php // phpcs:ignore - @generation-checksum NL-DR-76
/**
 * State City List for DR - NL.
 *
 * City count: 76
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for DR - NL.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aalden', 'wpdev-locations'),
	__('Angelslo', 'wpdev-locations'),
	__('Annen', 'wpdev-locations'),
	__('Assen', 'wpdev-locations'),
	__('Ballast', 'wpdev-locations'),
	__('Barger-Oosterveld', 'wpdev-locations'),
	__('Bargeres', 'wpdev-locations'),
	__('Beilen', 'wpdev-locations'),
	__('Borger', 'wpdev-locations'),
	__('Coevorden', 'wpdev-locations'),
	__('Dalen', 'wpdev-locations'),
	__('De Loo', 'wpdev-locations'),
	__('De Wijk', 'wpdev-locations'),
	__('Diever', 'wpdev-locations'),
	__('Dwingeloo', 'wpdev-locations'),
	__('Eelde', 'wpdev-locations'),
	__('Eext', 'wpdev-locations'),
	__('Emmen', 'wpdev-locations'),
	__('Emmer-Compascuum', 'wpdev-locations'),
	__('Emmer-Erfscheidenveen', 'wpdev-locations'),
	__('Emmerhout', 'wpdev-locations'),
	__('Emmermeer', 'wpdev-locations'),
	__('Emmerschans', 'wpdev-locations'),
	__('Exloo', 'wpdev-locations'),
	__('Gasselte', 'wpdev-locations'),
	__('Gasselternijveen', 'wpdev-locations'),
	__('Gemeente Aa en Hunze', 'wpdev-locations'),
	__('Gemeente Assen', 'wpdev-locations'),
	__('Gemeente Borger-Odoorn', 'wpdev-locations'),
	__('Gemeente Coevorden', 'wpdev-locations'),
	__('Gemeente De Wolden', 'wpdev-locations'),
	__('Gemeente Emmen', 'wpdev-locations'),
	__('Gemeente Hoogeveen', 'wpdev-locations'),
	__('Gemeente Meppel', 'wpdev-locations'),
	__('Gemeente Midden-Drenthe', 'wpdev-locations'),
	__('Gemeente Noordenveld', 'wpdev-locations'),
	__('Gemeente Tynaarlo', 'wpdev-locations'),
	__('Gemeente Westerveld', 'wpdev-locations'),
	__('Gieten', 'wpdev-locations'),
	__('Havelte', 'wpdev-locations'),
	__('Hoogeveen', 'wpdev-locations'),
	__('Klazienaveen', 'wpdev-locations'),
	__('Koekange', 'wpdev-locations'),
	__('Krakeel', 'wpdev-locations'),
	__('Marsdijk', 'wpdev-locations'),
	__('Meppel', 'wpdev-locations'),
	__('Nieuw-Buinen', 'wpdev-locations'),
	__('Nieuw-Dordrecht', 'wpdev-locations'),
	__('Nieuw-Roden', 'wpdev-locations'),
	__('Noordbarge', 'wpdev-locations'),
	__('Norg', 'wpdev-locations'),
	__('Odoorn', 'wpdev-locations'),
	__('Oosterhesselen', 'wpdev-locations'),
	__('Paterswolde', 'wpdev-locations'),
	__('Peelo', 'wpdev-locations'),
	__('Peize', 'wpdev-locations'),
	__('Roden', 'wpdev-locations'),
	__('Rolde', 'wpdev-locations'),
	__('Ruinen', 'wpdev-locations'),
	__('Ruinerwold', 'wpdev-locations'),
	__('Schoonebeek', 'wpdev-locations'),
	__('Schoonoord', 'wpdev-locations'),
	__('Sleen', 'wpdev-locations'),
	__('Tweede Exloërmond', 'wpdev-locations'),
	__('Tynaarlo', 'wpdev-locations'),
	__('Uffelte', 'wpdev-locations'),
	__('Valthe', 'wpdev-locations'),
	__('Valthermond', 'wpdev-locations'),
	__('Veenoord', 'wpdev-locations'),
	__('Vledder', 'wpdev-locations'),
	__('Vries', 'wpdev-locations'),
	__('Weiteveen', 'wpdev-locations'),
	__('Westerbork', 'wpdev-locations'),
	__('Westlaren', 'wpdev-locations'),
	__('Wolfsbos', 'wpdev-locations'),
	__('Zuidlaren', 'wpdev-locations'),
);
