<?php // phpcs:ignore - @generation-checksum NL-FL-14
/**
 * State City List for FL - NL.
 *
 * City count: 14
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for FL - NL.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Almere Stad', 'wpdev-locations'),
	__('Biddinghuizen', 'wpdev-locations'),
	__('Dronten', 'wpdev-locations'),
	__('Emmeloord', 'wpdev-locations'),
	__('Ens', 'wpdev-locations'),
	__('Gemeente Almere', 'wpdev-locations'),
	__('Gemeente Dronten', 'wpdev-locations'),
	__('Gemeente Lelystad', 'wpdev-locations'),
	__('Gemeente Noordoostpolder', 'wpdev-locations'),
	__('Gemeente Urk', 'wpdev-locations'),
	__('Gemeente Zeewolde', 'wpdev-locations'),
	__('Lelystad', 'wpdev-locations'),
	__('Urk', 'wpdev-locations'),
	__('Zeewolde', 'wpdev-locations'),
);
