<?php // phpcs:ignore - @generation-checksum NL-GR-79
/**
 * State City List for GR - NL.
 *
 * City count: 79
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for GR - NL.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aduard', 'wpdev-locations'),
	__('Appingedam', 'wpdev-locations'),
	__('Baflo', 'wpdev-locations'),
	__('Bedum', 'wpdev-locations'),
	__('Bellingwolde', 'wpdev-locations'),
	__('Blijham', 'wpdev-locations'),
	__('Coendersborg', 'wpdev-locations'),
	__('De Wijert', 'wpdev-locations'),
	__('Delfzijl', 'wpdev-locations'),
	__('Eenrum', 'wpdev-locations'),
	__('Eexta', 'wpdev-locations'),
	__('Farmsum', 'wpdev-locations'),
	__('Gemeente  Oldambt', 'wpdev-locations'),
	__('Gemeente Appingedam', 'wpdev-locations'),
	__('Gemeente Delfzijl', 'wpdev-locations'),
	__('Gemeente Groningen', 'wpdev-locations'),
	__('Gemeente Loppersum', 'wpdev-locations'),
	__('Gemeente Pekela', 'wpdev-locations'),
	__('Gemeente Stadskanaal', 'wpdev-locations'),
	__('Gemeente Veendam', 'wpdev-locations'),
	__('Glimmen', 'wpdev-locations'),
	__('Grijpskerk', 'wpdev-locations'),
	__('Groningen', 'wpdev-locations'),
	__('Grootegast', 'wpdev-locations'),
	__('Haren', 'wpdev-locations'),
	__('Harkstede', 'wpdev-locations'),
	__('Heiligerlee', 'wpdev-locations'),
	__('Helpman', 'wpdev-locations'),
	__('Hoogezand', 'wpdev-locations'),
	__('Korrewegwijk', 'wpdev-locations'),
	__('Leek', 'wpdev-locations'),
	__('Leens', 'wpdev-locations'),
	__('Loppersum', 'wpdev-locations'),
	__('Marum', 'wpdev-locations'),
	__('Meeden', 'wpdev-locations'),
	__('Middelstum', 'wpdev-locations'),
	__('Midden-Groningen', 'wpdev-locations'),
	__('Midwolda', 'wpdev-locations'),
	__('Niekerk', 'wpdev-locations'),
	__('Nieuwe Pekela', 'wpdev-locations'),
	__('Nieuwolda', 'wpdev-locations'),
	__('Noordbroek', 'wpdev-locations'),
	__('Noordhorn', 'wpdev-locations'),
	__('Obergum', 'wpdev-locations'),
	__('Oldehove', 'wpdev-locations'),
	__('Ommelanderwijk', 'wpdev-locations'),
	__('Onstwedde', 'wpdev-locations'),
	__('Oosterhoogebrug', 'wpdev-locations'),
	__('Oosterpark', 'wpdev-locations'),
	__('Oude Pekela', 'wpdev-locations'),
	__('Reitdiep', 'wpdev-locations'),
	__('Sappemeer', 'wpdev-locations'),
	__('Scheemda', 'wpdev-locations'),
	__('Schildwolde', 'wpdev-locations'),
	__('Sellingen', 'wpdev-locations'),
	__('Selwerd', 'wpdev-locations'),
	__('Siddeburen', 'wpdev-locations'),
	__('Slochteren', 'wpdev-locations'),
	__('Spijk', 'wpdev-locations'),
	__('Stadskanaal', 'wpdev-locations'),
	__('Ten Boer', 'wpdev-locations'),
	__('Ter Apel', 'wpdev-locations'),
	__('Tuikwerd', 'wpdev-locations'),
	__('Uithuizen', 'wpdev-locations'),
	__('Uithuizermeeden', 'wpdev-locations'),
	__('Ulrum', 'wpdev-locations'),
	__('Usquert', 'wpdev-locations'),
	__('Veendam', 'wpdev-locations'),
	__('Vlagtwedde', 'wpdev-locations'),
	__('Wagenborgen', 'wpdev-locations'),
	__('Warffum', 'wpdev-locations'),
	__('Westerlee', 'wpdev-locations'),
	__('Westerwolde', 'wpdev-locations'),
	__('Wildervank', 'wpdev-locations'),
	__('Winschoten', 'wpdev-locations'),
	__('Winsum', 'wpdev-locations'),
	__('Zoutkamp', 'wpdev-locations'),
	__('Zuidbroek', 'wpdev-locations'),
	__('Zuidhorn', 'wpdev-locations'),
);
