<?php // phpcs:ignore - @generation-checksum NL-OV-90
/**
 * State City List for OV - NL.
 *
 * City count: 90
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for OV - NL.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Almelo', 'wpdev-locations'),
	__('Baalder', 'wpdev-locations'),
	__('Berkum', 'wpdev-locations'),
	__('Blokzijl', 'wpdev-locations'),
	__('Borgele', 'wpdev-locations'),
	__('Borne', 'wpdev-locations'),
	__('Boskamp', 'wpdev-locations'),
	__('Brunnepe', 'wpdev-locations'),
	__('Dalfsen', 'wpdev-locations'),
	__('De Hoven', 'wpdev-locations'),
	__('Delden', 'wpdev-locations'),
	__('Den Ham', 'wpdev-locations'),
	__('Deventer', 'wpdev-locations'),
	__('Diepenheim', 'wpdev-locations'),
	__('Enschede', 'wpdev-locations'),
	__('Flevowijk', 'wpdev-locations'),
	__('Frankhuis', 'wpdev-locations'),
	__('Gemeente Almelo', 'wpdev-locations'),
	__('Gemeente Borne', 'wpdev-locations'),
	__('Gemeente Dalfsen', 'wpdev-locations'),
	__('Gemeente Deventer', 'wpdev-locations'),
	__('Gemeente Dinkelland', 'wpdev-locations'),
	__('Gemeente Enschede', 'wpdev-locations'),
	__('Gemeente Haaksbergen', 'wpdev-locations'),
	__('Gemeente Hardenberg', 'wpdev-locations'),
	__('Gemeente Hellendoorn', 'wpdev-locations'),
	__('Gemeente Hengelo', 'wpdev-locations'),
	__('Gemeente Hof van Twente', 'wpdev-locations'),
	__('Gemeente Kampen', 'wpdev-locations'),
	__('Gemeente Losser', 'wpdev-locations'),
	__('Gemeente Oldenzaal', 'wpdev-locations'),
	__('Gemeente Olst-Wijhe', 'wpdev-locations'),
	__('Gemeente Ommen', 'wpdev-locations'),
	__('Gemeente Raalte', 'wpdev-locations'),
	__('Gemeente Rijssen-Holten', 'wpdev-locations'),
	__('Gemeente Staphorst', 'wpdev-locations'),
	__('Gemeente Steenwijkerland', 'wpdev-locations'),
	__('Gemeente Tubbergen', 'wpdev-locations'),
	__('Gemeente Twenterand', 'wpdev-locations'),
	__('Gemeente Wierden', 'wpdev-locations'),
	__('Gemeente Zwartewaterland', 'wpdev-locations'),
	__('Gemeente Zwolle', 'wpdev-locations'),
	__('Giethoorn', 'wpdev-locations'),
	__('Goor', 'wpdev-locations'),
	__('Grafhorst', 'wpdev-locations'),
	__('Haaksbergen', 'wpdev-locations'),
	__('Haarle', 'wpdev-locations'),
	__('Hardenberg', 'wpdev-locations'),
	__('Hasselt', 'wpdev-locations'),
	__('Heino', 'wpdev-locations'),
	__('Hengelo', 'wpdev-locations'),
	__('Hengevelde', 'wpdev-locations'),
	__('Het Oostrik', 'wpdev-locations'),
	__('Kampen', 'wpdev-locations'),
	__('Klein Driene', 'wpdev-locations'),
	__('Losser', 'wpdev-locations'),
	__('Magele', 'wpdev-locations'),
	__('Markelo', 'wpdev-locations'),
	__('Mekkelholt', 'wpdev-locations'),
	__('Nieuwoord', 'wpdev-locations'),
	__('Nijrees', 'wpdev-locations'),
	__('Oldemarkt', 'wpdev-locations'),
	__('Oldenzaal', 'wpdev-locations'),
	__('Olst', 'wpdev-locations'),
	__('Ommen', 'wpdev-locations'),
	__('Oosterholt', 'wpdev-locations'),
	__('Oostermeenthe', 'wpdev-locations'),
	__('Ootmarsum', 'wpdev-locations'),
	__('Pathmos', 'wpdev-locations'),
	__('Pierik', 'wpdev-locations'),
	__('Raalte', 'wpdev-locations'),
	__('Rossum', 'wpdev-locations'),
	__('Schalkhaar', 'wpdev-locations'),
	__('Sint Jansklooster', 'wpdev-locations'),
	__('Staphorst', 'wpdev-locations'),
	__('Steenwijk', 'wpdev-locations'),
	__('Steenwijkerwold', 'wpdev-locations'),
	__('Tubbergen', 'wpdev-locations'),
	__('Tuk', 'wpdev-locations'),
	__('Twekkelerveld', 'wpdev-locations'),
	__('Vollenhove', 'wpdev-locations'),
	__('Vriezenveen', 'wpdev-locations'),
	__('Vroomshoop', 'wpdev-locations'),
	__('Westerhaar-Vriezenveensewijk', 'wpdev-locations'),
	__('Wierden', 'wpdev-locations'),
	__('Wijhe', 'wpdev-locations'),
	__('Woolde', 'wpdev-locations'),
	__('Wooldrik', 'wpdev-locations'),
	__('Zuid-Berghuizen', 'wpdev-locations'),
	__('Zwolle', 'wpdev-locations'),
);
