<?php // phpcs:ignore - @generation-checksum US-66-19821
/**
 * Country Class for United States (US).
 *
 * State/province count: 66
 * City count: 19821
 * City count per state/province:
 * - TX: 1277 cities
 * - CA: 1123 cities
 * - PA: 1054 cities
 * - NY: 1054 cities
 * - IL: 855 cities
 * - FL: 845 cities
 * - OH: 756 cities
 * - NC: 554 cities
 * - NJ: 551 cities
 * - GA: 534 cities
 * - MI: 526 cities
 * - MO: 510 cities
 * - VA: 503 cities
 * - WI: 492 cities
 * - MN: 460 cities
 * - IN: 434 cities
 * - WA: 433 cities
 * - MA: 405 cities
 * - KY: 388 cities
 * - TN: 386 cities
 * - IA: 383 cities
 * - AL: 378 cities
 * - MD: 364 cities
 * - LA: 344 cities
 * - OK: 320 cities
 * - KS: 319 cities
 * - MS: 295 cities
 * - CO: 289 cities
 * - AR: 287 cities
 * - SC: 283 cities
 * - ME: 271 cities
 * - PR: 255 cities
 * - OR: 255 cities
 * - NE: 238 cities
 * - AZ: 227 cities
 * - WV: 217 cities
 * - UT: 207 cities
 * - CT: 191 cities
 * - NH: 186 cities
 * - NM: 182 cities
 * - SD: 167 cities
 * - MT: 161 cities
 * - ID: 142 cities
 * - ND: 133 cities
 * - HI: 121 cities
 * - VT: 96 cities
 * - AK: 95 cities
 * - NV: 82 cities
 * - WY: 80 cities
 * - RI: 54 cities
 * - DE: 54 cities
 * - DC: 5 cities
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

namespace WPDevFramework\Country;

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * Country Class for United States (US).
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 *
 * @property-read string $code
 * @property-read string $currency
 * @property-read int $phone_code
 */
class Country_US extends Country {

	use \WPDevFramework\Traits\Singleton;

	/**
	 * General country attributes.
	 *
	 * This might be useful, might be not.
	 * In case of doubt, keep it.
	 *
	 * @since 2.0.11
	 * @var array
	 */
	protected $attributes = array(
		'country_code' => 'US',
		'currency'     => 'USD',
		'phone_code'   => 1,
	);

	/**
	 * The type of nomenclature used to refer to the country sub-divisions.
	 *
	 * @since 2.0.11
	 * @var string
	 */
	protected $state_type = 'state';

	/**
	 * Return the country name.
	 *
	 * @since 2.0.11
	 * @return string
	 */
	public function get_name() {

		return __('United States', 'wpdev-locations');

	} // end get_name;

	/**
	 * Returns the list of states for US.
	 *
	 * @since 2.0.11
	 * @return array The list of state/provinces for the country.
	 */
	protected function states() {

		return array(
			'AL'    => __('Alabama', 'wpdev-locations'),
			'AK'    => __('Alaska', 'wpdev-locations'),
			'AS'    => __('American Samoa', 'wpdev-locations'),
			'AZ'    => __('Arizona', 'wpdev-locations'),
			'AR'    => __('Arkansas', 'wpdev-locations'),
			'UM-81' => __('Baker Island', 'wpdev-locations'),
			'CA'    => __('California', 'wpdev-locations'),
			'CO'    => __('Colorado', 'wpdev-locations'),
			'CT'    => __('Connecticut', 'wpdev-locations'),
			'DE'    => __('Delaware', 'wpdev-locations'),
			'DC'    => __('District of Columbia', 'wpdev-locations'),
			'FL'    => __('Florida', 'wpdev-locations'),
			'GA'    => __('Georgia', 'wpdev-locations'),
			'GU'    => __('Guam', 'wpdev-locations'),
			'HI'    => __('Hawaii', 'wpdev-locations'),
			'UM-84' => __('Howland Island', 'wpdev-locations'),
			'ID'    => __('Idaho', 'wpdev-locations'),
			'IL'    => __('Illinois', 'wpdev-locations'),
			'IN'    => __('Indiana', 'wpdev-locations'),
			'IA'    => __('Iowa', 'wpdev-locations'),
			'UM-86' => __('Jarvis Island', 'wpdev-locations'),
			'UM-67' => __('Johnston Atoll', 'wpdev-locations'),
			'KS'    => __('Kansas', 'wpdev-locations'),
			'KY'    => __('Kentucky', 'wpdev-locations'),
			'UM-89' => __('Kingman Reef', 'wpdev-locations'),
			'LA'    => __('Louisiana', 'wpdev-locations'),
			'ME'    => __('Maine', 'wpdev-locations'),
			'MD'    => __('Maryland', 'wpdev-locations'),
			'MA'    => __('Massachusetts', 'wpdev-locations'),
			'MI'    => __('Michigan', 'wpdev-locations'),
			'UM-71' => __('Midway Atoll', 'wpdev-locations'),
			'MN'    => __('Minnesota', 'wpdev-locations'),
			'MS'    => __('Mississippi', 'wpdev-locations'),
			'MO'    => __('Missouri', 'wpdev-locations'),
			'MT'    => __('Montana', 'wpdev-locations'),
			'UM-76' => __('Navassa Island', 'wpdev-locations'),
			'NE'    => __('Nebraska', 'wpdev-locations'),
			'NV'    => __('Nevada', 'wpdev-locations'),
			'NH'    => __('New Hampshire', 'wpdev-locations'),
			'NJ'    => __('New Jersey', 'wpdev-locations'),
			'NM'    => __('New Mexico', 'wpdev-locations'),
			'NY'    => __('New York', 'wpdev-locations'),
			'NC'    => __('North Carolina', 'wpdev-locations'),
			'ND'    => __('North Dakota', 'wpdev-locations'),
			'MP'    => __('Northern Mariana Islands', 'wpdev-locations'),
			'OH'    => __('Ohio', 'wpdev-locations'),
			'OK'    => __('Oklahoma', 'wpdev-locations'),
			'OR'    => __('Oregon', 'wpdev-locations'),
			'UM-95' => __('Palmyra Atoll', 'wpdev-locations'),
			'PA'    => __('Pennsylvania', 'wpdev-locations'),
			'PR'    => __('Puerto Rico', 'wpdev-locations'),
			'RI'    => __('Rhode Island', 'wpdev-locations'),
			'SC'    => __('South Carolina', 'wpdev-locations'),
			'SD'    => __('South Dakota', 'wpdev-locations'),
			'TN'    => __('Tennessee', 'wpdev-locations'),
			'TX'    => __('Texas', 'wpdev-locations'),
			'UM'    => __('United States Minor Outlying Islands', 'wpdev-locations'),
			'VI'    => __('United States Virgin Islands', 'wpdev-locations'),
			'UT'    => __('Utah', 'wpdev-locations'),
			'VT'    => __('Vermont', 'wpdev-locations'),
			'VA'    => __('Virginia', 'wpdev-locations'),
			'UM-79' => __('Wake Island', 'wpdev-locations'),
			'WA'    => __('Washington', 'wpdev-locations'),
			'WV'    => __('West Virginia', 'wpdev-locations'),
			'WI'    => __('Wisconsin', 'wpdev-locations'),
			'WY'    => __('Wyoming', 'wpdev-locations'),
		);

	} // end states;

} // end class Country_US;
