<?php // phpcs:ignore - @generation-checksum DE-16-7097
/**
 * Country Class for Germany (DE).
 *
 * State/province count: 16
 * City count: 7097
 * City count per state/province:
 * - BY: 1756 cities
 * - BW: 944 cities
 * - NI: 751 cities
 * - RP: 688 cities
 * - SN: 442 cities
 * - NW: 428 cities
 * - SH: 386 cities
 * - ST: 368 cities
 * - HE: 347 cities
 * - TH: 319 cities
 * - MV: 253 cities
 * - BB: 217 cities
 * - BE: 97 cities
 * - SL: 60 cities
 * - HH: 37 cities
 * - HB: 4 cities
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

namespace WPDevFramework\Country;

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * Country Class for Germany (DE).
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 *
 * @property-read string $code
 * @property-read string $currency
 * @property-read int $phone_code
 */
class Country_DE extends Country {

	use \WPDevFramework\Traits\Singleton;

	/**
	 * General country attributes.
	 *
	 * This might be useful, might be not.
	 * In case of doubt, keep it.
	 *
	 * @since 2.0.11
	 * @var array
	 */
	protected $attributes = array(
		'country_code' => 'DE',
		'currency'     => 'EUR',
		'phone_code'   => 49,
	);

	/**
	 * The type of nomenclature used to refer to the country sub-divisions.
	 *
	 * @since 2.0.11
	 * @var string
	 */
	protected $state_type = 'state';

	/**
	 * Return the country name.
	 *
	 * @since 2.0.11
	 * @return string
	 */
	public function get_name() {

		return __('Germany', 'wpdev-locations');

	} // end get_name;

	/**
	 * Returns the list of states for DE.
	 *
	 * @since 2.0.11
	 * @return array The list of state/provinces for the country.
	 */
	protected function states() {

		return array(
			'BW' => __('Baden-Württemberg', 'wpdev-locations'),
			'BY' => __('Bavaria', 'wpdev-locations'),
			'BE' => __('Berlin', 'wpdev-locations'),
			'BB' => __('Brandenburg', 'wpdev-locations'),
			'HB' => __('Bremen', 'wpdev-locations'),
			'HH' => __('Hamburg', 'wpdev-locations'),
			'HE' => __('Hesse', 'wpdev-locations'),
			'NI' => __('Lower Saxony', 'wpdev-locations'),
			'MV' => __('Mecklenburg-Vorpommern', 'wpdev-locations'),
			'NW' => __('North Rhine-Westphalia', 'wpdev-locations'),
			'RP' => __('Rhineland-Palatinate', 'wpdev-locations'),
			'SL' => __('Saarland', 'wpdev-locations'),
			'SN' => __('Saxony', 'wpdev-locations'),
			'ST' => __('Saxony-Anhalt', 'wpdev-locations'),
			'SH' => __('Schleswig-Holstein', 'wpdev-locations'),
			'TH' => __('Thuringia', 'wpdev-locations'),
		);

	} // end states;

} // end class Country_DE;
