<?php // phpcs:ignore - @generation-checksum IN-36-4242
/**
 * Country Class for India (IN).
 *
 * State/province count: 36
 * City count: 4242
 * City count per state/province:
 * - UP: 624 cities
 * - MH: 574 cities
 * - TN: 350 cities
 * - GJ: 311 cities
 * - MP: 275 cities
 * - WB: 260 cities
 * - KA: 242 cities
 * - RJ: 187 cities
 * - AP: 168 cities
 * - BR: 132 cities
 * - PB: 115 cities
 * - OR: 113 cities
 * - KL: 107 cities
 * - TG: 89 cities
 * - AS: 87 cities
 * - HR: 83 cities
 * - CT: 78 cities
 * - JH: 77 cities
 * - HP: 57 cities
 * - JK: 56 cities
 * - UT: 55 cities
 * - GA: 50 cities
 * - AR: 26 cities
 * - TR: 19 cities
 * - DL: 19 cities
 * - ML: 18 cities
 * - MZ: 15 cities
 * - MN: 13 cities
 * - SK: 12 cities
 * - NL: 10 cities
 * - DH: 7 cities
 * - AN: 4 cities
 * - PY: 4 cities
 * - LA: 2 cities
 * - LD: 2 cities
 * - CH: 1 cities
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

namespace WPDevFramework\Country;

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * Country Class for India (IN).
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 *
 * @property-read string $code
 * @property-read string $currency
 * @property-read int $phone_code
 */
class Country_IN extends Country {

	use \WPDevFramework\Traits\Singleton;

	/**
	 * General country attributes.
	 *
	 * This might be useful, might be not.
	 * In case of doubt, keep it.
	 *
	 * @since 2.0.11
	 * @var array
	 */
	protected $attributes = array(
		'country_code' => 'IN',
		'currency'     => 'INR',
		'phone_code'   => 91,
	);

	/**
	 * The type of nomenclature used to refer to the country sub-divisions.
	 *
	 * @since 2.0.11
	 * @var string
	 */
	protected $state_type = 'unknown';

	/**
	 * Return the country name.
	 *
	 * @since 2.0.11
	 * @return string
	 */
	public function get_name() {

		return __('India', 'wpdev-locations');

	} // end get_name;

	/**
	 * Returns the list of states for IN.
	 *
	 * @since 2.0.11
	 * @return array The list of state/provinces for the country.
	 */
	protected function states() {

		return array(
			'AN' => __('Andaman and Nicobar Islands', 'wpdev-locations'),
			'AP' => __('Andhra Pradesh', 'wpdev-locations'),
			'AR' => __('Arunachal Pradesh', 'wpdev-locations'),
			'AS' => __('Assam', 'wpdev-locations'),
			'BR' => __('Bihar', 'wpdev-locations'),
			'CH' => __('Chandigarh', 'wpdev-locations'),
			'CT' => __('Chhattisgarh', 'wpdev-locations'),
			'DH' => __('Dadra and Nagar Haveli and Daman and Diu', 'wpdev-locations'),
			'DL' => __('Delhi', 'wpdev-locations'),
			'GA' => __('Goa', 'wpdev-locations'),
			'GJ' => __('Gujarat', 'wpdev-locations'),
			'HR' => __('Haryana', 'wpdev-locations'),
			'HP' => __('Himachal Pradesh', 'wpdev-locations'),
			'JK' => __('Jammu and Kashmir', 'wpdev-locations'),
			'JH' => __('Jharkhand', 'wpdev-locations'),
			'KA' => __('Karnataka', 'wpdev-locations'),
			'KL' => __('Kerala', 'wpdev-locations'),
			'LA' => __('Ladakh', 'wpdev-locations'),
			'LD' => __('Lakshadweep', 'wpdev-locations'),
			'MP' => __('Madhya Pradesh', 'wpdev-locations'),
			'MH' => __('Maharashtra', 'wpdev-locations'),
			'MN' => __('Manipur', 'wpdev-locations'),
			'ML' => __('Meghalaya', 'wpdev-locations'),
			'MZ' => __('Mizoram', 'wpdev-locations'),
			'NL' => __('Nagaland', 'wpdev-locations'),
			'OR' => __('Odisha', 'wpdev-locations'),
			'PY' => __('Puducherry', 'wpdev-locations'),
			'PB' => __('Punjab', 'wpdev-locations'),
			'RJ' => __('Rajasthan', 'wpdev-locations'),
			'SK' => __('Sikkim', 'wpdev-locations'),
			'TN' => __('Tamil Nadu', 'wpdev-locations'),
			'TG' => __('Telangana', 'wpdev-locations'),
			'TR' => __('Tripura', 'wpdev-locations'),
			'UP' => __('Uttar Pradesh', 'wpdev-locations'),
			'UT' => __('Uttarakhand', 'wpdev-locations'),
			'WB' => __('West Bengal', 'wpdev-locations'),
		);

	} // end states;

} // end class Country_IN;
