<?php // phpcs:ignore - @generation-checksum US-AK-95
/**
 * State City List for AK - US.
 *
 * City count: 95
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AK - US.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akutan', 'wpdev-locations'),
	__('Aleutians East Borough', 'wpdev-locations'),
	__('Aleutians West Census Area', 'wpdev-locations'),
	__('Anchor Point', 'wpdev-locations'),
	__('Anchorage', 'wpdev-locations'),
	__('Anchorage Municipality', 'wpdev-locations'),
	__('Badger', 'wpdev-locations'),
	__('Barrow', 'wpdev-locations'),
	__('Bear Creek', 'wpdev-locations'),
	__('Bethel', 'wpdev-locations'),
	__('Bethel Census Area', 'wpdev-locations'),
	__('Big Lake', 'wpdev-locations'),
	__('Bristol Bay Borough', 'wpdev-locations'),
	__('Butte', 'wpdev-locations'),
	__('Chevak', 'wpdev-locations'),
	__('City and Borough of Wrangell', 'wpdev-locations'),
	__('Cohoe', 'wpdev-locations'),
	__('College', 'wpdev-locations'),
	__('Cordova', 'wpdev-locations'),
	__('Craig', 'wpdev-locations'),
	__('Deltana', 'wpdev-locations'),
	__('Denali Borough', 'wpdev-locations'),
	__('Diamond Ridge', 'wpdev-locations'),
	__('Dillingham', 'wpdev-locations'),
	__('Dillingham Census Area', 'wpdev-locations'),
	__('Dutch Harbor', 'wpdev-locations'),
	__('Eagle River', 'wpdev-locations'),
	__('Eielson Air Force Base', 'wpdev-locations'),
	__('Elmendorf Air Force Base', 'wpdev-locations'),
	__('Ester', 'wpdev-locations'),
	__('Fairbanks', 'wpdev-locations'),
	__('Fairbanks North Star Borough', 'wpdev-locations'),
	__('Farm Loop', 'wpdev-locations'),
	__('Farmers Loop', 'wpdev-locations'),
	__('Fishhook', 'wpdev-locations'),
	__('Fritz Creek', 'wpdev-locations'),
	__('Gateway', 'wpdev-locations'),
	__('Girdwood', 'wpdev-locations'),
	__('Haines', 'wpdev-locations'),
	__('Haines Borough', 'wpdev-locations'),
	__('Healy', 'wpdev-locations'),
	__('Homer', 'wpdev-locations'),
	__('Hoonah-Angoon Census Area', 'wpdev-locations'),
	__('Hooper Bay', 'wpdev-locations'),
	__('Houston', 'wpdev-locations'),
	__('Juneau', 'wpdev-locations'),
	__('Kalifornsky', 'wpdev-locations'),
	__('Kenai', 'wpdev-locations'),
	__('Kenai Peninsula Borough', 'wpdev-locations'),
	__('Ketchikan', 'wpdev-locations'),
	__('Ketchikan Gateway Borough', 'wpdev-locations'),
	__('King Cove', 'wpdev-locations'),
	__('Knik-Fairview', 'wpdev-locations'),
	__('Kodiak', 'wpdev-locations'),
	__('Kodiak Island Borough', 'wpdev-locations'),
	__('Kodiak Station', 'wpdev-locations'),
	__('Kotzebue', 'wpdev-locations'),
	__('Lake and Peninsula Borough', 'wpdev-locations'),
	__('Lakes', 'wpdev-locations'),
	__('Lazy Mountain', 'wpdev-locations'),
	__('Matanuska-Susitna Borough', 'wpdev-locations'),
	__('Meadow Lakes', 'wpdev-locations'),
	__('Metlakatla', 'wpdev-locations'),
	__('Nikiski', 'wpdev-locations'),
	__('Nome', 'wpdev-locations'),
	__('Nome Census Area', 'wpdev-locations'),
	__('North Pole', 'wpdev-locations'),
	__('North Slope Borough', 'wpdev-locations'),
	__('Northwest Arctic Borough', 'wpdev-locations'),
	__('Palmer', 'wpdev-locations'),
	__('Petersburg', 'wpdev-locations'),
	__('Petersburg Borough', 'wpdev-locations'),
	__('Prudhoe Bay', 'wpdev-locations'),
	__('Ridgeway', 'wpdev-locations'),
	__('Salcha', 'wpdev-locations'),
	__('Sand Point', 'wpdev-locations'),
	__('Seward', 'wpdev-locations'),
	__('Sitka', 'wpdev-locations'),
	__('Sitka City and Borough', 'wpdev-locations'),
	__('Skagway Municipality', 'wpdev-locations'),
	__('Soldotna', 'wpdev-locations'),
	__('Southeast Fairbanks Census Area', 'wpdev-locations'),
	__('Sterling', 'wpdev-locations'),
	__('Sutton-Alpine', 'wpdev-locations'),
	__('Tanaina', 'wpdev-locations'),
	__('Tok', 'wpdev-locations'),
	__('Unalaska', 'wpdev-locations'),
	__('Valdez', 'wpdev-locations'),
	__('Valdez-Cordova Census Area', 'wpdev-locations'),
	__('Wasilla', 'wpdev-locations'),
	__('Willow', 'wpdev-locations'),
	__('Wrangell', 'wpdev-locations'),
	__('Y', 'wpdev-locations'),
	__('Yakutat City and Borough', 'wpdev-locations'),
	__('Yukon-Koyukuk Census Area', 'wpdev-locations'),
);
