<?php // phpcs:ignore - @generation-checksum US-DE-54
/**
 * State City List for DE - US.
 *
 * City count: 54
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for DE - US.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bear', 'wpdev-locations'),
	__('Bellefonte', 'wpdev-locations'),
	__('Bethany Beach', 'wpdev-locations'),
	__('Blades', 'wpdev-locations'),
	__('Bridgeville', 'wpdev-locations'),
	__('Brookside', 'wpdev-locations'),
	__('Camden', 'wpdev-locations'),
	__('Cheswold', 'wpdev-locations'),
	__('Claymont', 'wpdev-locations'),
	__('Clayton', 'wpdev-locations'),
	__('Delaware City', 'wpdev-locations'),
	__('Delmar', 'wpdev-locations'),
	__('Dover', 'wpdev-locations'),
	__('Dover Base Housing', 'wpdev-locations'),
	__('Edgemoor', 'wpdev-locations'),
	__('Elsmere', 'wpdev-locations'),
	__('Felton', 'wpdev-locations'),
	__('Georgetown', 'wpdev-locations'),
	__('Glasgow', 'wpdev-locations'),
	__('Greenville', 'wpdev-locations'),
	__('Greenwood', 'wpdev-locations'),
	__('Harrington', 'wpdev-locations'),
	__('Highland Acres', 'wpdev-locations'),
	__('Hockessin', 'wpdev-locations'),
	__('Kent Acres', 'wpdev-locations'),
	__('Kent County', 'wpdev-locations'),
	__('Laurel', 'wpdev-locations'),
	__('Lewes', 'wpdev-locations'),
	__('Long Neck', 'wpdev-locations'),
	__('Middletown', 'wpdev-locations'),
	__('Milford', 'wpdev-locations'),
	__('Millsboro', 'wpdev-locations'),
	__('Milton', 'wpdev-locations'),
	__('New Castle', 'wpdev-locations'),
	__('New Castle County', 'wpdev-locations'),
	__('Newark', 'wpdev-locations'),
	__('Newport', 'wpdev-locations'),
	__('North Star', 'wpdev-locations'),
	__('Ocean View', 'wpdev-locations'),
	__('Pike Creek', 'wpdev-locations'),
	__('Pike Creek Valley', 'wpdev-locations'),
	__('Rehoboth Beach', 'wpdev-locations'),
	__('Rising Sun-Lebanon', 'wpdev-locations'),
	__('Riverview', 'wpdev-locations'),
	__('Rodney Village', 'wpdev-locations'),
	__('Seaford', 'wpdev-locations'),
	__('Selbyville', 'wpdev-locations'),
	__('Smyrna', 'wpdev-locations'),
	__('Sussex County', 'wpdev-locations'),
	__('Townsend', 'wpdev-locations'),
	__('Wilmington', 'wpdev-locations'),
	__('Wilmington Manor', 'wpdev-locations'),
	__('Woodside East', 'wpdev-locations'),
	__('Wyoming', 'wpdev-locations'),
);
