<?php // phpcs:ignore - @generation-checksum US-VT-96
/**
 * State City List for VT - US.
 *
 * City count: 96
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for VT - US.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Addison', 'wpdev-locations'),
	__('Addison County', 'wpdev-locations'),
	__('Arlington', 'wpdev-locations'),
	__('Barre', 'wpdev-locations'),
	__('Bellows Falls', 'wpdev-locations'),
	__('Bennington', 'wpdev-locations'),
	__('Bennington County', 'wpdev-locations'),
	__('Brandon', 'wpdev-locations'),
	__('Brattleboro', 'wpdev-locations'),
	__('Bridport', 'wpdev-locations'),
	__('Bristol', 'wpdev-locations'),
	__('Burlington', 'wpdev-locations'),
	__('Caledonia County', 'wpdev-locations'),
	__('Castleton', 'wpdev-locations'),
	__('Charlotte', 'wpdev-locations'),
	__('Chelsea', 'wpdev-locations'),
	__('Chester', 'wpdev-locations'),
	__('Chittenden', 'wpdev-locations'),
	__('Chittenden County', 'wpdev-locations'),
	__('Clarendon', 'wpdev-locations'),
	__('Colchester', 'wpdev-locations'),
	__('Danby', 'wpdev-locations'),
	__('Dover', 'wpdev-locations'),
	__('Enosburg Falls', 'wpdev-locations'),
	__('Essex County', 'wpdev-locations'),
	__('Essex Junction', 'wpdev-locations'),
	__('Fair Haven', 'wpdev-locations'),
	__('Ferrisburgh', 'wpdev-locations'),
	__('Franklin County', 'wpdev-locations'),
	__('Grand Isle County', 'wpdev-locations'),
	__('Guildhall', 'wpdev-locations'),
	__('Hardwick', 'wpdev-locations'),
	__('Hartford', 'wpdev-locations'),
	__('Hinesburg', 'wpdev-locations'),
	__('Hyde Park', 'wpdev-locations'),
	__('Jamaica', 'wpdev-locations'),
	__('Jericho', 'wpdev-locations'),
	__('Johnson', 'wpdev-locations'),
	__('Lamoille County', 'wpdev-locations'),
	__('Leicester', 'wpdev-locations'),
	__('Lincoln', 'wpdev-locations'),
	__('Londonderry', 'wpdev-locations'),
	__('Lunenburg', 'wpdev-locations'),
	__('Lyndon', 'wpdev-locations'),
	__('Lyndonville', 'wpdev-locations'),
	__('Manchester Center', 'wpdev-locations'),
	__('Mendon', 'wpdev-locations'),
	__('Middlebury (village)', 'wpdev-locations'),
	__('Milton', 'wpdev-locations'),
	__('Montgomery', 'wpdev-locations'),
	__('Montpelier', 'wpdev-locations'),
	__('Moretown', 'wpdev-locations'),
	__('Morristown', 'wpdev-locations'),
	__('Morrisville', 'wpdev-locations'),
	__('Mount Holly', 'wpdev-locations'),
	__('Newfane', 'wpdev-locations'),
	__('Newport', 'wpdev-locations'),
	__('North Bennington', 'wpdev-locations'),
	__('North Hero', 'wpdev-locations'),
	__('Northfield', 'wpdev-locations'),
	__('Orange County', 'wpdev-locations'),
	__('Orleans County', 'wpdev-locations'),
	__('Pawlet', 'wpdev-locations'),
	__('Poultney', 'wpdev-locations'),
	__('Pownal', 'wpdev-locations'),
	__('Randolph', 'wpdev-locations'),
	__('Richford', 'wpdev-locations'),
	__('Rockingham', 'wpdev-locations'),
	__('Rutland', 'wpdev-locations'),
	__('Rutland County', 'wpdev-locations'),
	__('Saint Albans', 'wpdev-locations'),
	__('Saint Johnsbury', 'wpdev-locations'),
	__('Salisbury', 'wpdev-locations'),
	__('South Barre', 'wpdev-locations'),
	__('South Burlington', 'wpdev-locations'),
	__('Springfield', 'wpdev-locations'),
	__('St Johnsbury', 'wpdev-locations'),
	__('Starksboro', 'wpdev-locations'),
	__('Stowe', 'wpdev-locations'),
	__('Swanton', 'wpdev-locations'),
	__('Townshend', 'wpdev-locations'),
	__('Vergennes', 'wpdev-locations'),
	__('Washington', 'wpdev-locations'),
	__('Washington County', 'wpdev-locations'),
	__('Waterbury', 'wpdev-locations'),
	__('West Brattleboro', 'wpdev-locations'),
	__('West Rutland', 'wpdev-locations'),
	__('White River Junction', 'wpdev-locations'),
	__('Wilder', 'wpdev-locations'),
	__('Williamstown', 'wpdev-locations'),
	__('Williston', 'wpdev-locations'),
	__('Windham County', 'wpdev-locations'),
	__('Windsor', 'wpdev-locations'),
	__('Windsor County', 'wpdev-locations'),
	__('Winooski', 'wpdev-locations'),
	__('Woodstock', 'wpdev-locations'),
);
