<?php // phpcs:ignore - @generation-checksum US-WY-80
/**
 * State City List for WY - US.
 *
 * City count: 80
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for WY - US.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Afton', 'wpdev-locations'),
	__('Albany County', 'wpdev-locations'),
	__('Antelope Valley-Crestview', 'wpdev-locations'),
	__('Arapahoe', 'wpdev-locations'),
	__('Bar Nunn', 'wpdev-locations'),
	__('Basin', 'wpdev-locations'),
	__('Big Horn County', 'wpdev-locations'),
	__('Buffalo', 'wpdev-locations'),
	__('Campbell County', 'wpdev-locations'),
	__('Carbon County', 'wpdev-locations'),
	__('Casper', 'wpdev-locations'),
	__('Cheyenne', 'wpdev-locations'),
	__('Cody', 'wpdev-locations'),
	__('Converse County', 'wpdev-locations'),
	__('Crook County', 'wpdev-locations'),
	__('Douglas', 'wpdev-locations'),
	__('Ethete', 'wpdev-locations'),
	__('Evanston', 'wpdev-locations'),
	__('Evansville', 'wpdev-locations'),
	__('Fort Washakie', 'wpdev-locations'),
	__('Fox Farm-College', 'wpdev-locations'),
	__('Fremont County', 'wpdev-locations'),
	__('Gillette', 'wpdev-locations'),
	__('Glenrock', 'wpdev-locations'),
	__('Goshen County', 'wpdev-locations'),
	__('Green River', 'wpdev-locations'),
	__('Greybull', 'wpdev-locations'),
	__('Guernsey', 'wpdev-locations'),
	__('Hoback', 'wpdev-locations'),
	__('Hot Springs County', 'wpdev-locations'),
	__('Jackson', 'wpdev-locations'),
	__('Johnson County', 'wpdev-locations'),
	__('Kemmerer', 'wpdev-locations'),
	__('Lander', 'wpdev-locations'),
	__('Laramie', 'wpdev-locations'),
	__('Laramie County', 'wpdev-locations'),
	__('Lincoln County', 'wpdev-locations'),
	__('Lovell', 'wpdev-locations'),
	__('Lusk', 'wpdev-locations'),
	__('Lyman', 'wpdev-locations'),
	__('Marbleton', 'wpdev-locations'),
	__('Mills', 'wpdev-locations'),
	__('Moorcroft', 'wpdev-locations'),
	__('Moose Wilson Road', 'wpdev-locations'),
	__('Mountain View', 'wpdev-locations'),
	__('Natrona County', 'wpdev-locations'),
	__('Newcastle', 'wpdev-locations'),
	__('Niobrara County', 'wpdev-locations'),
	__('North Rock Springs', 'wpdev-locations'),
	__('Park County', 'wpdev-locations'),
	__('Pine Bluffs', 'wpdev-locations'),
	__('Pinedale', 'wpdev-locations'),
	__('Platte County', 'wpdev-locations'),
	__('Powell', 'wpdev-locations'),
	__('Rafter J Ranch', 'wpdev-locations'),
	__('Ranchettes', 'wpdev-locations'),
	__('Rawlins', 'wpdev-locations'),
	__('Riverton', 'wpdev-locations'),
	__('Rock Springs', 'wpdev-locations'),
	__('Saratoga', 'wpdev-locations'),
	__('Sheridan', 'wpdev-locations'),
	__('Sheridan County', 'wpdev-locations'),
	__('Sleepy Hollow', 'wpdev-locations'),
	__('South Greeley', 'wpdev-locations'),
	__('South Park', 'wpdev-locations'),
	__('Star Valley Ranch', 'wpdev-locations'),
	__('Sublette County', 'wpdev-locations'),
	__('Sundance', 'wpdev-locations'),
	__('Sweetwater County', 'wpdev-locations'),
	__('Teton County', 'wpdev-locations'),
	__('Thermopolis', 'wpdev-locations'),
	__('Torrington', 'wpdev-locations'),
	__('Uinta County', 'wpdev-locations'),
	__('Upton', 'wpdev-locations'),
	__('Washakie County', 'wpdev-locations'),
	__('Weston County', 'wpdev-locations'),
	__('Wheatland', 'wpdev-locations'),
	__('Wilson', 'wpdev-locations'),
	__('Worland', 'wpdev-locations'),
	__('Wright', 'wpdev-locations'),
);
