<?php // phpcs:ignore - @generation-checksum RU-ARK-71
/**
 * State City List for ARK - RU.
 *
 * City count: 71
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ARK - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Arkhangel’sk', 'wpdev-locations'),
	__('Berëznik', 'wpdev-locations'),
	__('Cheremushskiy', 'wpdev-locations'),
	__('Dvinskoy', 'wpdev-locations'),
	__('Ileza', 'wpdev-locations'),
	__('Il’insko-Podomskoye', 'wpdev-locations'),
	__('Isakogorka', 'wpdev-locations'),
	__('Kamenka', 'wpdev-locations'),
	__('Kargopol’', 'wpdev-locations'),
	__('Kargopol’skiy Rayon', 'wpdev-locations'),
	__('Karpogory', 'wpdev-locations'),
	__('Katunino', 'wpdev-locations'),
	__('Kharitonovo', 'wpdev-locations'),
	__('Kholmogorskiy Rayon', 'wpdev-locations'),
	__('Kholmogory', 'wpdev-locations'),
	__('Kizema', 'wpdev-locations'),
	__('Kodino', 'wpdev-locations'),
	__('Konosha', 'wpdev-locations'),
	__('Konëvo', 'wpdev-locations'),
	__('Koryazhma', 'wpdev-locations'),
	__('Kotlas', 'wpdev-locations'),
	__('Kotlasskiy Rayon', 'wpdev-locations'),
	__('Krasnoborsk', 'wpdev-locations'),
	__('Kuloy', 'wpdev-locations'),
	__('Lenskiy Rayon', 'wpdev-locations'),
	__('Leshukonskiy Rayon', 'wpdev-locations'),
	__('Leshukonskoye', 'wpdev-locations'),
	__('Loyga', 'wpdev-locations'),
	__('Lukovetskiy', 'wpdev-locations'),
	__('Mezenskiy Rayon', 'wpdev-locations'),
	__('Mezen’', 'wpdev-locations'),
	__('Mirnyy', 'wpdev-locations'),
	__('Novodvinsk', 'wpdev-locations'),
	__('Nyandoma', 'wpdev-locations'),
	__('Nyandomskiy Rayon', 'wpdev-locations'),
	__('Oksovskiy', 'wpdev-locations'),
	__('Onega', 'wpdev-locations'),
	__('Onezhskiy Rayon', 'wpdev-locations'),
	__('Pinega', 'wpdev-locations'),
	__('Pinezhskiy Rayon', 'wpdev-locations'),
	__('Plesetsk', 'wpdev-locations'),
	__('Podyuga', 'wpdev-locations'),
	__('Primorskiy Rayon', 'wpdev-locations'),
	__('Privodino', 'wpdev-locations'),
	__('Puksoozero', 'wpdev-locations'),
	__('Rochegda', 'wpdev-locations'),
	__('Samoded', 'wpdev-locations'),
	__('Severodvinsk', 'wpdev-locations'),
	__('Shalakusha', 'wpdev-locations'),
	__('Shangaly', 'wpdev-locations'),
	__('Shenkursk', 'wpdev-locations'),
	__('Shenkurskiy Rayon', 'wpdev-locations'),
	__('Shipitsyno', 'wpdev-locations'),
	__('Solginskiy', 'wpdev-locations'),
	__('Sol’vychegodsk', 'wpdev-locations'),
	__('Udimskiy', 'wpdev-locations'),
	__('Urdoma', 'wpdev-locations'),
	__('Ust’-Shonosha', 'wpdev-locations'),
	__('Ust’yanskiy Rayon', 'wpdev-locations'),
	__('Uyemskiy', 'wpdev-locations'),
	__('Vas’kovo', 'wpdev-locations'),
	__('Vel’sk', 'wpdev-locations'),
	__('Vel’skiy Rayon', 'wpdev-locations'),
	__('Verkhnyaya Toyma', 'wpdev-locations'),
	__('Voloshka', 'wpdev-locations'),
	__('Vychegodskiy', 'wpdev-locations'),
	__('Yagry', 'wpdev-locations'),
	__('Yarensk', 'wpdev-locations'),
	__('Yemetsk', 'wpdev-locations'),
	__('Yemtsa', 'wpdev-locations'),
	__('Yertsevo', 'wpdev-locations'),
);
