<?php // phpcs:ignore - @generation-checksum RU-AST-40
/**
 * State City List for AST - RU.
 *
 * City count: 40
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AST - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akhtubinsk', 'wpdev-locations'),
	__('Akhtubinskiy Rayon', 'wpdev-locations'),
	__('Aksarayskiy', 'wpdev-locations'),
	__('Astrakhan', 'wpdev-locations'),
	__('Chyorny Yar', 'wpdev-locations'),
	__('Ikryanoye', 'wpdev-locations'),
	__('Kamyzyak', 'wpdev-locations'),
	__('Kapustin Yar', 'wpdev-locations'),
	__('Karalat', 'wpdev-locations'),
	__('Kharabali', 'wpdev-locations'),
	__('Kirovskiy', 'wpdev-locations'),
	__('Krasnoyarskiy Rayon', 'wpdev-locations'),
	__('Krasnyy Yar', 'wpdev-locations'),
	__('Krasnyye Barrikady', 'wpdev-locations'),
	__('Liman', 'wpdev-locations'),
	__('Limanskiy Rayon', 'wpdev-locations'),
	__('Marfino', 'wpdev-locations'),
	__('Mumra', 'wpdev-locations'),
	__('Nachalovo', 'wpdev-locations'),
	__('Narimanov', 'wpdev-locations'),
	__('Nizhniy Baskunchak', 'wpdev-locations'),
	__('Oranzherei', 'wpdev-locations'),
	__('Poldnëvoye', 'wpdev-locations'),
	__('Privolzhskiy Rayon', 'wpdev-locations'),
	__('Sasykoli', 'wpdev-locations'),
	__('Sizyy Bugor', 'wpdev-locations'),
	__('Solyanka', 'wpdev-locations'),
	__('Starokucherganovka', 'wpdev-locations'),
	__('Tambovka', 'wpdev-locations'),
	__('Trudfront', 'wpdev-locations'),
	__('Tumak', 'wpdev-locations'),
	__('Uvary', 'wpdev-locations'),
	__('Verkhniy Baskunchak', 'wpdev-locations'),
	__('Volgo-Kaspiyskiy', 'wpdev-locations'),
	__('Volodarskiy', 'wpdev-locations'),
	__('Yaksatovo', 'wpdev-locations'),
	__('Yandyki', 'wpdev-locations'),
	__('Yenotayevka', 'wpdev-locations'),
	__('Zenzeli', 'wpdev-locations'),
	__('Znamensk', 'wpdev-locations'),
);
