<?php // phpcs:ignore - @generation-checksum RU-BEL-56
/**
 * State City List for BEL - RU.
 *
 * City count: 56
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for BEL - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alekseyevka', 'wpdev-locations'),
	__('Bekhteyevka', 'wpdev-locations'),
	__('Belgorod', 'wpdev-locations'),
	__('Belgorodskiy Rayon', 'wpdev-locations'),
	__('Bessonovka', 'wpdev-locations'),
	__('Borisovka', 'wpdev-locations'),
	__('Borisovskiy Rayon', 'wpdev-locations'),
	__('Chernyanka', 'wpdev-locations'),
	__('Chernyanskiy Rayon', 'wpdev-locations'),
	__('Golovchino', 'wpdev-locations'),
	__('Grayvoron', 'wpdev-locations'),
	__('Grayvoronskiy Rayon', 'wpdev-locations'),
	__('Gubkin', 'wpdev-locations'),
	__('Ilovka', 'wpdev-locations'),
	__('Ivnya', 'wpdev-locations'),
	__('Ivnyanskiy Rayon', 'wpdev-locations'),
	__('Korocha', 'wpdev-locations'),
	__('Korochanskiy Rayon', 'wpdev-locations'),
	__('Krasnaya Yaruga', 'wpdev-locations'),
	__('Krasnenskiy Rayon', 'wpdev-locations'),
	__('Krasnogvardeyskiy Rayon', 'wpdev-locations'),
	__('Krasnogvardeyskoye', 'wpdev-locations'),
	__('Krasnoyaruzhskiy Rayon', 'wpdev-locations'),
	__('Krasnoye', 'wpdev-locations'),
	__('Livenka', 'wpdev-locations'),
	__('Maslova Pristan’', 'wpdev-locations'),
	__('Mayskiy', 'wpdev-locations'),
	__('Novaya Tavolzhanka', 'wpdev-locations'),
	__('Novooskol’skiy Rayon', 'wpdev-locations'),
	__('Novyy Oskol', 'wpdev-locations'),
	__('Prokhorovka', 'wpdev-locations'),
	__('Prokhorovskiy Rayon', 'wpdev-locations'),
	__('Proletarskiy', 'wpdev-locations'),
	__('Pyatnitskoye', 'wpdev-locations'),
	__('Rakitnoye', 'wpdev-locations'),
	__('Rakityanskiy Rayon', 'wpdev-locations'),
	__('Razumnoye', 'wpdev-locations'),
	__('Rogovatoye', 'wpdev-locations'),
	__('Roven’skiy Rayon', 'wpdev-locations'),
	__('Severnyy', 'wpdev-locations'),
	__('Shebekino', 'wpdev-locations'),
	__('Shebekinskiy Rayon', 'wpdev-locations'),
	__('Skorodnoye', 'wpdev-locations'),
	__('Staryy Oskol', 'wpdev-locations'),
	__('Stroitel’', 'wpdev-locations'),
	__('Tomarovka', 'wpdev-locations'),
	__('Troitskiy', 'wpdev-locations'),
	__('Urazovo', 'wpdev-locations'),
	__('Valuyki', 'wpdev-locations'),
	__('Valuyskiy Rayon', 'wpdev-locations'),
	__('Veydelevka', 'wpdev-locations'),
	__('Volokonovka', 'wpdev-locations'),
	__('Volokonovskiy Rayon', 'wpdev-locations'),
	__('Yakovlevo', 'wpdev-locations'),
	__('Yakovlevskiy Rayon', 'wpdev-locations'),
	__('Zasosna', 'wpdev-locations'),
);
