<?php // phpcs:ignore - @generation-checksum RU-BRY-83
/**
 * State City List for BRY - RU.
 *
 * City count: 83
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for BRY - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Altukhovo', 'wpdev-locations'),
	__('Ardon’', 'wpdev-locations'),
	__('Belyye Berega', 'wpdev-locations'),
	__('Brasovskiy Rayon', 'wpdev-locations'),
	__('Bryansk', 'wpdev-locations'),
	__('Bryanskiy Rayon', 'wpdev-locations'),
	__('Bytosh’', 'wpdev-locations'),
	__('Churovichi', 'wpdev-locations'),
	__('Dobrun’', 'wpdev-locations'),
	__('Dubrovka', 'wpdev-locations'),
	__('Dubrovskiy Rayon', 'wpdev-locations'),
	__('Dyat’kovo', 'wpdev-locations'),
	__('Dyat’kovskiy Rayon', 'wpdev-locations'),
	__('Glinishchevo', 'wpdev-locations'),
	__('Gordeyevka', 'wpdev-locations'),
	__('Gordeyevskiy Rayon', 'wpdev-locations'),
	__('Gorod Bryansk', 'wpdev-locations'),
	__('Gorod Dyat’kovo', 'wpdev-locations'),
	__('Ivanovka', 'wpdev-locations'),
	__('Ivot', 'wpdev-locations'),
	__('Karachev', 'wpdev-locations'),
	__('Kletnya', 'wpdev-locations'),
	__('Kletnyanskiy Rayon', 'wpdev-locations'),
	__('Klimovo', 'wpdev-locations'),
	__('Klimovskiy Rayon', 'wpdev-locations'),
	__('Klintsovskiy Rayon', 'wpdev-locations'),
	__('Klintsy', 'wpdev-locations'),
	__('Kokino', 'wpdev-locations'),
	__('Kokorevka', 'wpdev-locations'),
	__('Komarichi', 'wpdev-locations'),
	__('Komarichskiy Rayon', 'wpdev-locations'),
	__('Korzhovka-Golubovka', 'wpdev-locations'),
	__('Krasnaya Gora', 'wpdev-locations'),
	__('Krasnogorskiy Rayon', 'wpdev-locations'),
	__('Lokot’', 'wpdev-locations'),
	__('Lopandino', 'wpdev-locations'),
	__('Lyubokhna', 'wpdev-locations'),
	__('Lyubovsho', 'wpdev-locations'),
	__('Mglin', 'wpdev-locations'),
	__('Mglinskiy Rayon', 'wpdev-locations'),
	__('Navlinskiy Rayon', 'wpdev-locations'),
	__('Navlya', 'wpdev-locations'),
	__('Net’inka', 'wpdev-locations'),
	__('Novozybkov', 'wpdev-locations'),
	__('Novozybkovskiy Rayon', 'wpdev-locations'),
	__('Novyy Ropsk', 'wpdev-locations'),
	__('Pochep', 'wpdev-locations'),
	__('Pochepskiy Rayon', 'wpdev-locations'),
	__('Pogar', 'wpdev-locations'),
	__('Pogarskiy Rayon', 'wpdev-locations'),
	__('Putëvka', 'wpdev-locations'),
	__('Raditsa-Krylovka', 'wpdev-locations'),
	__('Rognedino', 'wpdev-locations'),
	__('Rognedinskiy Rayon', 'wpdev-locations'),
	__('Rzhanitsa', 'wpdev-locations'),
	__('Sachkovichi', 'wpdev-locations'),
	__('Sel’tso', 'wpdev-locations'),
	__('Seshcha', 'wpdev-locations'),
	__('Sevsk', 'wpdev-locations'),
	__('Sevskiy Rayon', 'wpdev-locations'),
	__('Starodub', 'wpdev-locations'),
	__('Starodubskiy Rayon', 'wpdev-locations'),
	__('Star’', 'wpdev-locations'),
	__('Suponevo', 'wpdev-locations'),
	__('Surazh', 'wpdev-locations'),
	__('Surazhskiy Rayon', 'wpdev-locations'),
	__('Suzemskiy Rayon', 'wpdev-locations'),
	__('Suzëmka', 'wpdev-locations'),
	__('Sven’', 'wpdev-locations'),
	__('Trubchevsk', 'wpdev-locations'),
	__('Trubchevskiy Rayon', 'wpdev-locations'),
	__('Unecha', 'wpdev-locations'),
	__('Unechskiy Rayon', 'wpdev-locations'),
	__('Vygonichi', 'wpdev-locations'),
	__('Vygonichskiy Rayon', 'wpdev-locations'),
	__('Vyshkov', 'wpdev-locations'),
	__('Zamishevo', 'wpdev-locations'),
	__('Zaymishche', 'wpdev-locations'),
	__('Zhiryatino', 'wpdev-locations'),
	__('Zhiryatinskiy Rayon', 'wpdev-locations'),
	__('Zhukovka', 'wpdev-locations'),
	__('Zhukovskiy Rayon', 'wpdev-locations'),
	__('Zlynka', 'wpdev-locations'),
);
