<?php // phpcs:ignore - @generation-checksum RU-BU-66
/**
 * State City List for BU - RU.
 *
 * City count: 66
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for BU - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Babushkin', 'wpdev-locations'),
	__('Bagdarin', 'wpdev-locations'),
	__('Barguzin', 'wpdev-locations'),
	__('Bayangol', 'wpdev-locations'),
	__('Bichura', 'wpdev-locations'),
	__('Bol’shoy Kunaley', 'wpdev-locations'),
	__('Dzhida', 'wpdev-locations'),
	__('Gusinoozyorsk', 'wpdev-locations'),
	__('Gusinoye Ozero', 'wpdev-locations'),
	__('Il’inka', 'wpdev-locations'),
	__('Il’ka', 'wpdev-locations'),
	__('Istok', 'wpdev-locations'),
	__('Ivolginsk', 'wpdev-locations'),
	__('Ivolginskiy Rayon', 'wpdev-locations'),
	__('Kabansk', 'wpdev-locations'),
	__('Kholtoson', 'wpdev-locations'),
	__('Khonkholoy', 'wpdev-locations'),
	__('Khorinsk', 'wpdev-locations'),
	__('Kichera', 'wpdev-locations'),
	__('Kizhinga', 'wpdev-locations'),
	__('Kudara-Somon', 'wpdev-locations'),
	__('Kurumkan', 'wpdev-locations'),
	__('Kyakhta', 'wpdev-locations'),
	__('Kyren', 'wpdev-locations'),
	__('Mukhorshibirskiy Rayon', 'wpdev-locations'),
	__('Mukhorshibir’', 'wpdev-locations'),
	__('Muyskiy Rayon', 'wpdev-locations'),
	__('Naushki', 'wpdev-locations'),
	__('Nikolayevskiy', 'wpdev-locations'),
	__('Nikol’sk', 'wpdev-locations'),
	__('Nizhneangarsk', 'wpdev-locations'),
	__('Nizhniy Sayantuy', 'wpdev-locations'),
	__('Novaya Bryan’', 'wpdev-locations'),
	__('Novokizhinginsk', 'wpdev-locations'),
	__('Novyy Uoyan', 'wpdev-locations'),
	__('Novyy Zagan', 'wpdev-locations'),
	__('Okino-Klyuchi', 'wpdev-locations'),
	__('Okinskiy Rayon', 'wpdev-locations'),
	__('Onokhoy', 'wpdev-locations'),
	__('Orlik', 'wpdev-locations'),
	__('Petropavlovka', 'wpdev-locations'),
	__('Pribaykal’skiy Rayon', 'wpdev-locations'),
	__('Rechka-Vydrino', 'wpdev-locations'),
	__('Sagan-Nur', 'wpdev-locations'),
	__('Selenduma', 'wpdev-locations'),
	__('Selenginskiy Rayon', 'wpdev-locations'),
	__('Severo-Baykal’skiy Rayon', 'wpdev-locations'),
	__('Severobaykal’sk', 'wpdev-locations'),
	__('Severomuysk', 'wpdev-locations'),
	__('Sharalday', 'wpdev-locations'),
	__('Sokol', 'wpdev-locations'),
	__('Sosnovo-Ozerskoye', 'wpdev-locations'),
	__('Sotnikovo', 'wpdev-locations'),
	__('Taksimo', 'wpdev-locations'),
	__('Tankhoy', 'wpdev-locations'),
	__('Tarbagatay', 'wpdev-locations'),
	__('Tataurovo', 'wpdev-locations'),
	__('Turka', 'wpdev-locations'),
	__('Turuntayevo', 'wpdev-locations'),
	__('Ulan-Ude', 'wpdev-locations'),
	__('Ust’-Barguzin', 'wpdev-locations'),
	__('Vydrino', 'wpdev-locations'),
	__('Zaigrayevo', 'wpdev-locations'),
	__('Zakamensk', 'wpdev-locations'),
	__('Zarechnyy', 'wpdev-locations'),
	__('Zhemchug', 'wpdev-locations'),
);
