<?php // phpcs:ignore - @generation-checksum RU-CHU-10
/**
 * State City List for CHU - RU.
 *
 * City count: 10
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for CHU - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Anadyr', 'wpdev-locations'),
	__('Anadyrskiy Rayon', 'wpdev-locations'),
	__('Beringovskiy', 'wpdev-locations'),
	__('Bilibino', 'wpdev-locations'),
	__('Egvekinot', 'wpdev-locations'),
	__('Lavrentiya', 'wpdev-locations'),
	__('Lorino', 'wpdev-locations'),
	__('Pevek', 'wpdev-locations'),
	__('Provideniya', 'wpdev-locations'),
	__('Providenskiy Rayon', 'wpdev-locations'),
);
