<?php // phpcs:ignore - @generation-checksum RU-IN-25
/**
 * State City List for IN - RU.
 *
 * City count: 25
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for IN - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ali-Yurt', 'wpdev-locations'),
	__('Alkhan-Churt', 'wpdev-locations'),
	__('Dalakovo', 'wpdev-locations'),
	__('Dzhayrakh', 'wpdev-locations'),
	__('Dzhayrakhskiy Rayon', 'wpdev-locations'),
	__('Ekazhevo', 'wpdev-locations'),
	__('Galashki', 'wpdev-locations'),
	__('Kantyshevo', 'wpdev-locations'),
	__('Karabulak', 'wpdev-locations'),
	__('Magas', 'wpdev-locations'),
	__('Malgobek', 'wpdev-locations'),
	__('Malgobekskiy Rayon', 'wpdev-locations'),
	__('Nazranovskiy Rayon', 'wpdev-locations'),
	__('Nazran’', 'wpdev-locations'),
	__('Nesterovskaya', 'wpdev-locations'),
	__('Nizhniye Achaluki', 'wpdev-locations'),
	__('Psedakh', 'wpdev-locations'),
	__('Sagopshi', 'wpdev-locations'),
	__('Staryy Malgobek', 'wpdev-locations'),
	__('Sunzha', 'wpdev-locations'),
	__('Sunzhenskiy Rayon', 'wpdev-locations'),
	__('Surkhakhi', 'wpdev-locations'),
	__('Troitskaya', 'wpdev-locations'),
	__('Verkhniye Achaluki', 'wpdev-locations'),
	__('Voznesenskaya', 'wpdev-locations'),
);
