<?php // phpcs:ignore - @generation-checksum RU-IVA-61
/**
 * State City List for IVA - RU.
 *
 * City count: 61
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for IVA - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Arkhipovka', 'wpdev-locations'),
	__('Bogorodskoye', 'wpdev-locations'),
	__('Dulyapino', 'wpdev-locations'),
	__('Furmanov', 'wpdev-locations'),
	__('Gavrilov Posad', 'wpdev-locations'),
	__('Il’inskoye-Khovanskoye', 'wpdev-locations'),
	__('Ivanovo', 'wpdev-locations'),
	__('Ivanovskiy Rayon', 'wpdev-locations'),
	__('Kamenka', 'wpdev-locations'),
	__('Kaminskiy', 'wpdev-locations'),
	__('Kineshemskiy Rayon', 'wpdev-locations'),
	__('Kineshma', 'wpdev-locations'),
	__('Kitovo', 'wpdev-locations'),
	__('Kokhma', 'wpdev-locations'),
	__('Kolobovo', 'wpdev-locations'),
	__('Komsomol’sk', 'wpdev-locations'),
	__('Komsomol’skiy Rayon', 'wpdev-locations'),
	__('Kuznechikha', 'wpdev-locations'),
	__('Lezhnevo', 'wpdev-locations'),
	__('Lezhnevskiy Rayon', 'wpdev-locations'),
	__('Lukh', 'wpdev-locations'),
	__('Lukhskiy Rayon', 'wpdev-locations'),
	__('Markovo', 'wpdev-locations'),
	__('Navoloki', 'wpdev-locations'),
	__('Nerl’', 'wpdev-locations'),
	__('Novo-Talitsy', 'wpdev-locations'),
	__('Novopistsovo', 'wpdev-locations'),
	__('Novoye Leushino', 'wpdev-locations'),
	__('Novyye Gorki', 'wpdev-locations'),
	__('Palekh', 'wpdev-locations'),
	__('Palekhskiy Rayon', 'wpdev-locations'),
	__('Pestyaki', 'wpdev-locations'),
	__('Pestyakovskiy Rayon', 'wpdev-locations'),
	__('Petrovskiy', 'wpdev-locations'),
	__('Pistsovo', 'wpdev-locations'),
	__('Plës', 'wpdev-locations'),
	__('Privolzhsk', 'wpdev-locations'),
	__('Privolzhskiy Rayon', 'wpdev-locations'),
	__('Puchezh', 'wpdev-locations'),
	__('Puchezhskiy Rayon', 'wpdev-locations'),
	__('Rodniki', 'wpdev-locations'),
	__('Rodnikovskiy Rayon', 'wpdev-locations'),
	__('Savino', 'wpdev-locations'),
	__('Savinskiy Rayon', 'wpdev-locations'),
	__('Shuya', 'wpdev-locations'),
	__('Shuyskiy Rayon', 'wpdev-locations'),
	__('Staraya Vichuga', 'wpdev-locations'),
	__('Talitsy', 'wpdev-locations'),
	__('Teykovo', 'wpdev-locations'),
	__('Teykovskiy Rayon', 'wpdev-locations'),
	__('Verkhnelandekhovskiy Rayon', 'wpdev-locations'),
	__('Verkhniy Landekh', 'wpdev-locations'),
	__('Vichuga', 'wpdev-locations'),
	__('Vichugskiy Rayon', 'wpdev-locations'),
	__('Yur’yevets', 'wpdev-locations'),
	__('Yur’yevetskiy Rayon', 'wpdev-locations'),
	__('Yuzha', 'wpdev-locations'),
	__('Yuzhskiy Rayon', 'wpdev-locations'),
	__('Zarechnyy', 'wpdev-locations'),
	__('Zavolzhsk', 'wpdev-locations'),
	__('Zavolzhskiy Rayon', 'wpdev-locations'),
);
