<?php // phpcs:ignore - @generation-checksum RU-KHA-40
/**
 * State City List for KHA - RU.
 *
 * City count: 40
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KHA - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Amursk', 'wpdev-locations'),
	__('Ayan', 'wpdev-locations'),
	__('Berëzovyy', 'wpdev-locations'),
	__('Bikin', 'wpdev-locations'),
	__('Bikinskiy Rayon', 'wpdev-locations'),
	__('Bogorodskoye', 'wpdev-locations'),
	__('Chegdomyn', 'wpdev-locations'),
	__('Chumikan', 'wpdev-locations'),
	__('De-Kastri', 'wpdev-locations'),
	__('Gorin', 'wpdev-locations'),
	__('Gornyy', 'wpdev-locations'),
	__('Imeni Poliny Osipenko', 'wpdev-locations'),
	__('Khabarovsk', 'wpdev-locations'),
	__('Khabarovsk Vtoroy', 'wpdev-locations'),
	__('Khor', 'wpdev-locations'),
	__('Khurba', 'wpdev-locations'),
	__('Knyaze-Volkonskoye', 'wpdev-locations'),
	__('Komsomolsk-on-Amur', 'wpdev-locations'),
	__('Korfovskiy', 'wpdev-locations'),
	__('Lazarev', 'wpdev-locations'),
	__('Lermontovka', 'wpdev-locations'),
	__('Litovko', 'wpdev-locations'),
	__('Lososina', 'wpdev-locations'),
	__('Mago', 'wpdev-locations'),
	__('Mayskiy', 'wpdev-locations'),
	__('Mnogovershinnyy', 'wpdev-locations'),
	__('Mukhen', 'wpdev-locations'),
	__('Nekrasovka', 'wpdev-locations'),
	__('Nikolayevsk-on-Amure', 'wpdev-locations'),
	__('Novyy Urgal', 'wpdev-locations'),
	__('Okhotsk', 'wpdev-locations'),
	__('Selikhino', 'wpdev-locations'),
	__('Solnechnyy', 'wpdev-locations'),
	__('Sovetskaya Gavan’', 'wpdev-locations'),
	__('Topolëvo', 'wpdev-locations'),
	__('Tyrma', 'wpdev-locations'),
	__('Vanino', 'wpdev-locations'),
	__('Vyazemskiy', 'wpdev-locations'),
	__('Vysokogornyy', 'wpdev-locations'),
	__('Zavety Il’icha', 'wpdev-locations'),
);
