<?php // phpcs:ignore - @generation-checksum RU-KHM-44
/**
 * State City List for KHM - RU.
 *
 * City count: 44
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KHM - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Agirish', 'wpdev-locations'),
	__('Andra', 'wpdev-locations'),
	__('Barsovo', 'wpdev-locations'),
	__('Beloyarskiy', 'wpdev-locations'),
	__('Berëzovo', 'wpdev-locations'),
	__('Fedorovskiy', 'wpdev-locations'),
	__('Gornopravdinsk', 'wpdev-locations'),
	__('Igrim', 'wpdev-locations'),
	__('Izluchinsk', 'wpdev-locations'),
	__('Khanty-Mansiysk', 'wpdev-locations'),
	__('Khulimsunt', 'wpdev-locations'),
	__('Kogalym', 'wpdev-locations'),
	__('Kommunisticheskiy', 'wpdev-locations'),
	__('Kondinskoye', 'wpdev-locations'),
	__('Kuminskiy', 'wpdev-locations'),
	__('Langepas', 'wpdev-locations'),
	__('Lokosovo', 'wpdev-locations'),
	__('Lyantor', 'wpdev-locations'),
	__('Malinovskiy', 'wpdev-locations'),
	__('Megion', 'wpdev-locations'),
	__('Mezhdurechenskiy', 'wpdev-locations'),
	__('Mortka', 'wpdev-locations'),
	__('Nefteyugansk', 'wpdev-locations'),
	__('Nizhnesortymskiy', 'wpdev-locations'),
	__('Nizhnevartovsk', 'wpdev-locations'),
	__('Novoagansk', 'wpdev-locations'),
	__('Nyagan', 'wpdev-locations'),
	__('Pionerskiy', 'wpdev-locations'),
	__('Pokachi', 'wpdev-locations'),
	__('Poykovskiy', 'wpdev-locations'),
	__('Priob’ye', 'wpdev-locations'),
	__('Pyt-Yakh', 'wpdev-locations'),
	__('Raduzhny', 'wpdev-locations'),
	__('Russkinskiye', 'wpdev-locations'),
	__('Salym', 'wpdev-locations'),
	__('Saranpaul’', 'wpdev-locations'),
	__('Sherkaly', 'wpdev-locations'),
	__('Singapay', 'wpdev-locations'),
	__('Solnechniy', 'wpdev-locations'),
	__('Sovetskiy', 'wpdev-locations'),
	__('Surgut', 'wpdev-locations'),
	__('Uray', 'wpdev-locations'),
	__('Yugorsk', 'wpdev-locations'),
	__('Zelenoborsk', 'wpdev-locations'),
);
