<?php // phpcs:ignore - @generation-checksum RU-KL-18
/**
 * State City List for KL - RU.
 *
 * City count: 18
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KL - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Arshan’', 'wpdev-locations'),
	__('Elista', 'wpdev-locations'),
	__('Gorodoviki', 'wpdev-locations'),
	__('Gorodovikovsk', 'wpdev-locations'),
	__('Iki-Burul', 'wpdev-locations'),
	__('Iki-Burul’skiy Rayon', 'wpdev-locations'),
	__('Kaspiyskiy', 'wpdev-locations'),
	__('Komsomol’skiy', 'wpdev-locations'),
	__('Malyye Derbety', 'wpdev-locations'),
	__('Priyutnoye', 'wpdev-locations'),
	__('Sadovoye', 'wpdev-locations'),
	__('Sarpinskiy Rayon', 'wpdev-locations'),
	__('Sovetskoye', 'wpdev-locations'),
	__('Troitskoye', 'wpdev-locations'),
	__('Tsagan Aman', 'wpdev-locations'),
	__('Yashalta', 'wpdev-locations'),
	__('Yashaltinskiy Rayon', 'wpdev-locations'),
	__('Yashkul’', 'wpdev-locations'),
);
