<?php // phpcs:ignore - @generation-checksum RU-KLU-70
/**
 * State City List for KLU - RU.
 *
 * City count: 70
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KLU - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Babynino', 'wpdev-locations'),
	__('Babyninskiy Rayon', 'wpdev-locations'),
	__('Balabanovo', 'wpdev-locations'),
	__('Baryatino', 'wpdev-locations'),
	__('Baryatinskiy Rayon', 'wpdev-locations'),
	__('Belousovo', 'wpdev-locations'),
	__('Betlitsa', 'wpdev-locations'),
	__('Borovsk', 'wpdev-locations'),
	__('Borovskiy Rayon', 'wpdev-locations'),
	__('Deshovki', 'wpdev-locations'),
	__('Detchino', 'wpdev-locations'),
	__('Duminichi', 'wpdev-locations'),
	__('Duminichskiy Rayon', 'wpdev-locations'),
	__('Dvortsy', 'wpdev-locations'),
	__('Dzerzhinskiy Rayon', 'wpdev-locations'),
	__('Ferzikovo', 'wpdev-locations'),
	__('Ferzikovskiy Rayon', 'wpdev-locations'),
	__('Iznoski', 'wpdev-locations'),
	__('Iznoskovskiy rayon', 'wpdev-locations'),
	__('Kaluga', 'wpdev-locations'),
	__('Khvastovichi', 'wpdev-locations'),
	__('Khvastovichskiy Rayon', 'wpdev-locations'),
	__('Kirov', 'wpdev-locations'),
	__('Kirovskiy Rayon', 'wpdev-locations'),
	__('Kondrovo', 'wpdev-locations'),
	__('Kozel’sk', 'wpdev-locations'),
	__('Kozel’skiy Rayon', 'wpdev-locations'),
	__('Kremenki', 'wpdev-locations'),
	__('Kudinovo', 'wpdev-locations'),
	__('Kurovskoye', 'wpdev-locations'),
	__('Kuybyshevskiy Rayon', 'wpdev-locations'),
	__('Lyudinovo', 'wpdev-locations'),
	__('Lyudinovskiy Rayon', 'wpdev-locations'),
	__('Maloyaroslavets', 'wpdev-locations'),
	__('Maloyaroslavetskiy Rayon', 'wpdev-locations'),
	__('Medynskiy Rayon', 'wpdev-locations'),
	__('Medyn’', 'wpdev-locations'),
	__('Meshchovsk', 'wpdev-locations'),
	__('Meshchovskiy Rayon', 'wpdev-locations'),
	__('Mosal’sk', 'wpdev-locations'),
	__('Mosal’skiy Rayon', 'wpdev-locations'),
	__('Mstikhino', 'wpdev-locations'),
	__('Myatlevo', 'wpdev-locations'),
	__('Nikola-Lenivets', 'wpdev-locations'),
	__('Obninsk', 'wpdev-locations'),
	__('Peremyshl’', 'wpdev-locations'),
	__('Peremyshl’skiy Rayon', 'wpdev-locations'),
	__('Polotnyanyy Zavod', 'wpdev-locations'),
	__('Pyatovskiy', 'wpdev-locations'),
	__('Seredeyskiy', 'wpdev-locations'),
	__('Sosenskiy', 'wpdev-locations'),
	__('Spas-Demensk', 'wpdev-locations'),
	__('Spas-Demenskiy Rayon', 'wpdev-locations'),
	__('Sukhinichi', 'wpdev-locations'),
	__('Sukhinichskiy Rayon', 'wpdev-locations'),
	__('Tarusa', 'wpdev-locations'),
	__('Tarusskiy Rayon', 'wpdev-locations'),
	__('Tovarkovo', 'wpdev-locations'),
	__('Ul’yanovskiy Rayon', 'wpdev-locations'),
	__('Vorotynsk', 'wpdev-locations'),
	__('Vysokinichi', 'wpdev-locations'),
	__('Yermolino', 'wpdev-locations'),
	__('Yukhnov', 'wpdev-locations'),
	__('Yukhnovskiy Rayon', 'wpdev-locations'),
	__('Zarech’ye', 'wpdev-locations'),
	__('Zhiletovo', 'wpdev-locations'),
	__('Zhizdra', 'wpdev-locations'),
	__('Zhizdrinskiy Rayon', 'wpdev-locations'),
	__('Zhukovo', 'wpdev-locations'),
	__('Zhukovskiy Rayon', 'wpdev-locations'),
);
