<?php // phpcs:ignore - @generation-checksum RU-KO-51
/**
 * State City List for KO - RU.
 *
 * City count: 51
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KO - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aykino', 'wpdev-locations'),
	__('Blagoyevo', 'wpdev-locations'),
	__('Borovoy', 'wpdev-locations'),
	__('Ezhva', 'wpdev-locations'),
	__('Inta', 'wpdev-locations'),
	__('Izhma', 'wpdev-locations'),
	__('Knyazhpogostskiy Rayon', 'wpdev-locations'),
	__('Kortkeros', 'wpdev-locations'),
	__('Koslan', 'wpdev-locations'),
	__('Koygorodok', 'wpdev-locations'),
	__('Koygorodskiy Rayon', 'wpdev-locations'),
	__('Kozhva', 'wpdev-locations'),
	__('Letka', 'wpdev-locations'),
	__('Mezhdurechensk', 'wpdev-locations'),
	__('Mikun’', 'wpdev-locations'),
	__('Mordino', 'wpdev-locations'),
	__('Nizhniy Odes', 'wpdev-locations'),
	__('Parma', 'wpdev-locations'),
	__('Pechora', 'wpdev-locations'),
	__('Priluzskiy Rayon', 'wpdev-locations'),
	__('Promyshlennyy', 'wpdev-locations'),
	__('Puteyets', 'wpdev-locations'),
	__('Sedkyrkeshch', 'wpdev-locations'),
	__('Shudayag', 'wpdev-locations'),
	__('Sindor', 'wpdev-locations'),
	__('Sosnogorsk', 'wpdev-locations'),
	__('Sovetskiy', 'wpdev-locations'),
	__('Syktyvkar', 'wpdev-locations'),
	__('Synya', 'wpdev-locations'),
	__('Troitsko-Pechorsk', 'wpdev-locations'),
	__('Troitsko-Pechorskiy Rayon', 'wpdev-locations'),
	__('Tsementnozavodskiy', 'wpdev-locations'),
	__('Ukhta', 'wpdev-locations'),
	__('Usinsk', 'wpdev-locations'),
	__('Usogorsk', 'wpdev-locations'),
	__('Ust-Tsilma', 'wpdev-locations'),
	__('Ust’-Kulom', 'wpdev-locations'),
	__('Ust’-Tsilemskiy Rayon', 'wpdev-locations'),
	__('Verkhnyaya Inta', 'wpdev-locations'),
	__('Verkhnyaya Maksakovka', 'wpdev-locations'),
	__('Vizinga', 'wpdev-locations'),
	__('Vodnyy', 'wpdev-locations'),
	__('Vorgashor', 'wpdev-locations'),
	__('Vorkuta', 'wpdev-locations'),
	__('Voyvozh', 'wpdev-locations'),
	__('Vuktyl', 'wpdev-locations'),
	__('Yarega', 'wpdev-locations'),
	__('Yemva', 'wpdev-locations'),
	__('Zapolyarnyy', 'wpdev-locations'),
	__('Zelenets', 'wpdev-locations'),
	__('Zheshart', 'wpdev-locations'),
);
