<?php // phpcs:ignore - @generation-checksum RU-KOS-44
/**
 * State City List for KOS - RU.
 *
 * City count: 44
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KOS - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Antropovo', 'wpdev-locations'),
	__('Antropovskiy Rayon', 'wpdev-locations'),
	__('Bogovarovo', 'wpdev-locations'),
	__('Buy', 'wpdev-locations'),
	__('Buyskiy Rayon', 'wpdev-locations'),
	__('Chistyye Bory', 'wpdev-locations'),
	__('Chukhloma', 'wpdev-locations'),
	__('Galich', 'wpdev-locations'),
	__('Galichskiy Rayon', 'wpdev-locations'),
	__('Georgiyevskoye', 'wpdev-locations'),
	__('Kadyy', 'wpdev-locations'),
	__('Kadyyskiy Rayon', 'wpdev-locations'),
	__('Kologriv', 'wpdev-locations'),
	__('Kosmynino', 'wpdev-locations'),
	__('Kostroma', 'wpdev-locations'),
	__('Kostromskoy Rayon', 'wpdev-locations'),
	__('Krasnosel’skiy Rayon', 'wpdev-locations'),
	__('Krasnoye-na-Volge', 'wpdev-locations'),
	__('Makar’yev', 'wpdev-locations'),
	__('Manturovo', 'wpdev-locations'),
	__('Manturovskiy Rayon', 'wpdev-locations'),
	__('Nerekhta', 'wpdev-locations'),
	__('Nerekhtskiy Rayon', 'wpdev-locations'),
	__('Neya', 'wpdev-locations'),
	__('Neyskiy Rayon', 'wpdev-locations'),
	__('Ostrovskiy Rayon', 'wpdev-locations'),
	__('Ostrovskoye', 'wpdev-locations'),
	__('Parfen’yevo', 'wpdev-locations'),
	__('Parfen’yevskiy Rayon', 'wpdev-locations'),
	__('Pavino', 'wpdev-locations'),
	__('Ponazyrevo', 'wpdev-locations'),
	__('Ponazyrevskiy Rayon', 'wpdev-locations'),
	__('Pyshchug', 'wpdev-locations'),
	__('Shar’inskiy Rayon', 'wpdev-locations'),
	__('Shar’ya', 'wpdev-locations'),
	__('Soligalich', 'wpdev-locations'),
	__('Soligalichskiy Rayon', 'wpdev-locations'),
	__('Sudislavl’', 'wpdev-locations'),
	__('Sudislavskiy Rayon', 'wpdev-locations'),
	__('Susanino', 'wpdev-locations'),
	__('Vetluzhskiy', 'wpdev-locations'),
	__('Vokhma', 'wpdev-locations'),
	__('Vokhomskiy Rayon', 'wpdev-locations'),
	__('Volgorechensk', 'wpdev-locations'),
);
