<?php // phpcs:ignore - @generation-checksum RU-KR-48
/**
 * State City List for KR - RU.
 *
 * City count: 48
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KR - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Belomorsk', 'wpdev-locations'),
	__('Borovoy', 'wpdev-locations'),
	__('Chupa', 'wpdev-locations'),
	__('Essoyla', 'wpdev-locations'),
	__('Girvas', 'wpdev-locations'),
	__('Kalevala', 'wpdev-locations'),
	__('Kem’', 'wpdev-locations'),
	__('Kharlu', 'wpdev-locations'),
	__('Khelyulya', 'wpdev-locations'),
	__('Kondopoga', 'wpdev-locations'),
	__('Kostomuksha', 'wpdev-locations'),
	__('Kvartsitnyy', 'wpdev-locations'),
	__('Lakhdenpokh’ya', 'wpdev-locations'),
	__('Ledmozero', 'wpdev-locations'),
	__('Loukhi', 'wpdev-locations'),
	__('Lyaskelya', 'wpdev-locations'),
	__('Matrosy', 'wpdev-locations'),
	__('Medvezh’yegorsk', 'wpdev-locations'),
	__('Muyezerskiy', 'wpdev-locations'),
	__('Nadvoitsy', 'wpdev-locations'),
	__('Olonets', 'wpdev-locations'),
	__('Petrozavodsk', 'wpdev-locations'),
	__('Pindushi', 'wpdev-locations'),
	__('Pitkyaranta', 'wpdev-locations'),
	__('Pitkyarantskiy Rayon', 'wpdev-locations'),
	__('Porosozero', 'wpdev-locations'),
	__('Povenets', 'wpdev-locations'),
	__('Prionezhskiy Rayon', 'wpdev-locations'),
	__('Pryazha', 'wpdev-locations'),
	__('Pudozh', 'wpdev-locations'),
	__('Pyaozerskiy', 'wpdev-locations'),
	__('Rabocheostrovsk', 'wpdev-locations'),
	__('Ruskeala', 'wpdev-locations'),
	__('Salmi', 'wpdev-locations'),
	__('Segezha', 'wpdev-locations'),
	__('Shal’skiy', 'wpdev-locations'),
	__('Sheltozero', 'wpdev-locations'),
	__('Shun’ga', 'wpdev-locations'),
	__('Shuya', 'wpdev-locations'),
	__('Sortavala', 'wpdev-locations'),
	__('Sortaval’skiy Rayon', 'wpdev-locations'),
	__('Sukkozero', 'wpdev-locations'),
	__('Suoyarvi', 'wpdev-locations'),
	__('Suoyarvskiy Rayon', 'wpdev-locations'),
	__('Vyartsilya', 'wpdev-locations'),
	__('Yanishpole', 'wpdev-locations'),
	__('Yanis’yarvi', 'wpdev-locations'),
	__('Yushkozero', 'wpdev-locations'),
);
