<?php // phpcs:ignore - @generation-checksum RU-LIP-47
/**
 * State City List for LIP - RU.
 *
 * City count: 47
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for LIP - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bol’shoy Khomutets', 'wpdev-locations'),
	__('Borinskoye', 'wpdev-locations'),
	__('Chaplygin', 'wpdev-locations'),
	__('Chaplyginskiy Rayon', 'wpdev-locations'),
	__('Dankov', 'wpdev-locations'),
	__('Dankovskiy Rayon', 'wpdev-locations'),
	__('Dobrinka', 'wpdev-locations'),
	__('Dobrinskiy Rayon', 'wpdev-locations'),
	__('Dobrovskiy Rayon', 'wpdev-locations'),
	__('Dobroye', 'wpdev-locations'),
	__('Dolgorukovo', 'wpdev-locations'),
	__('Dolgorukovskiy Rayon', 'wpdev-locations'),
	__('Donskoye', 'wpdev-locations'),
	__('Gryazi', 'wpdev-locations'),
	__('Gryazinskiy Rayon', 'wpdev-locations'),
	__('Izmalkovo', 'wpdev-locations'),
	__('Izmalkovskiy Rayon', 'wpdev-locations'),
	__('Kalikino', 'wpdev-locations'),
	__('Kazaki', 'wpdev-locations'),
	__('Kazinka', 'wpdev-locations'),
	__('Khlevenskiy Rayon', 'wpdev-locations'),
	__('Khlevnoye', 'wpdev-locations'),
	__('Krasninskiy Rayon', 'wpdev-locations'),
	__('Krasnoye', 'wpdev-locations'),
	__('Kuz’minskiye Otverzhki', 'wpdev-locations'),
	__('Lebedyanskiy Rayon', 'wpdev-locations'),
	__('Lebedyan’', 'wpdev-locations'),
	__('Lev Tolstoy', 'wpdev-locations'),
	__('Lev-Tolstovskiy Rayon', 'wpdev-locations'),
	__('Lipetsk', 'wpdev-locations'),
	__('Lipetskiy Rayon', 'wpdev-locations'),
	__('Petrovskiy', 'wpdev-locations'),
	__('Plekhanovo', 'wpdev-locations'),
	__('Prigorodka', 'wpdev-locations'),
	__('Stanovlyanskiy Rayon', 'wpdev-locations'),
	__('Stanovoye', 'wpdev-locations'),
	__('Syrskoye', 'wpdev-locations'),
	__('Terbunskiy Rayon', 'wpdev-locations'),
	__('Terbuny', 'wpdev-locations'),
	__('Usmanskiy Rayon', 'wpdev-locations'),
	__('Usman’', 'wpdev-locations'),
	__('Volovo', 'wpdev-locations'),
	__('Volovskiy Rayon', 'wpdev-locations'),
	__('Yelets', 'wpdev-locations'),
	__('Yeletskiy Rayon', 'wpdev-locations'),
	__('Zadonsk', 'wpdev-locations'),
	__('Zadonskiy Rayon', 'wpdev-locations'),
);
