<?php // phpcs:ignore - @generation-checksum RU-ME-35
/**
 * State City List for ME - RU.
 *
 * City count: 35
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ME - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Gornomariyskiy Rayon', 'wpdev-locations'),
	__('Kilemarskiy Rayon', 'wpdev-locations'),
	__('Kilemary', 'wpdev-locations'),
	__('Koz’modem’yansk', 'wpdev-locations'),
	__('Krasnogorskiy', 'wpdev-locations'),
	__('Kuzhener', 'wpdev-locations'),
	__('Kuzhenerskiy Rayon', 'wpdev-locations'),
	__('Mari-Turek', 'wpdev-locations'),
	__('Mari-Turekskiy Rayon', 'wpdev-locations'),
	__('Medvedevo', 'wpdev-locations'),
	__('Medvedevskiy Rayon', 'wpdev-locations'),
	__('Mochalishche', 'wpdev-locations'),
	__('Morki', 'wpdev-locations'),
	__('Morkinskiy Rayon', 'wpdev-locations'),
	__('Novotor”yal’skiy Rayon', 'wpdev-locations'),
	__('Orshanka', 'wpdev-locations'),
	__('Orshanskiy Rayon', 'wpdev-locations'),
	__('Paran’ga', 'wpdev-locations'),
	__('Paran’ginskiy Rayon', 'wpdev-locations'),
	__('Pomary', 'wpdev-locations'),
	__('Privolzhskiy', 'wpdev-locations'),
	__('Sernur', 'wpdev-locations'),
	__('Sernurskiy Rayon', 'wpdev-locations'),
	__('Sovetskiy', 'wpdev-locations'),
	__('Sovetskiy Rayon', 'wpdev-locations'),
	__('Surok', 'wpdev-locations'),
	__('Suslonger', 'wpdev-locations'),
	__('Vilovatovo', 'wpdev-locations'),
	__('Volzhsk', 'wpdev-locations'),
	__('Volzhskiy Rayon', 'wpdev-locations'),
	__('Yoshkar-Ola', 'wpdev-locations'),
	__('Yurino', 'wpdev-locations'),
	__('Yurinskiy Rayon', 'wpdev-locations'),
	__('Zvenigovo', 'wpdev-locations'),
	__('Zvenigovskiy Rayon', 'wpdev-locations'),
);
