<?php // phpcs:ignore - @generation-checksum RU-NEN-2
/**
 * State City List for NEN - RU.
 *
 * City count: 2
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NEN - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Iskateley', 'wpdev-locations'),
	__("Nar'yan-Mar", 'wpdev-locations'),
);
