<?php // phpcs:ignore - @generation-checksum RU-OMS-38
/**
 * State City List for OMS - RU.
 *
 * City count: 38
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for OMS - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Azovo', 'wpdev-locations'),
	__('Beregovoy', 'wpdev-locations'),
	__('Bol’sherech’ye', 'wpdev-locations'),
	__('Cherlak', 'wpdev-locations'),
	__('Irtyshskiy', 'wpdev-locations'),
	__('Kalachinsk', 'wpdev-locations'),
	__('Kolosovka', 'wpdev-locations'),
	__('Kormilovka', 'wpdev-locations'),
	__('Krasnoyarka', 'wpdev-locations'),
	__('Krasnyy Yar', 'wpdev-locations'),
	__('Krutaya Gorka', 'wpdev-locations'),
	__('Krutinka', 'wpdev-locations'),
	__('Luzino', 'wpdev-locations'),
	__('Lyubinskiy', 'wpdev-locations'),
	__('Muromtsevo', 'wpdev-locations'),
	__('Muromtsevskiy Rayon', 'wpdev-locations'),
	__('Nazyvayevsk', 'wpdev-locations'),
	__('Nizhnyaya Omka', 'wpdev-locations'),
	__('Novoomskiy', 'wpdev-locations'),
	__('Novovarshavka', 'wpdev-locations'),
	__('Odesskoye', 'wpdev-locations'),
	__('Okoneshnikovo', 'wpdev-locations'),
	__('Omsk', 'wpdev-locations'),
	__('Pavlogradka', 'wpdev-locations'),
	__('Poltavka', 'wpdev-locations'),
	__('Rostovka', 'wpdev-locations'),
	__('Russkaya Polyana', 'wpdev-locations'),
	__('Sargatskoye', 'wpdev-locations'),
	__('Sedel’nikovskiy Rayon', 'wpdev-locations'),
	__('Sherbakul’', 'wpdev-locations'),
	__('Tara', 'wpdev-locations'),
	__('Tavricheskoye', 'wpdev-locations'),
	__('Tevriz', 'wpdev-locations'),
	__('Troitsk', 'wpdev-locations'),
	__('Tyukalinsk', 'wpdev-locations'),
	__('Ust’-Ishim', 'wpdev-locations'),
	__('Vkhodnoy', 'wpdev-locations'),
	__('Znamenskoye', 'wpdev-locations'),
);
