<?php // phpcs:ignore - @generation-checksum RU-ORE-52
/**
 * State City List for ORE - RU.
 *
 * City count: 52
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ORE - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Abdulino', 'wpdev-locations'),
	__('Adamovka', 'wpdev-locations'),
	__('Alandskoye', 'wpdev-locations'),
	__('Asekeyevo', 'wpdev-locations'),
	__('Belyayevka', 'wpdev-locations'),
	__('Buguruslan', 'wpdev-locations'),
	__('Buzuluk', 'wpdev-locations'),
	__('Dombarovskiy', 'wpdev-locations'),
	__('Energetik', 'wpdev-locations'),
	__('Gay', 'wpdev-locations'),
	__('Ilek', 'wpdev-locations'),
	__('Kardailovo', 'wpdev-locations'),
	__('Koltubanovskiy', 'wpdev-locations'),
	__('Krasnogvardeyets', 'wpdev-locations'),
	__('Krasnokholm', 'wpdev-locations'),
	__('Krasnoyarskiy', 'wpdev-locations'),
	__('Krasnyy Kommunar', 'wpdev-locations'),
	__('Kurmanayevka', 'wpdev-locations'),
	__('Kuvandyk', 'wpdev-locations'),
	__('Kvarkeno', 'wpdev-locations'),
	__('Kvarkenskiy Rayon', 'wpdev-locations'),
	__('Matveyevka', 'wpdev-locations'),
	__('Mednogorsk', 'wpdev-locations'),
	__('Nezhinka', 'wpdev-locations'),
	__('Nizhnepavlovka', 'wpdev-locations'),
	__('Novoorsk', 'wpdev-locations'),
	__('Novoorskiy Rayon', 'wpdev-locations'),
	__('Novorudnyy', 'wpdev-locations'),
	__('Novosergiyevka', 'wpdev-locations'),
	__('Novotroitsk', 'wpdev-locations'),
	__('Orenburg', 'wpdev-locations'),
	__('Orsk', 'wpdev-locations'),
	__('Perevolotskiy', 'wpdev-locations'),
	__('Pleshanovo', 'wpdev-locations'),
	__('Podgorodnyaya Pokrovka', 'wpdev-locations'),
	__('Prigorodnyy', 'wpdev-locations'),
	__('Sakmara', 'wpdev-locations'),
	__('Saraktash', 'wpdev-locations'),
	__('Saraktashskiy Rayon', 'wpdev-locations'),
	__('Severnoye', 'wpdev-locations'),
	__('Sharlyk', 'wpdev-locations'),
	__('Shil’da', 'wpdev-locations'),
	__('Sol’-Iletsk', 'wpdev-locations'),
	__('Sorochinsk', 'wpdev-locations'),
	__('Staraya Akkermanovka', 'wpdev-locations'),
	__('Svetlyy', 'wpdev-locations'),
	__('Tashla', 'wpdev-locations'),
	__('Tatarskaya Kargala', 'wpdev-locations'),
	__('Totskoye', 'wpdev-locations'),
	__('Tyul’gan', 'wpdev-locations'),
	__('Yasnyy', 'wpdev-locations'),
	__('Yelizavetinka', 'wpdev-locations'),
);
