<?php // phpcs:ignore - @generation-checksum RU-PER-83
/**
 * State City List for PER - RU.
 *
 * City count: 83
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for PER - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aleksandrovsk', 'wpdev-locations'),
	__('Barda', 'wpdev-locations'),
	__('Berezniki', 'wpdev-locations'),
	__('Bershet’', 'wpdev-locations'),
	__('Chastyye', 'wpdev-locations'),
	__('Chaykovskaya', 'wpdev-locations'),
	__('Chaykovskiy', 'wpdev-locations'),
	__('Cherdyn’', 'wpdev-locations'),
	__('Chermoz', 'wpdev-locations'),
	__('Chernushka', 'wpdev-locations'),
	__('Chusovoy', 'wpdev-locations'),
	__('Dobryanka', 'wpdev-locations'),
	__('Ferma', 'wpdev-locations'),
	__('Filippovka', 'wpdev-locations'),
	__('Foki', 'wpdev-locations'),
	__('Froly', 'wpdev-locations'),
	__('Gamovo', 'wpdev-locations'),
	__('Gayny', 'wpdev-locations'),
	__('Gornozavodsk', 'wpdev-locations'),
	__('Gremyachinsk', 'wpdev-locations'),
	__('Gubakha', 'wpdev-locations'),
	__('Kalino', 'wpdev-locations'),
	__('Karagay', 'wpdev-locations'),
	__('Kerchevskiy', 'wpdev-locations'),
	__('Kizel', 'wpdev-locations'),
	__('Kochevo', 'wpdev-locations'),
	__('Komarikhinskiy', 'wpdev-locations'),
	__('Kondratovo', 'wpdev-locations'),
	__('Kosa', 'wpdev-locations'),
	__('Krasnokamsk', 'wpdev-locations'),
	__('Krasnovishersk', 'wpdev-locations'),
	__('Kudymkar', 'wpdev-locations'),
	__('Kukushtan', 'wpdev-locations'),
	__('Kultayevo', 'wpdev-locations'),
	__('Kungur', 'wpdev-locations'),
	__('Kuyeda', 'wpdev-locations'),
	__('Lobanovo', 'wpdev-locations'),
	__('Lyamino', 'wpdev-locations'),
	__('Lys’va', 'wpdev-locations'),
	__('Maykor', 'wpdev-locations'),
	__('Mendeleyevo', 'wpdev-locations'),
	__('Novyye Lyady', 'wpdev-locations'),
	__('Nyrob', 'wpdev-locations'),
	__('Nytva', 'wpdev-locations'),
	__('Ochër', 'wpdev-locations'),
	__('Okhansk', 'wpdev-locations'),
	__('Orda', 'wpdev-locations'),
	__('Osa', 'wpdev-locations'),
	__('Overyata', 'wpdev-locations'),
	__('Pashiya', 'wpdev-locations'),
	__('Pavlovskiy', 'wpdev-locations'),
	__('Perm', 'wpdev-locations'),
	__('Polazna', 'wpdev-locations'),
	__('Pozhva', 'wpdev-locations'),
	__('Sarany', 'wpdev-locations'),
	__('Sars', 'wpdev-locations'),
	__('Severnyy-Kospashskiy', 'wpdev-locations'),
	__('Shakhta', 'wpdev-locations'),
	__('Shirokovskiy', 'wpdev-locations'),
	__('Shumikhinskiy', 'wpdev-locations'),
	__('Siva', 'wpdev-locations'),
	__('Sokol', 'wpdev-locations'),
	__('Solikamsk', 'wpdev-locations'),
	__('Suksun', 'wpdev-locations'),
	__('Sylva', 'wpdev-locations'),
	__('Tëplaya Gora', 'wpdev-locations'),
	__('Ugleural’skiy', 'wpdev-locations'),
	__('Uinskoye', 'wpdev-locations'),
	__('Usol’ye', 'wpdev-locations'),
	__('Ust’-Kachka', 'wpdev-locations'),
	__('Ust’-Kishert’', 'wpdev-locations'),
	__('Vereshchagino', 'wpdev-locations'),
	__('Verkhnechusovskiye Gorodki', 'wpdev-locations'),
	__('Yayva', 'wpdev-locations'),
	__('Yelovo', 'wpdev-locations'),
	__('Yubileynyy', 'wpdev-locations'),
	__('Yug', 'wpdev-locations'),
	__('Yugo-Kamskiy', 'wpdev-locations'),
	__('Yurla', 'wpdev-locations'),
	__('Yus’vinskiy Rayon', 'wpdev-locations'),
	__('Yuzhnyy-Kospashskiy', 'wpdev-locations'),
	__('Zvëzdnyy', 'wpdev-locations'),
	__('Zyukayka', 'wpdev-locations'),
);
