<?php // phpcs:ignore - @generation-checksum RU-PRI-96
/**
 * State City List for PRI - RU.
 *
 * City count: 96
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for PRI - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Anuchino', 'wpdev-locations'),
	__('Anuchinskiy Rayon', 'wpdev-locations'),
	__('Arsen’yev', 'wpdev-locations'),
	__('Artëm', 'wpdev-locations'),
	__('Barabash', 'wpdev-locations'),
	__('Blagodatnoye', 'wpdev-locations'),
	__('Bol’shoy Kamen’', 'wpdev-locations'),
	__('Chernigovka', 'wpdev-locations'),
	__('Chernigovskiy Rayon', 'wpdev-locations'),
	__('Chernyshëvka', 'wpdev-locations'),
	__('Chkalovskoye', 'wpdev-locations'),
	__('Chuguyevka', 'wpdev-locations'),
	__('Dalnegorsk', 'wpdev-locations'),
	__('Dalnerechensk', 'wpdev-locations'),
	__('Dostoyevka', 'wpdev-locations'),
	__('Dunay', 'wpdev-locations'),
	__('Emar', 'wpdev-locations'),
	__('Fokino', 'wpdev-locations'),
	__('Gornorechenskiy', 'wpdev-locations'),
	__('Gornyye Klyuchi', 'wpdev-locations'),
	__('Grazhdanka', 'wpdev-locations'),
	__('Ivanovka', 'wpdev-locations'),
	__('Kamenka', 'wpdev-locations'),
	__('Kamen’-Rybolov', 'wpdev-locations'),
	__('Kavalerovo', 'wpdev-locations'),
	__('Khasanskiy Rayon', 'wpdev-locations'),
	__('Khorol’', 'wpdev-locations'),
	__('Kirovskiy', 'wpdev-locations'),
	__('Knevichi', 'wpdev-locations'),
	__('Kraskino', 'wpdev-locations'),
	__('Krasnorechenskiy', 'wpdev-locations'),
	__('Lazo', 'wpdev-locations'),
	__('Lazovskiy Rayon', 'wpdev-locations'),
	__('Lesozavodsk', 'wpdev-locations'),
	__('Lipovtsy', 'wpdev-locations'),
	__('Livadiya', 'wpdev-locations'),
	__('Luchegorsk', 'wpdev-locations'),
	__('Luchki', 'wpdev-locations'),
	__('Lyalichi', 'wpdev-locations'),
	__('Mikhaylovka', 'wpdev-locations'),
	__('Mikhaylovskiy Rayon', 'wpdev-locations'),
	__('Mnogoudobnoye', 'wpdev-locations'),
	__('Monastyrishche', 'wpdev-locations'),
	__('Nadezhdinskiy Rayon', 'wpdev-locations'),
	__('Nakhodka', 'wpdev-locations'),
	__('Novonikol’sk', 'wpdev-locations'),
	__('Novopokrovka', 'wpdev-locations'),
	__('Novoshakhtinskiy', 'wpdev-locations'),
	__('Novosysoyevka', 'wpdev-locations'),
	__('Novyy', 'wpdev-locations'),
	__('Ol’ga', 'wpdev-locations'),
	__('Partizansk', 'wpdev-locations'),
	__('Plastun', 'wpdev-locations'),
	__('Pogranichnyy', 'wpdev-locations'),
	__('Pokrovka', 'wpdev-locations'),
	__('Popova', 'wpdev-locations'),
	__('Preobrazheniye', 'wpdev-locations'),
	__('Primorskiy', 'wpdev-locations'),
	__('Putyatin', 'wpdev-locations'),
	__('Razdol’noye', 'wpdev-locations'),
	__('Rettikhovka', 'wpdev-locations'),
	__('Romanovka', 'wpdev-locations'),
	__('Rudnaya Pristan’', 'wpdev-locations'),
	__('Rudnyy', 'wpdev-locations'),
	__('Russkiy', 'wpdev-locations'),
	__('Sergeyevka', 'wpdev-locations'),
	__('Shkotovo', 'wpdev-locations'),
	__('Shkotovskiy Rayon', 'wpdev-locations'),
	__('Shtykovo', 'wpdev-locations'),
	__('Sivakovka', 'wpdev-locations'),
	__('Slavyanka', 'wpdev-locations'),
	__('Smolyaninovo', 'wpdev-locations'),
	__('Spassk-Dal’niy', 'wpdev-locations'),
	__('Spasskiy Rayon', 'wpdev-locations'),
	__('Spasskoye', 'wpdev-locations'),
	__('Svetlaya', 'wpdev-locations'),
	__('Tavrichanka', 'wpdev-locations'),
	__('Terney', 'wpdev-locations'),
	__('Trudovoye', 'wpdev-locations'),
	__('Uglekamensk', 'wpdev-locations'),
	__('Uglovoye', 'wpdev-locations'),
	__('Ussuriysk', 'wpdev-locations'),
	__('Vladimiro-Aleksandrovskoye', 'wpdev-locations'),
	__('Vladivostok', 'wpdev-locations'),
	__('Volchanets', 'wpdev-locations'),
	__('Vol’no-Nadezhdinskoye', 'wpdev-locations'),
	__('Vostok', 'wpdev-locations'),
	__('Vozdvizhenka', 'wpdev-locations'),
	__('Vrangel’', 'wpdev-locations'),
	__('Yakovlevka', 'wpdev-locations'),
	__('Yakovlevskiy Rayon', 'wpdev-locations'),
	__('Yaroslavskiy', 'wpdev-locations'),
	__('Yekaterinovka', 'wpdev-locations'),
	__('Zarubino', 'wpdev-locations'),
	__('Zavodskoy', 'wpdev-locations'),
	__('Zharikovo', 'wpdev-locations'),
);
