<?php // phpcs:ignore - @generation-checksum RU-RYA-48
/**
 * State City List for RYA - RU.
 *
 * City count: 48
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for RYA - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aleksandro-Nevskiy', 'wpdev-locations'),
	__('Bagramovo', 'wpdev-locations'),
	__('Chuchkovo', 'wpdev-locations'),
	__('Gus’-Zheleznyy', 'wpdev-locations'),
	__('Izhevskoye', 'wpdev-locations'),
	__('Kadom', 'wpdev-locations'),
	__('Kasimov', 'wpdev-locations'),
	__('Kasimovskiy Rayon', 'wpdev-locations'),
	__('Kiritsy', 'wpdev-locations'),
	__('Klepikovskiy Rayon', 'wpdev-locations'),
	__('Korablino', 'wpdev-locations'),
	__('Lashma', 'wpdev-locations'),
	__('Lesnoy', 'wpdev-locations'),
	__('Mikhaylov', 'wpdev-locations'),
	__('Miloslavskoye', 'wpdev-locations'),
	__('Murmino', 'wpdev-locations'),
	__('Novomichurinsk', 'wpdev-locations'),
	__('Oktyabr’skiy', 'wpdev-locations'),
	__('Pavelets', 'wpdev-locations'),
	__('Pitelino', 'wpdev-locations'),
	__('Polyany', 'wpdev-locations'),
	__('Pronsk', 'wpdev-locations'),
	__('Putyatino', 'wpdev-locations'),
	__('Ryazanskiy Rayon', 'wpdev-locations'),
	__('Ryazan’', 'wpdev-locations'),
	__('Ryazhsk', 'wpdev-locations'),
	__('Rybnovskiy Rayon', 'wpdev-locations'),
	__('Rybnoye', 'wpdev-locations'),
	__('Sapozhok', 'wpdev-locations'),
	__('Sarai', 'wpdev-locations'),
	__('Sasovo', 'wpdev-locations'),
	__('Shatsk', 'wpdev-locations'),
	__('Shilovo', 'wpdev-locations'),
	__('Skopin', 'wpdev-locations'),
	__('Solotcha', 'wpdev-locations'),
	__('Spas-Klepiki', 'wpdev-locations'),
	__('Spassk-Ryazanskiy', 'wpdev-locations'),
	__('Starozhilovo', 'wpdev-locations'),
	__('Syntul', 'wpdev-locations'),
	__('Tuma', 'wpdev-locations'),
	__('Ukholovo', 'wpdev-locations'),
	__('Vilenka', 'wpdev-locations'),
	__('Yambirno', 'wpdev-locations'),
	__('Yelat’ma', 'wpdev-locations'),
	__('Yermish’', 'wpdev-locations'),
	__('Zakharovo', 'wpdev-locations'),
	__('Zakharovskiy Rayon', 'wpdev-locations'),
	__('Zarechnyy', 'wpdev-locations'),
);
