<?php // phpcs:ignore - @generation-checksum RU-SA-86
/**
 * State City List for SA - RU.
 *
 * City count: 86
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SA - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Abyysky District', 'wpdev-locations'),
	__('Aldan', 'wpdev-locations'),
	__('Allaikhovskiy Rayon', 'wpdev-locations'),
	__('Almaznyy', 'wpdev-locations'),
	__('Amga', 'wpdev-locations'),
	__('Anabarskiy Rayon', 'wpdev-locations'),
	__('Aykhal', 'wpdev-locations'),
	__('Batagay', 'wpdev-locations'),
	__('Batagay-Alyta', 'wpdev-locations'),
	__('Belaya Gora', 'wpdev-locations'),
	__('Berdigestyakh', 'wpdev-locations'),
	__('Berkakit', 'wpdev-locations'),
	__('Borogontsy', 'wpdev-locations'),
	__('Bulunskiy Rayon', 'wpdev-locations'),
	__('Chernyshevskiy', 'wpdev-locations'),
	__('Cherskiy', 'wpdev-locations'),
	__('Chokurdakh', 'wpdev-locations'),
	__('Chul’man', 'wpdev-locations'),
	__('Churapcha', 'wpdev-locations'),
	__('Deputatsky', 'wpdev-locations'),
	__('Dzhebariki-Khaya', 'wpdev-locations'),
	__('Eveno-Bytantaysky National District', 'wpdev-locations'),
	__('Gornyy Rayon', 'wpdev-locations'),
	__('Kangalassy', 'wpdev-locations'),
	__('Khandyga', 'wpdev-locations'),
	__('Khatassy', 'wpdev-locations'),
	__('Kobyayskiy Rayon', 'wpdev-locations'),
	__('Kysyl-Syr', 'wpdev-locations'),
	__('Lebedinyy', 'wpdev-locations'),
	__('Leninskiy', 'wpdev-locations'),
	__('Lensk', 'wpdev-locations'),
	__('Magan', 'wpdev-locations'),
	__('Markha', 'wpdev-locations'),
	__('Mayya', 'wpdev-locations'),
	__('Mirninskiy Rayon', 'wpdev-locations'),
	__('Mirny', 'wpdev-locations'),
	__('Mokhsogollokh', 'wpdev-locations'),
	__('Momsky District', 'wpdev-locations'),
	__('Namskiy Rayon', 'wpdev-locations'),
	__('Namtsy', 'wpdev-locations'),
	__('Neryungri', 'wpdev-locations'),
	__('Nezhdaninskoe', 'wpdev-locations'),
	__('Nizhniy Bestyakh', 'wpdev-locations'),
	__('Nizhniy Kuranakh', 'wpdev-locations'),
	__('Nyurba', 'wpdev-locations'),
	__('Nyurbinsky District', 'wpdev-locations'),
	__('Olenyok', 'wpdev-locations'),
	__('Olenyoksky District', 'wpdev-locations'),
	__('Olyokminsk', 'wpdev-locations'),
	__('Olyokminsky District', 'wpdev-locations'),
	__('Oymyakonskiy District', 'wpdev-locations'),
	__('Peleduy', 'wpdev-locations'),
	__('Pokrovsk', 'wpdev-locations'),
	__('Sangar', 'wpdev-locations'),
	__('Saskylakh', 'wpdev-locations'),
	__('Serebryanyy Bor', 'wpdev-locations'),
	__('Solnechnyy', 'wpdev-locations'),
	__('Srednekolymsk', 'wpdev-locations'),
	__('Srednekolymsky District', 'wpdev-locations'),
	__('Suntar', 'wpdev-locations'),
	__('Suntarskiy District', 'wpdev-locations'),
	__('Tabaga', 'wpdev-locations'),
	__('Tiksi', 'wpdev-locations'),
	__('Tommot', 'wpdev-locations'),
	__('Tomponskiy District', 'wpdev-locations'),
	__('Udachny', 'wpdev-locations'),
	__('Ust-Aldansky District', 'wpdev-locations'),
	__('Ust-Kuyga', 'wpdev-locations'),
	__('Ust-Maya', 'wpdev-locations'),
	__('Ust-Nera', 'wpdev-locations'),
	__('Ust’-Yanskiy Rayon', 'wpdev-locations'),
	__('Verkhnekolymsky District', 'wpdev-locations'),
	__('Verkhnevilyuysk', 'wpdev-locations'),
	__('Verkhnevilyuysky District', 'wpdev-locations'),
	__('Verkhoyansk', 'wpdev-locations'),
	__('Verkhoyansky District', 'wpdev-locations'),
	__('Vilyuysk', 'wpdev-locations'),
	__('Vilyuyskiy Rayon', 'wpdev-locations'),
	__('Vilyuysky District', 'wpdev-locations'),
	__('Vitim', 'wpdev-locations'),
	__('Yakutsk', 'wpdev-locations'),
	__('Ytyk-Kyuyël’', 'wpdev-locations'),
	__('Zhatay', 'wpdev-locations'),
	__('Zhigansk', 'wpdev-locations'),
	__('Zhigansky District', 'wpdev-locations'),
	__('Zyryanka', 'wpdev-locations'),
);
