<?php // phpcs:ignore - @generation-checksum RU-SAK-42
/**
 * State City List for SAK - RU.
 *
 * City count: 42
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SAK - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aleksandrovsk-Sakhalinskiy', 'wpdev-locations'),
	__('Aniva', 'wpdev-locations'),
	__('Boshnyakovo', 'wpdev-locations'),
	__('Bykov', 'wpdev-locations'),
	__('Chekhov', 'wpdev-locations'),
	__('Dolinsk', 'wpdev-locations'),
	__('Gastello', 'wpdev-locations'),
	__('Gornozavodsk', 'wpdev-locations'),
	__('Kholmsk', 'wpdev-locations'),
	__('Korsakov', 'wpdev-locations'),
	__('Krasnogorsk', 'wpdev-locations'),
	__('Kurilsky District', 'wpdev-locations'),
	__('Kuril’sk', 'wpdev-locations'),
	__('Leonidovo', 'wpdev-locations'),
	__('Makarov', 'wpdev-locations'),
	__('Mgachi', 'wpdev-locations'),
	__('Nevel’sk', 'wpdev-locations'),
	__('Nogliki', 'wpdev-locations'),
	__('Okha', 'wpdev-locations'),
	__('Otrada', 'wpdev-locations'),
	__('Poronaysk', 'wpdev-locations'),
	__('Pravda', 'wpdev-locations'),
	__('Severo-Kuril’sk', 'wpdev-locations'),
	__('Shakhtersk', 'wpdev-locations'),
	__('Shebunino', 'wpdev-locations'),
	__('Shikotan', 'wpdev-locations'),
	__('Sinegorsk', 'wpdev-locations'),
	__('Smirnykh', 'wpdev-locations'),
	__('Sokol', 'wpdev-locations'),
	__('Tomari', 'wpdev-locations'),
	__('Troitskoye', 'wpdev-locations'),
	__('Tungor', 'wpdev-locations'),
	__('Tymovskoye', 'wpdev-locations'),
	__('Uglegorsk', 'wpdev-locations'),
	__('Uglegorskiy Rayon', 'wpdev-locations'),
	__('Uglezavodsk', 'wpdev-locations'),
	__('Vakhrushev', 'wpdev-locations'),
	__('Vostok', 'wpdev-locations'),
	__('Yablochnyy', 'wpdev-locations'),
	__('Yuzhno-Kurilsk', 'wpdev-locations'),
	__('Yuzhno-Kurilsky District', 'wpdev-locations'),
	__('Yuzhno-Sakhalinsk', 'wpdev-locations'),
);
