<?php // phpcs:ignore - @generation-checksum RU-SE-31
/**
 * State City List for SE - RU.
 *
 * City count: 31
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SE - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alagir', 'wpdev-locations'),
	__('Alagirskiy Rayon', 'wpdev-locations'),
	__('Ardon', 'wpdev-locations'),
	__('Arkhonskaya', 'wpdev-locations'),
	__('Beslan', 'wpdev-locations'),
	__('Chermen', 'wpdev-locations'),
	__('Chikola', 'wpdev-locations'),
	__('Dachnoye', 'wpdev-locations'),
	__('Digora', 'wpdev-locations'),
	__('Digorskiy Rayon', 'wpdev-locations'),
	__('Gizel’', 'wpdev-locations'),
	__('Irafskiy Rayon', 'wpdev-locations'),
	__('Kambileyevskoye', 'wpdev-locations'),
	__('Kardzhin', 'wpdev-locations'),
	__('Khumalag', 'wpdev-locations'),
	__('Kirovskiy Rayon', 'wpdev-locations'),
	__('Kizlyar', 'wpdev-locations'),
	__('Mikhaylovskoye', 'wpdev-locations'),
	__('Mizur', 'wpdev-locations'),
	__('Mozdok', 'wpdev-locations'),
	__('Nogir', 'wpdev-locations'),
	__('Pavlodol’skaya', 'wpdev-locations'),
	__('Pravoberezhnyy Rayon', 'wpdev-locations'),
	__('Prigorodnyy Rayon', 'wpdev-locations'),
	__('Sunzha', 'wpdev-locations'),
	__('Tarskoye', 'wpdev-locations'),
	__('Terskaya', 'wpdev-locations'),
	__('Troitskoye', 'wpdev-locations'),
	__('Verkhniy Fiagdon', 'wpdev-locations'),
	__('Vladikavkaz', 'wpdev-locations'),
	__('Zmeyskaya', 'wpdev-locations'),
);
