<?php // phpcs:ignore - @generation-checksum RU-SMO-36
/**
 * State City List for SMO - RU.
 *
 * City count: 36
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SMO - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Demidov', 'wpdev-locations'),
	__('Desnogorsk', 'wpdev-locations'),
	__('Dorogobuzh', 'wpdev-locations'),
	__('Dukhovshchina', 'wpdev-locations'),
	__('Gagarin', 'wpdev-locations'),
	__('Glinka', 'wpdev-locations'),
	__('Golynki', 'wpdev-locations'),
	__('Kardymovo', 'wpdev-locations'),
	__("Katyn'", 'wpdev-locations'),
	__('Khislavichi', 'wpdev-locations'),
	__('Kholm-Zhirkovskiy', 'wpdev-locations'),
	__('Monastyrshchina', 'wpdev-locations'),
	__('Novodugino', 'wpdev-locations'),
	__('Oster', 'wpdev-locations'),
	__('Ozërnyy', 'wpdev-locations'),
	__('Pechersk', 'wpdev-locations'),
	__('Pochinok', 'wpdev-locations'),
	__('Roslavl’', 'wpdev-locations'),
	__('Rudnya', 'wpdev-locations'),
	__('Safonovo', 'wpdev-locations'),
	__('Safonovskiy Rayon', 'wpdev-locations'),
	__('Shatalovo', 'wpdev-locations'),
	__('Shumyachi', 'wpdev-locations'),
	__('Smolensk', 'wpdev-locations'),
	__('Stodolishche', 'wpdev-locations'),
	__('Sychëvka', 'wpdev-locations'),
	__('Talashkino', 'wpdev-locations'),
	__('Tëmkino', 'wpdev-locations'),
	__('Ugra', 'wpdev-locations'),
	__('Velizh', 'wpdev-locations'),
	__('Verkhnedneprovskiy', 'wpdev-locations'),
	__('Vyaz’ma', 'wpdev-locations'),
	__('Yartsevo', 'wpdev-locations'),
	__('Yekimovichi', 'wpdev-locations'),
	__('Yel’nya', 'wpdev-locations'),
	__('Yershichi', 'wpdev-locations'),
);
