<?php // phpcs:ignore - @generation-checksum RU-SPE-58
/**
 * State City List for SPE - RU.
 *
 * City count: 58
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SPE - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Admiralteisky', 'wpdev-locations'),
	__('Aleksandrovskaya', 'wpdev-locations'),
	__('Avtovo', 'wpdev-locations'),
	__('Beloostrov', 'wpdev-locations'),
	__('Centralniy', 'wpdev-locations'),
	__('Dachnoye', 'wpdev-locations'),
	__('Frunzenskiy Rayon', 'wpdev-locations'),
	__('Gorelovo', 'wpdev-locations'),
	__('Grazhdanka', 'wpdev-locations'),
	__('Kolomyagi', 'wpdev-locations'),
	__('Kolpino', 'wpdev-locations'),
	__('Komarovo', 'wpdev-locations'),
	__('Komendantsky aerodrom', 'wpdev-locations'),
	__('Krasnogvargeisky', 'wpdev-locations'),
	__('Krasnoye Selo', 'wpdev-locations'),
	__('Kronshtadt', 'wpdev-locations'),
	__('Kupchino', 'wpdev-locations'),
	__('Kurortnyy Rayon', 'wpdev-locations'),
	__('Kushelevka', 'wpdev-locations'),
	__('Lakhtinskiy', 'wpdev-locations'),
	__('Levashovo', 'wpdev-locations'),
	__('Lisiy Nos', 'wpdev-locations'),
	__('Lomonosov', 'wpdev-locations'),
	__('Metallostroy', 'wpdev-locations'),
	__('Molodezhnoye', 'wpdev-locations'),
	__('Novaya Derevnya', 'wpdev-locations'),
	__('Obukhovo', 'wpdev-locations'),
	__('Ol’gino', 'wpdev-locations'),
	__('Ozerki', 'wpdev-locations'),
	__('Pargolovo', 'wpdev-locations'),
	__('Pavlovsk', 'wpdev-locations'),
	__('Pesochnyy', 'wpdev-locations'),
	__('Peterhof', 'wpdev-locations'),
	__('Petro-Slavyanka', 'wpdev-locations'),
	__('Petrodvorets', 'wpdev-locations'),
	__('Petrogradka', 'wpdev-locations'),
	__('Pontonnyy', 'wpdev-locations'),
	__('Primorskiy Rayon', 'wpdev-locations'),
	__('Pushkin', 'wpdev-locations'),
	__('Razliv', 'wpdev-locations'),
	__('Repino', 'wpdev-locations'),
	__('Saint Petersburg', 'wpdev-locations'),
	__('Sapërnyy', 'wpdev-locations'),
	__('Sestroretsk', 'wpdev-locations'),
	__('Shushary', 'wpdev-locations'),
	__('Shuvalovo', 'wpdev-locations'),
	__('Solnechnoye', 'wpdev-locations'),
	__('Sosnovaya Polyana', 'wpdev-locations'),
	__('Sosnovka', 'wpdev-locations'),
	__('Staraya Derevnya', 'wpdev-locations'),
	__("Strel'na", 'wpdev-locations'),
	__('Tarkhovka', 'wpdev-locations'),
	__('Tyarlevo', 'wpdev-locations'),
	__('Uritsk', 'wpdev-locations'),
	__('Ust’-Izhora', 'wpdev-locations'),
	__('Vasileostrovskiy Rayon', 'wpdev-locations'),
	__("Vasyl'evsky Ostrov", 'wpdev-locations'),
	__('Zelenogorsk', 'wpdev-locations'),
);
