<?php // phpcs:ignore - @generation-checksum RU-TAM-35
/**
 * State City List for TAM - RU.
 *
 * City count: 35
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TAM - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bokino', 'wpdev-locations'),
	__('Bondarskiy Rayon', 'wpdev-locations'),
	__('Donskoye', 'wpdev-locations'),
	__('Gavrilovka Vtoraya', 'wpdev-locations'),
	__('Goreloye', 'wpdev-locations'),
	__('Inzhavino', 'wpdev-locations'),
	__('Kirsanov', 'wpdev-locations'),
	__('Kirsanovskiy Rayon', 'wpdev-locations'),
	__('Komsomolets', 'wpdev-locations'),
	__('Kotovsk', 'wpdev-locations'),
	__('Michurinsk', 'wpdev-locations'),
	__('Mordovo', 'wpdev-locations'),
	__('Morshansk', 'wpdev-locations'),
	__('Muchkapskiy', 'wpdev-locations'),
	__('Novaya Lyada', 'wpdev-locations'),
	__('Novopokrovka', 'wpdev-locations'),
	__('Pervomayskiy', 'wpdev-locations'),
	__('Pichayevo', 'wpdev-locations'),
	__('Platonovka', 'wpdev-locations'),
	__('Pokrovo-Prigorodnoye', 'wpdev-locations'),
	__('Rasskazovo', 'wpdev-locations'),
	__('Rasskazovskiy Rayon', 'wpdev-locations'),
	__('Rzhaksa', 'wpdev-locations'),
	__('Sampurskiy Rayon', 'wpdev-locations'),
	__('Satinka', 'wpdev-locations'),
	__('Selezni', 'wpdev-locations'),
	__('Sosnovka', 'wpdev-locations'),
	__('Staroyur’yevo', 'wpdev-locations'),
	__('Tambov', 'wpdev-locations'),
	__('Tokarevskiy Rayon', 'wpdev-locations'),
	__('Uvarovo', 'wpdev-locations'),
	__('Zavoronezhskoye', 'wpdev-locations'),
	__('Zherdevka', 'wpdev-locations'),
	__('Znamenka', 'wpdev-locations'),
	__('Znamenskiy Rayon', 'wpdev-locations'),
);
