<?php // phpcs:ignore - @generation-checksum RU-TOM-30
/**
 * State City List for TOM - RU.
 *
 * City count: 30
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TOM - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aleksandrovskoye', 'wpdev-locations'),
	__('Asino', 'wpdev-locations'),
	__('Bakchar', 'wpdev-locations'),
	__('Belyy Yar', 'wpdev-locations'),
	__('Bogashevo', 'wpdev-locations'),
	__('Kaltay', 'wpdev-locations'),
	__('Kargasok', 'wpdev-locations'),
	__('Kedrovyy', 'wpdev-locations'),
	__('Kolpashevo', 'wpdev-locations'),
	__('Kozhevnikovo', 'wpdev-locations'),
	__('Krasnyy Yar', 'wpdev-locations'),
	__('Krivosheino', 'wpdev-locations'),
	__('Mel’nikovo', 'wpdev-locations'),
	__('Molchanovo', 'wpdev-locations'),
	__('Molchanovskiy Rayon', 'wpdev-locations'),
	__('Moryakovskiy Zaton', 'wpdev-locations'),
	__('Parabel’', 'wpdev-locations'),
	__('Pervomayskoye', 'wpdev-locations'),
	__('Podgornoye', 'wpdev-locations'),
	__('Samus’', 'wpdev-locations'),
	__('Seversk', 'wpdev-locations'),
	__('Strezhevoy', 'wpdev-locations'),
	__('Svetlyy', 'wpdev-locations'),
	__('Tegul’det', 'wpdev-locations'),
	__('Tegul’detskiy Rayon', 'wpdev-locations'),
	__('Timiryazevskoye', 'wpdev-locations'),
	__('Togur', 'wpdev-locations'),
	__('Tomsk', 'wpdev-locations'),
	__('Tomskiy Rayon', 'wpdev-locations'),
	__('Zyryanskoye', 'wpdev-locations'),
);
