<?php // phpcs:ignore - @generation-checksum RU-TUL-64
/**
 * State City List for TUL - RU.
 *
 * City count: 64
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TUL - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ageyevo', 'wpdev-locations'),
	__('Aleksin', 'wpdev-locations'),
	__('Aleksinskiy Rayon', 'wpdev-locations'),
	__('Arsen’yevo', 'wpdev-locations'),
	__('Barsuki', 'wpdev-locations'),
	__('Begichevskiy', 'wpdev-locations'),
	__('Belëv', 'wpdev-locations'),
	__('Bogoroditsk', 'wpdev-locations'),
	__('Bolokhovo', 'wpdev-locations'),
	__('Bol’shoye Skuratovo', 'wpdev-locations'),
	__('Borodinskiy', 'wpdev-locations'),
	__('Brusyanka', 'wpdev-locations'),
	__('Chekalin', 'wpdev-locations'),
	__('Cherepet’', 'wpdev-locations'),
	__('Chern’', 'wpdev-locations'),
	__('Donskoy', 'wpdev-locations'),
	__('Dubna', 'wpdev-locations'),
	__('Dubovka', 'wpdev-locations'),
	__('Gorelki', 'wpdev-locations'),
	__('Gritsovskiy', 'wpdev-locations'),
	__('Kamenetskiy', 'wpdev-locations'),
	__('Kazachka', 'wpdev-locations'),
	__('Khanino', 'wpdev-locations'),
	__('Kimovsk', 'wpdev-locations'),
	__('Kireyevsk', 'wpdev-locations'),
	__('Kosaya Gora', 'wpdev-locations'),
	__('Krapivna', 'wpdev-locations'),
	__('Kurkino', 'wpdev-locations'),
	__('Leninskiy', 'wpdev-locations'),
	__('Lomintsevskiy', 'wpdev-locations'),
	__('Mayskiy', 'wpdev-locations'),
	__('Mendeleyevskiy', 'wpdev-locations'),
	__('Novogurovskiy', 'wpdev-locations'),
	__('Novomoskovsk', 'wpdev-locations'),
	__('Odoyev', 'wpdev-locations'),
	__('Partizan', 'wpdev-locations'),
	__('Pervomayskiy', 'wpdev-locations'),
	__('Plavsk', 'wpdev-locations'),
	__('Podlesnyy', 'wpdev-locations'),
	__('Priupskiy', 'wpdev-locations'),
	__('Revyakino', 'wpdev-locations'),
	__('Rozhdestvenskiy', 'wpdev-locations'),
	__('Severo-Zadonsk', 'wpdev-locations'),
	__('Shchëkino', 'wpdev-locations'),
	__('Shvartsevskiy', 'wpdev-locations'),
	__('Skuratovskiy', 'wpdev-locations'),
	__('Slavniy', 'wpdev-locations'),
	__('Suvorov', 'wpdev-locations'),
	__('Suvorovskiy Rayon', 'wpdev-locations'),
	__('Tovarkovskiy', 'wpdev-locations'),
	__('Tula', 'wpdev-locations'),
	__('Tëplo-Ogarëvskiy Rayon', 'wpdev-locations'),
	__('Tëploye', 'wpdev-locations'),
	__('Uzlovaya', 'wpdev-locations'),
	__('Venevskiy Rayon', 'wpdev-locations'),
	__('Venëv', 'wpdev-locations'),
	__('Volovo', 'wpdev-locations'),
	__('Yasnogorsk', 'wpdev-locations'),
	__('Yasnogorskiy Rayon', 'wpdev-locations'),
	__('Yefremov', 'wpdev-locations'),
	__('Yepifan’', 'wpdev-locations'),
	__('Zaokskiy', 'wpdev-locations'),
	__('Zaokskiy Rayon', 'wpdev-locations'),
	__('Zhdankovskiy', 'wpdev-locations'),
);
