<?php // phpcs:ignore - @generation-checksum RU-TVE-89
/**
 * State City List for TVE - RU.
 *
 * City count: 89
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TVE - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Andreapol’', 'wpdev-locations'),
	__('Andreapol’skiy Rayon', 'wpdev-locations'),
	__('Belyy', 'wpdev-locations'),
	__('Belyy Gorodok', 'wpdev-locations'),
	__('Bel’skiy Rayon', 'wpdev-locations'),
	__('Berezayka', 'wpdev-locations'),
	__('Bernovo', 'wpdev-locations'),
	__('Bezhetsk', 'wpdev-locations'),
	__('Bezhetskiy Rayon', 'wpdev-locations'),
	__('Bologovskiy Rayon', 'wpdev-locations'),
	__('Bologoye', 'wpdev-locations'),
	__('Bologoye-4', 'wpdev-locations'),
	__('Emmaus', 'wpdev-locations'),
	__('Firovo', 'wpdev-locations'),
	__('Firovskiy Rayon', 'wpdev-locations'),
	__('Gorodnya', 'wpdev-locations'),
	__('Il’inskoye', 'wpdev-locations'),
	__('Izoplit', 'wpdev-locations'),
	__('Kalashnikovo', 'wpdev-locations'),
	__('Kalininskiy Rayon', 'wpdev-locations'),
	__('Kalyazin', 'wpdev-locations'),
	__('Kalyazinskiy Rayon', 'wpdev-locations'),
	__('Kashin', 'wpdev-locations'),
	__('Kashinskiy Rayon', 'wpdev-locations'),
	__('Kesova Gora', 'wpdev-locations'),
	__('Kesovogorskiy Rayon', 'wpdev-locations'),
	__('Kimrskiy Rayon', 'wpdev-locations'),
	__('Kimry', 'wpdev-locations'),
	__('Konakovo', 'wpdev-locations'),
	__('Konakovskiy Rayon', 'wpdev-locations'),
	__('Kozlovo', 'wpdev-locations'),
	__('Krasnokholmskiy Rayon', 'wpdev-locations'),
	__('Krasnomayskiy', 'wpdev-locations'),
	__('Krasnyy Kholm', 'wpdev-locations'),
	__('Kuvshinovo', 'wpdev-locations'),
	__('Kuvshinovskiy Rayon', 'wpdev-locations'),
	__('Kuzhenkino', 'wpdev-locations'),
	__('Lesnoy Rayon', 'wpdev-locations'),
	__('Lesnoye', 'wpdev-locations'),
	__('Likhoslavl’', 'wpdev-locations'),
	__('Likhoslavl’skiy Rayon', 'wpdev-locations'),
	__('Maksatikha', 'wpdev-locations'),
	__('Maksatikhinskiy Rayon', 'wpdev-locations'),
	__('Molokovo', 'wpdev-locations'),
	__('Nelidovo', 'wpdev-locations'),
	__('Novozavidovskiy', 'wpdev-locations'),
	__('Olenino', 'wpdev-locations'),
	__('Orsha', 'wpdev-locations'),
	__('Ostashkov', 'wpdev-locations'),
	__('Ostashkovskiy Rayon', 'wpdev-locations'),
	__('Peno', 'wpdev-locations'),
	__('Penovskiy Rayon', 'wpdev-locations'),
	__('Radchenko', 'wpdev-locations'),
	__('Rameshki', 'wpdev-locations'),
	__('Rameshkovskiy Rayon', 'wpdev-locations'),
	__('Redkino', 'wpdev-locations'),
	__('Rzhev', 'wpdev-locations'),
	__('Sakharovo', 'wpdev-locations'),
	__('Sandovo', 'wpdev-locations'),
	__('Sandovskiy Rayon', 'wpdev-locations'),
	__('Selishche', 'wpdev-locations'),
	__('Selizharovo', 'wpdev-locations'),
	__('Selizharovskiy Rayon', 'wpdev-locations'),
	__('Sonkovo', 'wpdev-locations'),
	__('Spirovo', 'wpdev-locations'),
	__('Spirovskiy Rayon', 'wpdev-locations'),
	__('Stantsia Staritsa', 'wpdev-locations'),
	__('Staraya Toropa', 'wpdev-locations'),
	__('Staritsa', 'wpdev-locations'),
	__('Staritskiy Rayon', 'wpdev-locations'),
	__('Toropets', 'wpdev-locations'),
	__('Toropetskiy Rayon', 'wpdev-locations'),
	__('Torzhok', 'wpdev-locations'),
	__('Torzhokskiy Rayon', 'wpdev-locations'),
	__('Tver', 'wpdev-locations'),
	__('Udomlya', 'wpdev-locations'),
	__('Vasil’yevskiy Mokh', 'wpdev-locations'),
	__('Velikooktyabr’skiy', 'wpdev-locations'),
	__('Ves’yegonsk', 'wpdev-locations'),
	__('Ves’yegonskiy Rayon', 'wpdev-locations'),
	__('Vydropuzhsk', 'wpdev-locations'),
	__('Vypolzovo', 'wpdev-locations'),
	__('Vyshnevolotskiy Rayon', 'wpdev-locations'),
	__('Vyshniy Volochëk', 'wpdev-locations'),
	__('Zapadnaya Dvina', 'wpdev-locations'),
	__('Zavidovo', 'wpdev-locations'),
	__('Zharkovskiy', 'wpdev-locations'),
	__('Zubtsov', 'wpdev-locations'),
	__('Zubtsovskiy Rayon', 'wpdev-locations'),
);
