<?php // phpcs:ignore - @generation-checksum RU-TYU-46
/**
 * State City List for TYU - RU.
 *
 * City count: 46
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TYU - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Abalak', 'wpdev-locations'),
	__('Abatskoye', 'wpdev-locations'),
	__('Antipino', 'wpdev-locations'),
	__('Armizonskiy Rayon', 'wpdev-locations'),
	__('Armizonskoye', 'wpdev-locations'),
	__('Aromashevo', 'wpdev-locations'),
	__('Berdyuzhskiy Rayon', 'wpdev-locations'),
	__('Bogandinskiy', 'wpdev-locations'),
	__('Borovskiy', 'wpdev-locations'),
	__('Chervishevo', 'wpdev-locations'),
	__('Golyshmanovo', 'wpdev-locations'),
	__('Golyshmanovskiy Rayon', 'wpdev-locations'),
	__('Irtyshskiy', 'wpdev-locations'),
	__('Isetskiy Rayon', 'wpdev-locations'),
	__('Isetskoye', 'wpdev-locations'),
	__('Ishim', 'wpdev-locations'),
	__('Ishimskiy Rayon', 'wpdev-locations'),
	__('Kazanskiy Rayon', 'wpdev-locations'),
	__('Kazanskoye', 'wpdev-locations'),
	__('Melioratorov', 'wpdev-locations'),
	__('Mendeleyevo', 'wpdev-locations'),
	__('Moskovskiy', 'wpdev-locations'),
	__('Nizhnyaya Tavda', 'wpdev-locations'),
	__('Novaya Zaimka', 'wpdev-locations'),
	__('Novoseleznëvo', 'wpdev-locations'),
	__('Omutinskiy', 'wpdev-locations'),
	__('Omutinskiy Rayon', 'wpdev-locations'),
	__('Onokhino', 'wpdev-locations'),
	__('Sladkovo', 'wpdev-locations'),
	__('Sladkovskiy Rayon', 'wpdev-locations'),
	__('Sumkino', 'wpdev-locations'),
	__('Tobol’sk', 'wpdev-locations'),
	__('Turtas', 'wpdev-locations'),
	__('Tyumen', 'wpdev-locations'),
	__('Uporovo', 'wpdev-locations'),
	__('Uporovskiy Rayon', 'wpdev-locations'),
	__('Uspenka', 'wpdev-locations'),
	__('Uvat', 'wpdev-locations'),
	__('Vagay', 'wpdev-locations'),
	__('Vagayskiy Rayon', 'wpdev-locations'),
	__('Vikulovo', 'wpdev-locations'),
	__('Vinzili', 'wpdev-locations'),
	__('Yalutorovsk', 'wpdev-locations'),
	__('Yarkovo', 'wpdev-locations'),
	__('Yurginskoye', 'wpdev-locations'),
	__('Zavodoukovsk', 'wpdev-locations'),
);
