<?php // phpcs:ignore - @generation-checksum RU-UD-36
/**
 * State City List for UD - RU.
 *
 * City count: 36
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for UD - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alnashi', 'wpdev-locations'),
	__('Balezino', 'wpdev-locations'),
	__('Debesy', 'wpdev-locations'),
	__('Fakel', 'wpdev-locations'),
	__('Glazov', 'wpdev-locations'),
	__('Grakhovo', 'wpdev-locations'),
	__('Igra', 'wpdev-locations'),
	__('Izhevsk', 'wpdev-locations'),
	__('Kama', 'wpdev-locations'),
	__('Kambarka', 'wpdev-locations'),
	__('Karakulino', 'wpdev-locations'),
	__('Karakulinskiy Rayon', 'wpdev-locations'),
	__('Kez', 'wpdev-locations'),
	__('Khokhryaki', 'wpdev-locations'),
	__('Kiyasovo', 'wpdev-locations'),
	__('Kiyasovskiy Rayon', 'wpdev-locations'),
	__('Kizner', 'wpdev-locations'),
	__('Krasnogorskoye', 'wpdev-locations'),
	__('Malaya Purga', 'wpdev-locations'),
	__('Malopurginskiy Rayon', 'wpdev-locations'),
	__('Mozhga', 'wpdev-locations'),
	__('Pirogovo', 'wpdev-locations'),
	__('Pudem', 'wpdev-locations'),
	__('Pychas', 'wpdev-locations'),
	__('Sarapul', 'wpdev-locations'),
	__('Sarapul’skiy Rayon', 'wpdev-locations'),
	__('Selty', 'wpdev-locations'),
	__('Sharkan', 'wpdev-locations'),
	__('Sigayevo', 'wpdev-locations'),
	__('Syumsi', 'wpdev-locations'),
	__('Uva', 'wpdev-locations'),
	__('Vavozh', 'wpdev-locations'),
	__('Votkinsk', 'wpdev-locations'),
	__('Yar', 'wpdev-locations'),
	__('Yukamenskoye', 'wpdev-locations'),
	__('Zav’yalovskiy Rayon', 'wpdev-locations'),
);
