<?php // phpcs:ignore - @generation-checksum RU-ULY-45
/**
 * State City List for ULY - RU.
 *
 * City count: 45
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ULY - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Barysh', 'wpdev-locations'),
	__('Bazarnyy Syzgan', 'wpdev-locations'),
	__('Cherdaklinskiy Rayon', 'wpdev-locations'),
	__('Cherdakly', 'wpdev-locations'),
	__('Chufarovo', 'wpdev-locations'),
	__('Dimitrovgrad', 'wpdev-locations'),
	__('Glotovka', 'wpdev-locations'),
	__('Ignatovka', 'wpdev-locations'),
	__('Imeni Vladimira Il’icha Lenina', 'wpdev-locations'),
	__('Inza', 'wpdev-locations'),
	__('Isheyevka', 'wpdev-locations'),
	__('Izmaylovo', 'wpdev-locations'),
	__('Kanadey', 'wpdev-locations'),
	__('Karsun', 'wpdev-locations'),
	__('Krasnyy Gulyay', 'wpdev-locations'),
	__('Kuzovatovo', 'wpdev-locations'),
	__('Mayna', 'wpdev-locations'),
	__('Maynskiy Rayon', 'wpdev-locations'),
	__('Mirnyy', 'wpdev-locations'),
	__('Mullovka', 'wpdev-locations'),
	__('Nikolayevka', 'wpdev-locations'),
	__('Novaya Malykla', 'wpdev-locations'),
	__('Novaya Mayna', 'wpdev-locations'),
	__('Novocheremshansk', 'wpdev-locations'),
	__('Novospasskoye', 'wpdev-locations'),
	__('Novoul’yanovsk', 'wpdev-locations'),
	__('Pavlovka', 'wpdev-locations'),
	__('Pavlovskiy Rayon', 'wpdev-locations'),
	__('Radishchevo', 'wpdev-locations'),
	__('Sengiley', 'wpdev-locations'),
	__('Silikatnyy', 'wpdev-locations'),
	__('Staraya Kulatka', 'wpdev-locations'),
	__('Staraya Mayna', 'wpdev-locations'),
	__('Starokulatkinskiy Rayon', 'wpdev-locations'),
	__('Starotimoshkino', 'wpdev-locations'),
	__('Surskoye', 'wpdev-locations'),
	__('Teren’gul’skiy Rayon', 'wpdev-locations'),
	__('Tsil’na', 'wpdev-locations'),
	__('Tsil’ninskiy Rayon', 'wpdev-locations'),
	__('Ulyanovsk', 'wpdev-locations'),
	__('Ulyanovskiy Rayon', 'wpdev-locations'),
	__('Undory', 'wpdev-locations'),
	__('Veshkayma', 'wpdev-locations'),
	__('Yazykovo', 'wpdev-locations'),
	__('Zhadovka', 'wpdev-locations'),
);
