<?php // phpcs:ignore - @generation-checksum RU-VLA-66
/**
 * State City List for VLA - RU.
 *
 * City count: 66
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for VLA - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aleksandrov', 'wpdev-locations'),
	__('Aleksandrovskiy Rayon', 'wpdev-locations'),
	__('Andreyevo', 'wpdev-locations'),
	__('Anopino', 'wpdev-locations'),
	__('Arsaki', 'wpdev-locations'),
	__('Balakirevo', 'wpdev-locations'),
	__('Bavleny', 'wpdev-locations'),
	__('Belaya Rechka', 'wpdev-locations'),
	__('Bogolyubovo', 'wpdev-locations'),
	__('Dobryatino', 'wpdev-locations'),
	__('Galitsy', 'wpdev-locations'),
	__('Golovino', 'wpdev-locations'),
	__('Gorokhovets', 'wpdev-locations'),
	__('Gusevskiy', 'wpdev-locations'),
	__('Gus’-Khrustal’nyy', 'wpdev-locations'),
	__('Imeni Vorovskogo', 'wpdev-locations'),
	__('Ivanishchi', 'wpdev-locations'),
	__('Kameshkovo', 'wpdev-locations'),
	__('Karabanovo', 'wpdev-locations'),
	__('Kideksha', 'wpdev-locations'),
	__('Kirzhach', 'wpdev-locations'),
	__('Kol’chugino', 'wpdev-locations'),
	__('Kol’chuginskiy Rayon', 'wpdev-locations'),
	__('Kommunar', 'wpdev-locations'),
	__('Kosterevo', 'wpdev-locations'),
	__('Kovrov', 'wpdev-locations'),
	__('Krasnaya Gorbatka', 'wpdev-locations'),
	__('Krasnyy Bogatyr’', 'wpdev-locations'),
	__('Krasnyy Oktyabr’', 'wpdev-locations'),
	__('Kurlovo', 'wpdev-locations'),
	__('Lakinsk', 'wpdev-locations'),
	__('Luknovo', 'wpdev-locations'),
	__('Melekhovo', 'wpdev-locations'),
	__('Melenki', 'wpdev-locations'),
	__('Melenkovskiy Rayon', 'wpdev-locations'),
	__('Mezinovskiy', 'wpdev-locations'),
	__('Mstera', 'wpdev-locations'),
	__('Murom', 'wpdev-locations'),
	__('Muromskiy Rayon', 'wpdev-locations'),
	__('Muromtsevo', 'wpdev-locations'),
	__('Nikologory', 'wpdev-locations'),
	__('Novki', 'wpdev-locations'),
	__('Novovyazniki', 'wpdev-locations'),
	__('Oktyabr’skiy', 'wpdev-locations'),
	__('Orgtrud', 'wpdev-locations'),
	__('Petushinskiy Rayon', 'wpdev-locations'),
	__('Petushki', 'wpdev-locations'),
	__('Pokrov', 'wpdev-locations'),
	__('Raduzhnyy', 'wpdev-locations'),
	__('Sobinka', 'wpdev-locations'),
	__('Sobinskiy Rayon', 'wpdev-locations'),
	__('Stavrovo', 'wpdev-locations'),
	__('Stepantsevo', 'wpdev-locations'),
	__('Strunino', 'wpdev-locations'),
	__('Sudogda', 'wpdev-locations'),
	__('Sudogodskiy Rayon', 'wpdev-locations'),
	__('Suzdal’', 'wpdev-locations'),
	__('Suzdal’skiy Rayon', 'wpdev-locations'),
	__('Urshel’skiy', 'wpdev-locations'),
	__('Velikodvorskiy', 'wpdev-locations'),
	__('Vladimir', 'wpdev-locations'),
	__('Vorsha', 'wpdev-locations'),
	__('Vyazniki', 'wpdev-locations'),
	__('Yur’yev-Pol’skiy', 'wpdev-locations'),
	__('Yur’yev-Pol’skiy Rayon', 'wpdev-locations'),
	__('Zolotkovo', 'wpdev-locations'),
);
