<?php // phpcs:ignore - @generation-checksum RU-YAN-24
/**
 * State City List for YAN - RU.
 *
 * City count: 24
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for YAN - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aksarka', 'wpdev-locations'),
	__('Gubkinskiy', 'wpdev-locations'),
	__('Kharp', 'wpdev-locations'),
	__('Korotchaevo', 'wpdev-locations'),
	__('Labytnangi', 'wpdev-locations'),
	__('Muravlenko', 'wpdev-locations'),
	__('Muzhi', 'wpdev-locations'),
	__('Mys-Kamennyy', 'wpdev-locations'),
	__('Nadym', 'wpdev-locations'),
	__('Nadymskiy Rayon', 'wpdev-locations'),
	__('Novyy Urengoy', 'wpdev-locations'),
	__('Noyabrsk', 'wpdev-locations'),
	__('Nyda', 'wpdev-locations'),
	__('Pangody', 'wpdev-locations'),
	__('Priural’skiy Rayon', 'wpdev-locations'),
	__('Purovskiy Rayon', 'wpdev-locations'),
	__('Purpe', 'wpdev-locations'),
	__('Salekhard', 'wpdev-locations'),
	__('Shuryshkarskiy Rayon', 'wpdev-locations'),
	__('Staryy Nadym', 'wpdev-locations'),
	__('Tarko-Sale', 'wpdev-locations'),
	__('Tazovskiy', 'wpdev-locations'),
	__('Urengoy', 'wpdev-locations'),
	__('Yar-Sale', 'wpdev-locations'),
);
