<?php // phpcs:ignore - @generation-checksum RU-YAR-52
/**
 * State City List for YAR - RU.
 *
 * City count: 52
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for YAR - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Berendeyevo', 'wpdev-locations'),
	__('Bol’shesel’skiy Rayon', 'wpdev-locations'),
	__('Bol’shoye Selo', 'wpdev-locations'),
	__('Borisoglebskiy', 'wpdev-locations'),
	__('Borisoglebskiy Rayon', 'wpdev-locations'),
	__('Borok', 'wpdev-locations'),
	__('Breytovo', 'wpdev-locations'),
	__('Breytovskiy Rayon', 'wpdev-locations'),
	__('Burmakino', 'wpdev-locations'),
	__('Danilov', 'wpdev-locations'),
	__('Danilovskiy Rayon', 'wpdev-locations'),
	__('Dubki', 'wpdev-locations'),
	__('Gavrilov-Yam', 'wpdev-locations'),
	__('Gavrilov-Yamskiy Rayon', 'wpdev-locations'),
	__('Ishnya', 'wpdev-locations'),
	__('Konstantinovskiy', 'wpdev-locations'),
	__('Krasnyy Profintern', 'wpdev-locations'),
	__('Krasnyye Tkachi', 'wpdev-locations'),
	__('Kukoboy', 'wpdev-locations'),
	__('Kurba', 'wpdev-locations'),
	__('Levashevo', 'wpdev-locations'),
	__('Lyubim', 'wpdev-locations'),
	__('Lyubimskiy Rayon', 'wpdev-locations'),
	__('Myshkin', 'wpdev-locations'),
	__('Myshkinskiy Rayon', 'wpdev-locations'),
	__('Nekouzskiy Rayon', 'wpdev-locations'),
	__('Nekrasovskiy Rayon', 'wpdev-locations'),
	__('Nekrasovskoye', 'wpdev-locations'),
	__('Novyy Nekouz', 'wpdev-locations'),
	__('Pereslavl’-Zalesskiy', 'wpdev-locations'),
	__('Pereslavskiy Rayon', 'wpdev-locations'),
	__('Pervomayskiy Rayon', 'wpdev-locations'),
	__('Pesochnoye', 'wpdev-locations'),
	__('Petrovsk', 'wpdev-locations'),
	__('Porech’ye-Rybnoye', 'wpdev-locations'),
	__('Poshekhonskiy Rayon', 'wpdev-locations'),
	__('Poshekhon’ye', 'wpdev-locations'),
	__('Prechistoye', 'wpdev-locations'),
	__('Rostov', 'wpdev-locations'),
	__('Rostovskiy Rayon', 'wpdev-locations'),
	__('Rybinsk', 'wpdev-locations'),
	__('Rybinskiy Rayon', 'wpdev-locations'),
	__('Semibratovo', 'wpdev-locations'),
	__('Sudoverf’', 'wpdev-locations'),
	__('Tunoshna', 'wpdev-locations'),
	__('Tutayev', 'wpdev-locations'),
	__('Tutayevskiy Rayon', 'wpdev-locations'),
	__('Uglich', 'wpdev-locations'),
	__('Uglichskiy Rayon', 'wpdev-locations'),
	__('Volga', 'wpdev-locations'),
	__('Yaroslavl', 'wpdev-locations'),
	__('Yaroslavskiy Rayon', 'wpdev-locations'),
);
