/**
 * @wpdev/create-wp-project — `doctorProject` health check.
 *
 * Phase 24 of plan.v3.md (24.9, 24.10). The installer's
 * `wpdev doctor` command runs this function and prints the
 * result. The doctor is the installer's "is this consumer
 * project healthy?" surface.
 *
 * The contract:
 *
 *   doctorProject(dir) → {
 *     ok: boolean,           // true iff errors.length === 0
 *     warnings: string[],    // non-fatal drift
 *     errors: string[],      // fatal — `wpdev update` recommended
 *   }
 *
 * SAFE contract: the function NEVER throws. A malformed
 * manifest is a `warnings.push("manifest unreadable: ...")`,
 * NOT a throw — the CLI shows the user the warning and
 * exits non-zero only when errors.length > 0. This is the
 * load-bearing property: the doctor is a passive observer,
 * not a fixer. The installer's auto-fix flow is `wpdev
 * update`, which has its own permission/dry-run semantics.
 *
 * Checks (one per documented drift category, all
 * fail-soft):
 *
 *  1. Manifest present. Missing → `errors.push("manifest
 *     missing")`. This is the only FATAL check that doesn't
 *     need a manifest to detect — every other check
 *     short-circuits on a missing manifest.
 *
 *  2. Every feature id in `manifest.features` is a known
 *     catalog id (per `getFeatureCatalog()`). Unknown ids →
 *     `errors.push("unknown feature: <id>")` (one per id).
 *     Drift: a project whose manifest was hand-edited with
 *     a typo'd feature id, OR a project generated by a
 *     NEWER kit that has a feature the OLD kit doesn't
 *     know about.
 *
 *  3. `manifest.kitVersion` is not NEWER than the installed
 *     kit's own version. A manifest newer than the running
 *     kit is a "the kit is older than the project" mismatch
 *     — the user should `wpdev update`. WARNING, not error:
 *     the project will still work for the features it uses,
 *     it just can't get updates. Message: "kit newer than
 *     installed deps — run wpdev update".
 *
 *  4. If `manifest.distMode === "vendored"`, legacy projects may
 *     still have framework source copies under `src/Core/`.
 *     Doctor warns if they look hand-edited or are present
 *     (recommend `wpdev update` to migrate to deps). The
 *     actual vendored dep install lives at vendor/wpdev/framework
 *     after composer install. Placeholder logic upgraded for
 *     the src/Core case (no heavy checksums in v3; migration
 *     is the supported cleanup path).
 */

import { existsSync } from "node:fs";
import { readFileSync } from "node:fs";
import * as path from "node:path";

import { readManifest, MANIFEST_SCHEMA } from "./manifest.js";
import { getFeatureCatalog } from "./features.js";
import { getDepVersions } from "./dep-versions.js";

/* -------------------------------------------------------------------- */
/* Constants                                                             */
/* -------------------------------------------------------------------- */

const VENDORED_FRAMEWORK_DIR = "vendor/wpdev/framework"; // legacy vendored layout (pre-deps); actual copies for old projects were under src/Core/

/* -------------------------------------------------------------------- */
/* Helpers                                                               */
/* -------------------------------------------------------------------- */

/**
 * Compare two semver strings numerically. Returns:
 *   negative if a < b,
 *   zero     if a === b,
 *   positive if a > b.
 *
 * Mirrors the `compareSemver` in `migrations/index.js` (and
 * the simpler local copy in `plan-update.js`). We don't
 * import either because the doctor's check is "is kitVersion
 * newer than the kit's own version?", a single comparison —
 * duplicating the 10-line helper is cheaper than the import
 * dance.
 *
 * @param {string} a
 * @param {string} b
 * @returns {number}
 */
function compareSemver(a, b) {
  const aParts = String(a)
    .split(".")
    .slice(0, 3)
    .map((n) => parseInt(n, 10) || 0);
  const bParts = String(b)
    .split(".")
    .slice(0, 3)
    .map((n) => parseInt(n, 10) || 0);
  for (let i = 0; i < 3; i++) {
    if (aParts[i] !== bParts[i]) return aParts[i] - bParts[i];
  }
  return 0;
}

/**
 * Resolve a file path relative to this module's directory.
 * Mirrors the helper in `plan-update.js` and
 * `migrations/index.js`. Needed to read the kit's OWN
 * package.json for the version comparison in check 3.
 */
function modulePath(...parts) {
  let here;
  if (typeof __dirname !== "undefined" && __dirname) {
    here = __dirname;
  } else if (
    process.argv[1] &&
    process.argv[1].endsWith("create-wp-project/src/doctor.js")
  ) {
    here = path.dirname(process.argv[1]);
  } else {
    here = path.join(process.cwd(), "packages/create-wp-project/src");
  }
  return path.join(here, ...parts);
}

/**
 * Read the installed kit's own version from its own
 * package.json. Returns "0.0.0" when the package.json is
 * missing or unparseable (e.g. the test runner inlined the
 * module). The fallback is intentionally NOT a throw — the
 * doctor is fail-soft.
 *
 * @returns {string}
 */
function readInstalledKitVersion() {
  try {
    const pkgPath = modulePath("..", "..", "..", "package.json");
    if (!existsSync(pkgPath)) return "0.0.0";
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
    return typeof pkg.version === "string" ? pkg.version : "0.0.0";
  } catch {
    return "0.0.0";
  }
}

/* -------------------------------------------------------------------- */
/* checkVendoredChecksum (placeholder)                                   */
/* -------------------------------------------------------------------- */

/**
 * Placeholder for the vendored framework checksum check.
 * The contract (per Phase 24.10) is:
 *  - The function exists and is invoked when the project
 *    is in `distMode: "vendored"`.
 *  - When the framework files are absent (the project
 *    hasn't scaffolded yet, or the vendored dir was
 *    deleted), the function is a no-op — `doctorProject`
 *    does not warn.
 *  - When the files ARE present, the function reads them
 *    and compares to a shipped manifest (Phase 25+). The
 *    placeholder returns `[]` (no warnings).
 *
 * Exported so the test can verify the wiring (the dispatch
 * in `doctorProject` calls THIS function), and so a future
 * phase can replace the body without touching the dispatch.
 *
 * @param {string} dir
 * @returns {string[]}  array of warning messages (empty = ok)
 */
export function checkVendoredChecksum(dir) {
  if (!dir || typeof dir !== "string") return [];
  const warnings = [];
  // Legacy vendored (pre-Phase 23): framework sources lived as
  // src/Core copies inside the project (not under the Composer
  // vendor/ path until after install + strauss). Presence of
  // these in a modern project is drift — recommend update.
  const legacyCore = path.join(dir, "src", "Core", "Plugin.php");
  if (existsSync(legacyCore)) {
    warnings.push(
      "Legacy vendored framework sources found under src/Core/. " +
        "Run `wpdev update` (or delete src/Core/ after confirming " +
        "your modules only use public WPDev APIs) to migrate to deps mode.",
    );
  }
  const frameworkDir = path.join(dir, VENDORED_FRAMEWORK_DIR);
  if (existsSync(frameworkDir)) {
    // Real installed copy under vendor (post composer). No checksum
    // validation in v3 baseline; the dep + composer.lock is source of
    // truth. Placeholder kept for forward compat.
    // (In a future version we could hash against a manifest.)
  }
  return warnings;
}

/* -------------------------------------------------------------------- */
/* doctorProject                                                          */
/* -------------------------------------------------------------------- */

/**
 * Run the doctor on a project rooted at `dir`. Returns
 * `{ok, warnings, errors}`. NEVER throws.
 *
 * @param {string} dir
 * @returns {{ ok: boolean, warnings: string[], errors: string[] }}
 */
export function doctorProject(dir) {
  const result = { ok: true, warnings: [], errors: [] };
  if (!dir || typeof dir !== "string") {
    result.errors.push("manifest missing");
    result.ok = false;
    return result;
  }

  // Check 1: manifest present.
  let manifest;
  try {
    manifest = readManifest(dir);
  } catch (error) {
    // Malformed manifest → warning (not error). The
    // installer's "broken manifest" UX is "show the user the
    // path + parser message, suggest `git checkout .` if
    // they didn't mean to edit it".
    result.warnings.push(
      `manifest unreadable: ${error && error.message ? error.message : String(error)}`,
    );
    return result;
  }
  if (!manifest) {
    result.errors.push("manifest missing");
    result.ok = false;
    return result;
  }

  // Check 1b: unsupported manifest schema.
  if (
    typeof manifest.schema === "number" &&
    manifest.schema !== MANIFEST_SCHEMA
  ) {
    result.errors.push(
      `unsupported manifest schema ${manifest.schema} — upgrade the kit before updating this project (expected schema ${MANIFEST_SCHEMA})`,
    );
  }

  // Check 2: unknown feature ids.
  const knownIds = new Set(getFeatureCatalog().map((f) => f.id));
  const features = (manifest && manifest.features) || {};
  for (const id of Object.keys(features)) {
    if (!knownIds.has(id)) {
      result.errors.push(`unknown feature: ${id}`);
    }
  }

  // Check 3: manifest.kitVersion vs installed kit's own version.
  // A manifest NEWER than the running kit is a warning. We
  // ALSO verify the dep registry is non-empty — if the
  // registry is empty (e.g. the kit's package.json was
  // missing), the check is a no-op (we can't compare).
  const installed = readInstalledKitVersion();
  const project =
    typeof manifest.kitVersion === "string" ? manifest.kitVersion : null;
  if (project && installed !== "0.0.0") {
    if (compareSemver(project, installed) > 0) {
      result.warnings.push(
        `project manifest kitVersion (${project}) is newer than the installed kit (${installed}) — run wpdev update`,
      );
    }
  }

  // Check 4: vendored framework checksum.
  if (manifest.distMode === "vendored") {
    const vendoredWarnings = checkVendoredChecksum(dir);
    for (const w of vendoredWarnings) {
      result.warnings.push(w);
    }
  }

  // The dep registry is consulted only to keep the dep-versions
  // module warm (caching the disk read). Reading it here also
  // surfaces a future "registry is empty" condition as a
  // warning if it ever fires — the kit's package.json
  // disappearance is an installation bug, not a user error.
  const registry = getDepVersions();
  if (registry.size === 0) {
    result.warnings.push(
      "dep registry is empty — the kit's own package.json/composer.json may be missing",
    );
  }

  result.ok = result.errors.length === 0;
  return result;
}
