<?php // phpcs:ignore - @generation-checksum DE-HH-37
/**
 * State City List for HH - DE.
 *
 * City count: 37
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for HH - DE.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alsterdorf', 'wpdev-locations'),
	__('Altona', 'wpdev-locations'),
	__('Barmbek-Nord', 'wpdev-locations'),
	__('Bergedorf', 'wpdev-locations'),
	__('Bergstedt', 'wpdev-locations'),
	__('Borgfelde', 'wpdev-locations'),
	__('Duvenstedt', 'wpdev-locations'),
	__('Eidelstedt', 'wpdev-locations'),
	__('Eimsbüttel', 'wpdev-locations'),
	__('Farmsen-Berne', 'wpdev-locations'),
	__('Fuhlsbüttel', 'wpdev-locations'),
	__('Hamburg', 'wpdev-locations'),
	__('Hamburg-Altstadt', 'wpdev-locations'),
	__('Hamburg-Mitte', 'wpdev-locations'),
	__('Hamburg-Nord', 'wpdev-locations'),
	__('Hammerbrook', 'wpdev-locations'),
	__('Harburg', 'wpdev-locations'),
	__('Hummelsbüttel', 'wpdev-locations'),
	__('Kleiner Grasbrook', 'wpdev-locations'),
	__('Langenhorn', 'wpdev-locations'),
	__('Lemsahl-Mellingstedt', 'wpdev-locations'),
	__('Lurup', 'wpdev-locations'),
	__('Marienthal', 'wpdev-locations'),
	__('Neustadt', 'wpdev-locations'),
	__('Ohlsdorf', 'wpdev-locations'),
	__('Ottensen', 'wpdev-locations'),
	__('Poppenbüttel', 'wpdev-locations'),
	__('Rothenburgsort', 'wpdev-locations'),
	__('Sasel', 'wpdev-locations'),
	__('St. Georg', 'wpdev-locations'),
	__('St. Pauli', 'wpdev-locations'),
	__('Steilshoop', 'wpdev-locations'),
	__('Stellingen', 'wpdev-locations'),
	__('Wandsbek', 'wpdev-locations'),
	__('Wellingsbüttel', 'wpdev-locations'),
	__('Winterhude', 'wpdev-locations'),
	__('Wohldorf-Ohlstedt', 'wpdev-locations'),
);
