<?php // phpcs:ignore - @generation-checksum DE-SL-60
/**
 * State City List for SL - DE.
 *
 * City count: 60
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SL - DE.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Beckingen', 'wpdev-locations'),
	__('Bexbach', 'wpdev-locations'),
	__('Blieskastel', 'wpdev-locations'),
	__('Bous', 'wpdev-locations'),
	__('Britten', 'wpdev-locations'),
	__('Dillingen', 'wpdev-locations'),
	__('Ensdorf', 'wpdev-locations'),
	__('Eppelborn', 'wpdev-locations'),
	__('Freisen', 'wpdev-locations'),
	__('Friedrichsthal', 'wpdev-locations'),
	__('Fürstenhausen', 'wpdev-locations'),
	__('Gersheim', 'wpdev-locations'),
	__('Großrosseln', 'wpdev-locations'),
	__('Hangard', 'wpdev-locations'),
	__('Heidstock', 'wpdev-locations'),
	__('Heusweiler', 'wpdev-locations'),
	__('Homburg', 'wpdev-locations'),
	__('Illingen', 'wpdev-locations'),
	__('Kirkel', 'wpdev-locations'),
	__('Kleinblittersdorf', 'wpdev-locations'),
	__('Lebach', 'wpdev-locations'),
	__('Losheim', 'wpdev-locations'),
	__('Ludweiler-Warndt', 'wpdev-locations'),
	__('Luisenthal', 'wpdev-locations'),
	__('Mainzweiler', 'wpdev-locations'),
	__('Marpingen', 'wpdev-locations'),
	__('Merchweiler', 'wpdev-locations'),
	__('Merzig', 'wpdev-locations'),
	__('Mettlach', 'wpdev-locations'),
	__('Nalbach', 'wpdev-locations'),
	__('Namborn', 'wpdev-locations'),
	__('Neunkirchen', 'wpdev-locations'),
	__('Nohfelden', 'wpdev-locations'),
	__('Nonnweiler', 'wpdev-locations'),
	__('Oberthal', 'wpdev-locations'),
	__('Orscholz', 'wpdev-locations'),
	__('Ottweiler', 'wpdev-locations'),
	__('Püttlingen', 'wpdev-locations'),
	__('Quierschied', 'wpdev-locations'),
	__('Riegelsberg', 'wpdev-locations'),
	__('Röchling-Höhe', 'wpdev-locations'),
	__('Saarbrücken', 'wpdev-locations'),
	__('Saarhölzbach', 'wpdev-locations'),
	__('Saarlouis', 'wpdev-locations'),
	__('Saarwellingen', 'wpdev-locations'),
	__('Sankt Ingbert', 'wpdev-locations'),
	__('Sankt Wendel', 'wpdev-locations'),
	__('Schiffweiler', 'wpdev-locations'),
	__('Schmelz', 'wpdev-locations'),
	__('Schwalbach', 'wpdev-locations'),
	__('Spiesen-Elversberg', 'wpdev-locations'),
	__('Sulzbach', 'wpdev-locations'),
	__('Tholey', 'wpdev-locations'),
	__('Völklingen', 'wpdev-locations'),
	__('Wadern', 'wpdev-locations'),
	__('Wadgassen', 'wpdev-locations'),
	__('Wallerfangen', 'wpdev-locations'),
	__('Weiskirchen', 'wpdev-locations'),
	__('Weiten', 'wpdev-locations'),
	__('Überherrn', 'wpdev-locations'),
);
