<?php // phpcs:ignore - @generation-checksum TR-01-17
/**
 * State City List for 01 - TR.
 *
 * City count: 17
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 01 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Adana', 'wpdev-locations'),
	__('Aladağ', 'wpdev-locations'),
	__('Bahçe', 'wpdev-locations'),
	__('Ceyhan', 'wpdev-locations'),
	__('Feke', 'wpdev-locations'),
	__('Karaisalı', 'wpdev-locations'),
	__('Karataş', 'wpdev-locations'),
	__('Kozan', 'wpdev-locations'),
	__('Pozantı', 'wpdev-locations'),
	__('Saimbeyli', 'wpdev-locations'),
	__('Sarıçam', 'wpdev-locations'),
	__('Seyhan', 'wpdev-locations'),
	__('Tufanbeyli', 'wpdev-locations'),
	__('Yumurtalık', 'wpdev-locations'),
	__('Yüreğir', 'wpdev-locations'),
	__('Çukurova', 'wpdev-locations'),
	__('İmamoğlu', 'wpdev-locations'),
);
