<?php // phpcs:ignore - @generation-checksum TR-02-11
/**
 * State City List for 02 - TR.
 *
 * City count: 11
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 02 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Adıyaman', 'wpdev-locations'),
	__('Aralık İlçesi', 'wpdev-locations'),
	__('Besni', 'wpdev-locations'),
	__('Gerger', 'wpdev-locations'),
	__('Gölbaşı', 'wpdev-locations'),
	__('Kâhta', 'wpdev-locations'),
	__('Merkez', 'wpdev-locations'),
	__('Samsat', 'wpdev-locations'),
	__('Sincik', 'wpdev-locations'),
	__('Tut', 'wpdev-locations'),
	__('Çelikhan', 'wpdev-locations'),
);
