<?php // phpcs:ignore - @generation-checksum TR-04-8
/**
 * State City List for 04 - TR.
 *
 * City count: 8
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 04 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ağrı', 'wpdev-locations'),
	__('Diyadin', 'wpdev-locations'),
	__('Doğubayazıt', 'wpdev-locations'),
	__('Eleşkirt', 'wpdev-locations'),
	__('Hamur', 'wpdev-locations'),
	__('Patnos', 'wpdev-locations'),
	__('Taşlıçay', 'wpdev-locations'),
	__('Tutak İlçesi', 'wpdev-locations'),
);
