<?php // phpcs:ignore - @generation-checksum TR-06-30
/**
 * State City List for 06 - TR.
 *
 * City count: 30
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 06 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akyurt', 'wpdev-locations'),
	__('Altpınar', 'wpdev-locations'),
	__('Altındağ', 'wpdev-locations'),
	__('Ankara', 'wpdev-locations'),
	__('Ayaş', 'wpdev-locations'),
	__('Bala İlçesi', 'wpdev-locations'),
	__('Batikent', 'wpdev-locations'),
	__('Beypazari', 'wpdev-locations'),
	__('Beypazarı', 'wpdev-locations'),
	__('Elmadağ', 'wpdev-locations'),
	__('Etimesgut İlçesi', 'wpdev-locations'),
	__('Evren', 'wpdev-locations'),
	__('Gölbaşı', 'wpdev-locations'),
	__('Güdül', 'wpdev-locations'),
	__('Haymana', 'wpdev-locations'),
	__('Kahramankazan', 'wpdev-locations'),
	__('Kalecik', 'wpdev-locations'),
	__('Kazan', 'wpdev-locations'),
	__('Keçiören', 'wpdev-locations'),
	__('Kızılcahamam', 'wpdev-locations'),
	__('Mamak İlçesi', 'wpdev-locations'),
	__('Nallıhan', 'wpdev-locations'),
	__('Polatlı', 'wpdev-locations'),
	__('Pursaklar', 'wpdev-locations'),
	__('Sincan İlçesi', 'wpdev-locations'),
	__('Yenimahalle', 'wpdev-locations'),
	__('Çamlıdere', 'wpdev-locations'),
	__('Çankaya', 'wpdev-locations'),
	__('Çubuk', 'wpdev-locations'),
	__('Şereflikoçhisar', 'wpdev-locations'),
);
