<?php // phpcs:ignore - @generation-checksum TR-07-37
/**
 * State City List for 07 - TR.
 *
 * City count: 37
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 07 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akseki', 'wpdev-locations'),
	__('Aksu', 'wpdev-locations'),
	__('Alanya', 'wpdev-locations'),
	__('Antalya', 'wpdev-locations'),
	__('Avsallar', 'wpdev-locations'),
	__('Belek', 'wpdev-locations'),
	__('Beykonak', 'wpdev-locations'),
	__('Boğazkent', 'wpdev-locations'),
	__('Demre', 'wpdev-locations'),
	__('Döşemealtı İlçesi', 'wpdev-locations'),
	__('Eksere', 'wpdev-locations'),
	__('Elmalı', 'wpdev-locations'),
	__('Evrenseki', 'wpdev-locations'),
	__('Finike', 'wpdev-locations'),
	__('Gazipaşa', 'wpdev-locations'),
	__('Göynük', 'wpdev-locations'),
	__('Gündoğmuş İlçesi', 'wpdev-locations'),
	__('Kalkan', 'wpdev-locations'),
	__('Kaş', 'wpdev-locations'),
	__('Kemer', 'wpdev-locations'),
	__('Kepez İlçesi', 'wpdev-locations'),
	__('Konyaaltı', 'wpdev-locations'),
	__('Korkuteli', 'wpdev-locations'),
	__('Kumköy', 'wpdev-locations'),
	__('Kumluca', 'wpdev-locations'),
	__('Kızılağaç', 'wpdev-locations'),
	__('Mahmutlar', 'wpdev-locations'),
	__('Manavgat', 'wpdev-locations'),
	__('Muratpaşa', 'wpdev-locations'),
	__('Okurcalar', 'wpdev-locations'),
	__('Payallar', 'wpdev-locations'),
	__('Serik', 'wpdev-locations'),
	__('Side', 'wpdev-locations'),
	__('Tekirova', 'wpdev-locations'),
	__('Turunçova', 'wpdev-locations'),
	__('Türkler', 'wpdev-locations'),
	__('İbradı', 'wpdev-locations'),
);
