<?php // phpcs:ignore - @generation-checksum TR-08-10
/**
 * State City List for 08 - TR.
 *
 * City count: 10
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 08 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ardanuç', 'wpdev-locations'),
	__('Arhavi', 'wpdev-locations'),
	__('Artvin', 'wpdev-locations'),
	__('Borçka', 'wpdev-locations'),
	__('Hopa', 'wpdev-locations'),
	__('Kemalpaşa', 'wpdev-locations'),
	__('Murgul', 'wpdev-locations'),
	__('Seyitler', 'wpdev-locations'),
	__('Yusufeli', 'wpdev-locations'),
	__('Şavşat', 'wpdev-locations'),
);
