<?php // phpcs:ignore - @generation-checksum TR-11-11
/**
 * State City List for 11 - TR.
 *
 * City count: 11
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 11 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bilecik', 'wpdev-locations'),
	__('Bozüyük', 'wpdev-locations'),
	__('Dodurga', 'wpdev-locations'),
	__('Gölpazarı', 'wpdev-locations'),
	__('Küplü', 'wpdev-locations'),
	__('Osmaneli', 'wpdev-locations'),
	__('Pazaryeri', 'wpdev-locations'),
	__('Söğüt İlçesi', 'wpdev-locations'),
	__('Vezirhan', 'wpdev-locations'),
	__('Yenipazar', 'wpdev-locations'),
	__('İnhisar', 'wpdev-locations'),
);
