<?php // phpcs:ignore - @generation-checksum TR-15-14
/**
 * State City List for 15 - TR.
 *
 * City count: 14
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 15 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Altınyayla', 'wpdev-locations'),
	__('Ağlasun', 'wpdev-locations'),
	__('Bucak', 'wpdev-locations'),
	__('Burdur', 'wpdev-locations'),
	__('Gölhisar', 'wpdev-locations'),
	__('Karamanlı', 'wpdev-locations'),
	__('Kemer', 'wpdev-locations'),
	__('Kocaaliler', 'wpdev-locations'),
	__('Kızılkaya', 'wpdev-locations'),
	__('Merkez', 'wpdev-locations'),
	__('Tefenni', 'wpdev-locations'),
	__('Yeşilova', 'wpdev-locations'),
	__('Çavdır İlçesi', 'wpdev-locations'),
	__('Çeltikçi İlçesi', 'wpdev-locations'),
);
