<?php // phpcs:ignore - @generation-checksum TR-16-39
/**
 * State City List for 16 - TR.
 *
 * City count: 39
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 16 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alanyurt', 'wpdev-locations'),
	__('Balarim', 'wpdev-locations'),
	__('Boyalıca', 'wpdev-locations'),
	__('Bursa', 'wpdev-locations'),
	__('Büyükorhan İlçesi', 'wpdev-locations'),
	__('Cerrah', 'wpdev-locations'),
	__('Demirtaş', 'wpdev-locations'),
	__('Elbeyli', 'wpdev-locations'),
	__('Gemlik', 'wpdev-locations'),
	__('Gürsu', 'wpdev-locations'),
	__('Hamzabey', 'wpdev-locations'),
	__('Harmancık İlçesi', 'wpdev-locations'),
	__('Karacabey', 'wpdev-locations'),
	__('Karıncalı', 'wpdev-locations'),
	__('Keles', 'wpdev-locations'),
	__('Kestel', 'wpdev-locations'),
	__('Kirazlı', 'wpdev-locations'),
	__('Kurşunlu', 'wpdev-locations'),
	__('Küçükkumla', 'wpdev-locations'),
	__('Mudanya', 'wpdev-locations'),
	__('Mustafakemalpaşa', 'wpdev-locations'),
	__('Narlıca', 'wpdev-locations'),
	__('Nilüfer', 'wpdev-locations'),
	__('Orhaneli', 'wpdev-locations'),
	__('Orhangazi', 'wpdev-locations'),
	__('Osmangazi', 'wpdev-locations'),
	__('Sölöz', 'wpdev-locations'),
	__('Tacir', 'wpdev-locations'),
	__('Tahtaköprü', 'wpdev-locations'),
	__('Tatkavaklı', 'wpdev-locations'),
	__('Umurbey', 'wpdev-locations'),
	__('Yenice', 'wpdev-locations'),
	__('Yeniköy', 'wpdev-locations'),
	__('Yenişehir', 'wpdev-locations'),
	__('Yıldırım İlçesi', 'wpdev-locations'),
	__('Çakırca', 'wpdev-locations'),
	__('Çakırlı', 'wpdev-locations'),
	__('İnegol', 'wpdev-locations'),
	__('İznik', 'wpdev-locations'),
);
