<?php // phpcs:ignore - @generation-checksum TR-20-24
/**
 * State City List for 20 - TR.
 *
 * City count: 24
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 20 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Acıpayam', 'wpdev-locations'),
	__('Akkent', 'wpdev-locations'),
	__('Akköy', 'wpdev-locations'),
	__('Babadağ', 'wpdev-locations'),
	__('Baklan', 'wpdev-locations'),
	__('Bekilli', 'wpdev-locations'),
	__('Beyağaç İlçesi', 'wpdev-locations'),
	__('Bozkurt', 'wpdev-locations'),
	__('Buldan', 'wpdev-locations'),
	__('Denizli', 'wpdev-locations'),
	__('Gözler', 'wpdev-locations'),
	__('Güney İlçesi', 'wpdev-locations'),
	__('Honaz', 'wpdev-locations'),
	__('Kale', 'wpdev-locations'),
	__('Merkezefendi', 'wpdev-locations'),
	__('Nikfer', 'wpdev-locations'),
	__('Pamukkale', 'wpdev-locations'),
	__('Sarayköy', 'wpdev-locations'),
	__('Serinhisar', 'wpdev-locations'),
	__('Tavas', 'wpdev-locations'),
	__('Çal İlçesi', 'wpdev-locations'),
	__('Çameli İlçesi', 'wpdev-locations'),
	__('Çardak', 'wpdev-locations'),
	__('Çivril', 'wpdev-locations'),
);
