<?php // phpcs:ignore - @generation-checksum TR-23-13
/**
 * State City List for 23 - TR.
 *
 * City count: 13
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 23 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Arıcak', 'wpdev-locations'),
	__('Ağın', 'wpdev-locations'),
	__('Baskil', 'wpdev-locations'),
	__('Elazığ', 'wpdev-locations'),
	__('Karakoçan', 'wpdev-locations'),
	__('Karakoçan / Elazığ', 'wpdev-locations'),
	__('Keban', 'wpdev-locations'),
	__('Kovancılar', 'wpdev-locations'),
	__('Maden İlçesi', 'wpdev-locations'),
	__('Merkez', 'wpdev-locations'),
	__('Palu', 'wpdev-locations'),
	__('Sivrice', 'wpdev-locations'),
	__('Turluk', 'wpdev-locations'),
);
