<?php // phpcs:ignore - @generation-checksum TR-25-22
/**
 * State City List for 25 - TR.
 *
 * City count: 22
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 25 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aziziye', 'wpdev-locations'),
	__('Aşkale', 'wpdev-locations'),
	__('Erzurum', 'wpdev-locations'),
	__('Horasan', 'wpdev-locations'),
	__('Hınıs', 'wpdev-locations'),
	__('Ilıca', 'wpdev-locations'),
	__('Karayazı', 'wpdev-locations'),
	__('Karaçoban', 'wpdev-locations'),
	__('Köprüköy İlçesi', 'wpdev-locations'),
	__('Narman', 'wpdev-locations'),
	__('Oltu', 'wpdev-locations'),
	__('Olur', 'wpdev-locations'),
	__('Palandöken', 'wpdev-locations'),
	__('Pasinler', 'wpdev-locations'),
	__('Pazaryolu', 'wpdev-locations'),
	__('Tekman', 'wpdev-locations'),
	__('Tortum', 'wpdev-locations'),
	__('Uzundere', 'wpdev-locations'),
	__('Yakutiye', 'wpdev-locations'),
	__('Çat İlçesi', 'wpdev-locations'),
	__('İspir', 'wpdev-locations'),
	__('Şenkaya', 'wpdev-locations'),
);
