<?php // phpcs:ignore - @generation-checksum TR-26-18
/**
 * State City List for 26 - TR.
 *
 * City count: 18
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 26 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alpu', 'wpdev-locations'),
	__('Beylikova', 'wpdev-locations'),
	__('Bozan', 'wpdev-locations'),
	__('Eskişehir', 'wpdev-locations'),
	__('Günyüzü İlçesi', 'wpdev-locations'),
	__('Han', 'wpdev-locations'),
	__('Kırka', 'wpdev-locations'),
	__('Mahmudiye İlçesi', 'wpdev-locations'),
	__('Mihalgazi', 'wpdev-locations'),
	__('Mihalıçcık İlçesi', 'wpdev-locations'),
	__('Odunpazarı', 'wpdev-locations'),
	__('Sarıcakaya İlçesi', 'wpdev-locations'),
	__('Sevinç', 'wpdev-locations'),
	__('Seyitgazi', 'wpdev-locations'),
	__('Sivrihisar', 'wpdev-locations'),
	__('Tepebaşı', 'wpdev-locations'),
	__('Çifteler', 'wpdev-locations'),
	__('İnönü', 'wpdev-locations'),
);
