<?php // phpcs:ignore - @generation-checksum TR-27-15
/**
 * State City List for 27 - TR.
 *
 * City count: 15
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 27 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Araban', 'wpdev-locations'),
	__('Doğanpınar', 'wpdev-locations'),
	__('Gaziantep', 'wpdev-locations'),
	__('Karkamış', 'wpdev-locations'),
	__('Nizip', 'wpdev-locations'),
	__('Nurdağı', 'wpdev-locations'),
	__('Oğuzeli', 'wpdev-locations'),
	__('Sekili', 'wpdev-locations'),
	__('Uluyatır', 'wpdev-locations'),
	__('Yavuzeli', 'wpdev-locations'),
	__('Yeşildere', 'wpdev-locations'),
	__('İkizce', 'wpdev-locations'),
	__('İslahiye İlçesi', 'wpdev-locations'),
	__('Şahinbey İlçesi', 'wpdev-locations'),
	__('Şehitkamil', 'wpdev-locations'),
);
