<?php // phpcs:ignore - @generation-checksum TR-30-6
/**
 * State City List for 30 - TR.
 *
 * City count: 6
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 30 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Hakkâri', 'wpdev-locations'),
	__('Karsani', 'wpdev-locations'),
	__('Yüksekova', 'wpdev-locations'),
	__('Çukurca', 'wpdev-locations'),
	__('Şemdinli', 'wpdev-locations'),
	__('Şemdinni İlçesi', 'wpdev-locations'),
);
