<?php // phpcs:ignore - @generation-checksum TR-31-40
/**
 * State City List for 31 - TR.
 *
 * City count: 40
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 31 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Altınözü', 'wpdev-locations'),
	__('Anayazı', 'wpdev-locations'),
	__('Antakya', 'wpdev-locations'),
	__('Arsuz', 'wpdev-locations'),
	__('Açıkdere', 'wpdev-locations'),
	__('Aşağı Karafakılı', 'wpdev-locations'),
	__('Aşağıokçular', 'wpdev-locations'),
	__('Balıklıdere', 'wpdev-locations'),
	__('Belen', 'wpdev-locations'),
	__('Boynuyoğun', 'wpdev-locations'),
	__('Büyük Dalyan', 'wpdev-locations'),
	__('Büyükçat', 'wpdev-locations'),
	__('Defne', 'wpdev-locations'),
	__('Denizciler', 'wpdev-locations'),
	__('Dursunlu', 'wpdev-locations'),
	__('Dörtyol', 'wpdev-locations'),
	__('Erzin', 'wpdev-locations'),
	__('Gümüşgöze', 'wpdev-locations'),
	__('Günyazı', 'wpdev-locations'),
	__('Hacıpaşa', 'wpdev-locations'),
	__('Hassa', 'wpdev-locations'),
	__('Karasüleymanlı', 'wpdev-locations'),
	__('Kastal', 'wpdev-locations'),
	__('Kumlu İlçesi', 'wpdev-locations'),
	__('Kuzeytepe', 'wpdev-locations'),
	__('Kırıkhan', 'wpdev-locations'),
	__('Kızkalesi', 'wpdev-locations'),
	__('Kışlak', 'wpdev-locations'),
	__('Mahmutlar', 'wpdev-locations'),
	__('Payas', 'wpdev-locations'),
	__('Reyhanlı', 'wpdev-locations'),
	__('Samankaya', 'wpdev-locations'),
	__('Serinyol', 'wpdev-locations'),
	__('Tepehan', 'wpdev-locations'),
	__('Toygarlı', 'wpdev-locations'),
	__('Uzunbağ', 'wpdev-locations'),
	__('Uzunkavak', 'wpdev-locations'),
	__('Yayladağı', 'wpdev-locations'),
	__('Çırtıman', 'wpdev-locations'),
	__('İskenderun', 'wpdev-locations'),
);
