<?php // phpcs:ignore - @generation-checksum TR-32-15
/**
 * State City List for 32 - TR.
 *
 * City count: 15
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 32 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aksu', 'wpdev-locations'),
	__('Anamas', 'wpdev-locations'),
	__('Atabey', 'wpdev-locations'),
	__('Eğirdir', 'wpdev-locations'),
	__('Gelendost', 'wpdev-locations'),
	__('Gönen', 'wpdev-locations'),
	__('Isparta', 'wpdev-locations'),
	__('Keçiborlu', 'wpdev-locations'),
	__('Pavlu Cebel', 'wpdev-locations'),
	__('Senirkent', 'wpdev-locations'),
	__('Sütçüler İlçesi', 'wpdev-locations'),
	__('Uluborlu', 'wpdev-locations'),
	__('Yalvaç', 'wpdev-locations'),
	__('Yenişarbademli', 'wpdev-locations'),
	__('Şarkîkaraağaç', 'wpdev-locations'),
);
