<?php // phpcs:ignore - @generation-checksum TR-34-40
/**
 * State City List for 34 - TR.
 *
 * City count: 40
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 34 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Adalar', 'wpdev-locations'),
	__('Arnavutköy', 'wpdev-locations'),
	__('Ataşehir', 'wpdev-locations'),
	__('Avcılar', 'wpdev-locations'),
	__('Bahçelievler', 'wpdev-locations'),
	__('Bakırköy', 'wpdev-locations'),
	__('Bayrampaşa', 'wpdev-locations'),
	__('Bağcılar', 'wpdev-locations'),
	__('Başakşehir', 'wpdev-locations'),
	__('Beykoz', 'wpdev-locations'),
	__('Beylikdüzü', 'wpdev-locations'),
	__('Beyoğlu', 'wpdev-locations'),
	__('Beşiktaş', 'wpdev-locations'),
	__('Büyükçekmece', 'wpdev-locations'),
	__('Eminönü', 'wpdev-locations'),
	__('Esenler', 'wpdev-locations'),
	__('Esenyurt', 'wpdev-locations'),
	__('Eyüpsultan', 'wpdev-locations'),
	__('Fatih', 'wpdev-locations'),
	__('Gaziosmanpaşa', 'wpdev-locations'),
	__('Güngören', 'wpdev-locations'),
	__('Kadıköy', 'wpdev-locations'),
	__('Kartal', 'wpdev-locations'),
	__('Kâğıthane', 'wpdev-locations'),
	__('Küçükçekmece', 'wpdev-locations'),
	__('Maltepe', 'wpdev-locations'),
	__('Pendik', 'wpdev-locations'),
	__('Sancaktepe', 'wpdev-locations'),
	__('Sarıyer', 'wpdev-locations'),
	__('Silivri', 'wpdev-locations'),
	__('Sultanbeyli', 'wpdev-locations'),
	__('Sultangazi', 'wpdev-locations'),
	__('Tuzla', 'wpdev-locations'),
	__('Umraniye', 'wpdev-locations'),
	__('Zeytinburnu', 'wpdev-locations'),
	__('Çatalca', 'wpdev-locations'),
	__('Çekmeköy', 'wpdev-locations'),
	__('Üsküdar', 'wpdev-locations'),
	__('Şile', 'wpdev-locations'),
	__('Şişli', 'wpdev-locations'),
);
