<?php // phpcs:ignore - @generation-checksum TR-39-9
/**
 * State City List for 39 - TR.
 *
 * City count: 9
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 39 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Babaeski', 'wpdev-locations'),
	__('Demirköy İlçesi', 'wpdev-locations'),
	__('Kofçaz', 'wpdev-locations'),
	__('Kırklareli', 'wpdev-locations'),
	__('Lüleburgaz İlçesi', 'wpdev-locations'),
	__('Pehlivanköy', 'wpdev-locations'),
	__('Pınarhisar', 'wpdev-locations'),
	__('Vize', 'wpdev-locations'),
	__('Üsküp', 'wpdev-locations'),
);
