<?php // phpcs:ignore - @generation-checksum TR-44-14
/**
 * State City List for 44 - TR.
 *
 * City count: 14
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 44 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akçadağ', 'wpdev-locations'),
	__('Arapgir', 'wpdev-locations'),
	__('Arguvan', 'wpdev-locations'),
	__('Battalgazi', 'wpdev-locations'),
	__('Darende', 'wpdev-locations'),
	__('Doğanyol', 'wpdev-locations'),
	__('Doğanşehir', 'wpdev-locations'),
	__('Hekimhan', 'wpdev-locations'),
	__('Kale', 'wpdev-locations'),
	__('Kuluncak', 'wpdev-locations'),
	__('Malatya', 'wpdev-locations'),
	__('Pütürge', 'wpdev-locations'),
	__('Yazıhan', 'wpdev-locations'),
	__('Yeşilyurt', 'wpdev-locations'),
);
