<?php // phpcs:ignore - @generation-checksum TR-46-14
/**
 * State City List for 46 - TR.
 *
 * City count: 14
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 46 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Afşin', 'wpdev-locations'),
	__('Andırın', 'wpdev-locations'),
	__('Celeyke', 'wpdev-locations'),
	__('Dulkadiroğlu', 'wpdev-locations'),
	__('Ekinözü İlçesi', 'wpdev-locations'),
	__('Elbistan', 'wpdev-locations'),
	__('Göksun', 'wpdev-locations'),
	__('Kahramanmaraş', 'wpdev-locations'),
	__('Nurhak', 'wpdev-locations'),
	__('Onikişubat', 'wpdev-locations'),
	__('Pazarcık', 'wpdev-locations'),
	__('Süleymanlı', 'wpdev-locations'),
	__('Türkoğlu İlçesi', 'wpdev-locations'),
	__('Çağlayancerit', 'wpdev-locations'),
);
