<?php // phpcs:ignore - @generation-checksum TR-47-64
/**
 * State City List for 47 - TR.
 *
 * City count: 64
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 47 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Acırlı', 'wpdev-locations'),
	__('Akarsu', 'wpdev-locations'),
	__('Alakamış', 'wpdev-locations'),
	__('Aran', 'wpdev-locations'),
	__('Artuklu', 'wpdev-locations'),
	__('Avine', 'wpdev-locations'),
	__('Barıştepe', 'wpdev-locations'),
	__('Bağlıca', 'wpdev-locations'),
	__('Başkavak', 'wpdev-locations'),
	__('Cinatamiho', 'wpdev-locations'),
	__('Dara', 'wpdev-locations'),
	__('Dargeçit', 'wpdev-locations'),
	__('Dereyanı', 'wpdev-locations'),
	__('Derik İlçesi', 'wpdev-locations'),
	__('Duruca', 'wpdev-locations'),
	__('Ebish', 'wpdev-locations'),
	__('Eymirli', 'wpdev-locations'),
	__('Eşme', 'wpdev-locations'),
	__('Gelinkaya', 'wpdev-locations'),
	__('Gyundyukoru', 'wpdev-locations'),
	__('Gülveren', 'wpdev-locations'),
	__('Haberli', 'wpdev-locations'),
	__('Kabala', 'wpdev-locations'),
	__('Karalar', 'wpdev-locations'),
	__('Kavsan', 'wpdev-locations'),
	__('Kayalıpınar', 'wpdev-locations'),
	__('Kaynakkaya', 'wpdev-locations'),
	__('Kindirip', 'wpdev-locations'),
	__('Kumlu', 'wpdev-locations'),
	__('Kutlubey', 'wpdev-locations'),
	__('Kılavuz', 'wpdev-locations'),
	__('Kızıltepe', 'wpdev-locations'),
	__('Mardin', 'wpdev-locations'),
	__('Mardin Merkez', 'wpdev-locations'),
	__('Mazıdağı', 'wpdev-locations'),
	__('Midyat', 'wpdev-locations'),
	__('Nusaybin', 'wpdev-locations'),
	__('Ortaca', 'wpdev-locations'),
	__('Ortaköy', 'wpdev-locations'),
	__('Oyalı', 'wpdev-locations'),
	__('Pınardere', 'wpdev-locations'),
	__('Reshidi', 'wpdev-locations'),
	__('Savur', 'wpdev-locations'),
	__('Selah', 'wpdev-locations'),
	__('Seri', 'wpdev-locations'),
	__('Serkan', 'wpdev-locations'),
	__('Sivrice', 'wpdev-locations'),
	__('Teffi', 'wpdev-locations'),
	__('Telminar', 'wpdev-locations'),
	__('Tepealtı', 'wpdev-locations'),
	__('Toptepe', 'wpdev-locations'),
	__('Yaylı', 'wpdev-locations'),
	__('Yayvantepe', 'wpdev-locations'),
	__('Yeşilalan', 'wpdev-locations'),
	__('Yeşilli', 'wpdev-locations'),
	__('Yolbaşı', 'wpdev-locations'),
	__('Çalpınar', 'wpdev-locations'),
	__('Çavuşlu', 'wpdev-locations'),
	__('Çınaraltı', 'wpdev-locations'),
	__('Çıplak', 'wpdev-locations'),
	__('Ömerli', 'wpdev-locations'),
	__('Özbek', 'wpdev-locations'),
	__('Şenocak', 'wpdev-locations'),
	__('Şenyurt', 'wpdev-locations'),
);
