<?php // phpcs:ignore - @generation-checksum TR-48-26
/**
 * State City List for 48 - TR.
 *
 * City count: 26
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 48 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bayır', 'wpdev-locations'),
	__('Bodrum', 'wpdev-locations'),
	__('Bozarmut', 'wpdev-locations'),
	__('Dalaman', 'wpdev-locations'),
	__('Dalyan', 'wpdev-locations'),
	__('Datça', 'wpdev-locations'),
	__('Fethiye', 'wpdev-locations'),
	__('Göcek', 'wpdev-locations'),
	__('Güvercinlik', 'wpdev-locations'),
	__('Kargı', 'wpdev-locations'),
	__('Kavaklıdere', 'wpdev-locations'),
	__('Köyceğiz İlçesi', 'wpdev-locations'),
	__('Marmaris', 'wpdev-locations'),
	__('Menteşe', 'wpdev-locations'),
	__('Milas', 'wpdev-locations'),
	__('Muğla', 'wpdev-locations'),
	__('Ortaca', 'wpdev-locations'),
	__('Sarigerme', 'wpdev-locations'),
	__('Seydikemer', 'wpdev-locations'),
	__('Turgut', 'wpdev-locations'),
	__('Turgutreis', 'wpdev-locations'),
	__('Ula', 'wpdev-locations'),
	__('Yalıkavak', 'wpdev-locations'),
	__('Yaniklar', 'wpdev-locations'),
	__('Yatağan', 'wpdev-locations'),
	__('Ölüdeniz', 'wpdev-locations'),
);
