<?php // phpcs:ignore - @generation-checksum TR-49-7
/**
 * State City List for 49 - TR.
 *
 * City count: 7
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 49 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bulanık', 'wpdev-locations'),
	__('Hasköy', 'wpdev-locations'),
	__('Korkut', 'wpdev-locations'),
	__('Malazgirt', 'wpdev-locations'),
	__('Merkez', 'wpdev-locations'),
	__('Muş', 'wpdev-locations'),
	__('Varto', 'wpdev-locations'),
);
