<?php // phpcs:ignore - @generation-checksum TR-50-10
/**
 * State City List for 50 - TR.
 *
 * City count: 10
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 50 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Acıgöl', 'wpdev-locations'),
	__('Avanos', 'wpdev-locations'),
	__('Derinkuyu', 'wpdev-locations'),
	__('Göreme', 'wpdev-locations'),
	__('Gülşehir', 'wpdev-locations'),
	__('Hacıbektaş', 'wpdev-locations'),
	__('Kozaklı İlçesi', 'wpdev-locations'),
	__('Merkez', 'wpdev-locations'),
	__('Nevşehir', 'wpdev-locations'),
	__('Ürgüp', 'wpdev-locations'),
);
