<?php // phpcs:ignore - @generation-checksum TR-51-6
/**
 * State City List for 51 - TR.
 *
 * City count: 6
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 51 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Altunhisar', 'wpdev-locations'),
	__('Bor', 'wpdev-locations'),
	__('Niğde', 'wpdev-locations'),
	__('Ulukisla', 'wpdev-locations'),
	__('Çamardı İlçesi', 'wpdev-locations'),
	__('Çiftlik', 'wpdev-locations'),
);
