<?php // phpcs:ignore - @generation-checksum TR-53-11
/**
 * State City List for 53 - TR.
 *
 * City count: 11
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 53 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ardeşen', 'wpdev-locations'),
	__('Fındıklı', 'wpdev-locations'),
	__('Güneysu', 'wpdev-locations'),
	__('Hemşin İlçesi', 'wpdev-locations'),
	__('Kalkandere', 'wpdev-locations'),
	__('Nurluca', 'wpdev-locations'),
	__('Pazar', 'wpdev-locations'),
	__('Rize', 'wpdev-locations'),
	__('Çayeli', 'wpdev-locations'),
	__('İkizdere İlçesi', 'wpdev-locations'),
	__('İyidere', 'wpdev-locations'),
);
