<?php // phpcs:ignore - @generation-checksum TR-56-22
/**
 * State City List for 56 - TR.
 *
 * City count: 22
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 56 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Baykan', 'wpdev-locations'),
	__('Civankan', 'wpdev-locations'),
	__('Doğanca', 'wpdev-locations'),
	__('Doğanköy', 'wpdev-locations'),
	__('Eruh', 'wpdev-locations'),
	__('Gökbudak', 'wpdev-locations'),
	__('Gökçekoru', 'wpdev-locations'),
	__('Gölgelikonak', 'wpdev-locations'),
	__('Gözpınar', 'wpdev-locations'),
	__('Güleçler', 'wpdev-locations'),
	__('Kayabağlar', 'wpdev-locations'),
	__('Kurtalan', 'wpdev-locations'),
	__('Lodi', 'wpdev-locations'),
	__('Okçular', 'wpdev-locations'),
	__('Palamutlu', 'wpdev-locations'),
	__('Pervari', 'wpdev-locations'),
	__('Serhatta', 'wpdev-locations'),
	__('Siirt', 'wpdev-locations'),
	__('Taliban', 'wpdev-locations'),
	__('Taşlı', 'wpdev-locations'),
	__('Tillo', 'wpdev-locations'),
	__('Şirvan', 'wpdev-locations'),
);
