<?php // phpcs:ignore - @generation-checksum TR-58-19
/**
 * State City List for 58 - TR.
 *
 * City count: 19
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 58 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aksu', 'wpdev-locations'),
	__('Akıncılar', 'wpdev-locations'),
	__('Altınyayla', 'wpdev-locations'),
	__('Divriği', 'wpdev-locations'),
	__('Doğanşar', 'wpdev-locations'),
	__('Gemerek', 'wpdev-locations'),
	__('Gölova', 'wpdev-locations'),
	__('Gürün', 'wpdev-locations'),
	__('Hafik', 'wpdev-locations'),
	__('Kangal', 'wpdev-locations'),
	__('Koyulhisar', 'wpdev-locations'),
	__('Merkez', 'wpdev-locations'),
	__('Sivas', 'wpdev-locations'),
	__('Suşehri', 'wpdev-locations'),
	__('Ulaş', 'wpdev-locations'),
	__('Yıldızeli İlçesi', 'wpdev-locations'),
	__('Zara', 'wpdev-locations'),
	__('İmranlı', 'wpdev-locations'),
	__('Şarkışla', 'wpdev-locations'),
);
