<?php // phpcs:ignore - @generation-checksum TR-60-12
/**
 * State City List for 60 - TR.
 *
 * City count: 12
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 60 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Almus', 'wpdev-locations'),
	__('Artova', 'wpdev-locations'),
	__('Başçiftlik', 'wpdev-locations'),
	__('Erbaa', 'wpdev-locations'),
	__('Niksar', 'wpdev-locations'),
	__('Pazar', 'wpdev-locations'),
	__('Reşadiye', 'wpdev-locations'),
	__('Sulusaray', 'wpdev-locations'),
	__('Tokat', 'wpdev-locations'),
	__('Turhal', 'wpdev-locations'),
	__('Yeşilyurt İlçesi', 'wpdev-locations'),
	__('Zile', 'wpdev-locations'),
);
