<?php // phpcs:ignore - @generation-checksum TR-63-31
/**
 * State City List for 63 - TR.
 *
 * City count: 31
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 63 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akdiken', 'wpdev-locations'),
	__('Akçakale', 'wpdev-locations'),
	__('Aşağı Beğdeş', 'wpdev-locations'),
	__('Birecik', 'wpdev-locations'),
	__('Bozova', 'wpdev-locations'),
	__('Bulutlu', 'wpdev-locations'),
	__('Ceylanpınar', 'wpdev-locations'),
	__('Dorumali', 'wpdev-locations'),
	__('Eyyübiye', 'wpdev-locations'),
	__('Güneren', 'wpdev-locations'),
	__('Halfeti', 'wpdev-locations'),
	__('Haliliye', 'wpdev-locations'),
	__('Hanköy', 'wpdev-locations'),
	__('Harran', 'wpdev-locations'),
	__('Hilvan', 'wpdev-locations'),
	__('Işıklar', 'wpdev-locations'),
	__('Karaköprü', 'wpdev-locations'),
	__('Koyunluca', 'wpdev-locations'),
	__('Küçükkendirci', 'wpdev-locations'),
	__('Mağaralı', 'wpdev-locations'),
	__('Meydankapı', 'wpdev-locations'),
	__('Minare', 'wpdev-locations'),
	__('Muratlı', 'wpdev-locations'),
	__('Pekmezli', 'wpdev-locations'),
	__('Seksenören', 'wpdev-locations'),
	__('Siverek', 'wpdev-locations'),
	__('Suruç', 'wpdev-locations'),
	__('Viranşehir', 'wpdev-locations'),
	__('Yukarı Taşyalak', 'wpdev-locations'),
	__('Öncül', 'wpdev-locations'),
	__('Şanlıurfa', 'wpdev-locations'),
);
