<?php // phpcs:ignore - @generation-checksum TR-64-12
/**
 * State City List for 64 - TR.
 *
 * City count: 12
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 64 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Banaz', 'wpdev-locations'),
	__('Bölme', 'wpdev-locations'),
	__('Eşme', 'wpdev-locations'),
	__('Güllü', 'wpdev-locations'),
	__('Karahallı', 'wpdev-locations'),
	__('Kızılcasöğüt', 'wpdev-locations'),
	__('Merkez', 'wpdev-locations'),
	__('Selçikler', 'wpdev-locations'),
	__('Sivaslı', 'wpdev-locations'),
	__('Ulubey', 'wpdev-locations'),
	__('Uşak', 'wpdev-locations'),
	__('İlyaslı', 'wpdev-locations'),
);
