<?php // phpcs:ignore - @generation-checksum TR-65-15
/**
 * State City List for 65 - TR.
 *
 * City count: 15
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 65 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bahçesaray', 'wpdev-locations'),
	__('Başkale', 'wpdev-locations'),
	__('Edremit', 'wpdev-locations'),
	__('Erciş', 'wpdev-locations'),
	__('Gevaş', 'wpdev-locations'),
	__('Gürpınar', 'wpdev-locations'),
	__('Konalga', 'wpdev-locations'),
	__('Muradiye', 'wpdev-locations'),
	__('Saray', 'wpdev-locations'),
	__('Tuşpa', 'wpdev-locations'),
	__('Van', 'wpdev-locations'),
	__('Çaldıran', 'wpdev-locations'),
	__('Çatak İlçesi', 'wpdev-locations'),
	__('Özalp', 'wpdev-locations'),
	__('İpekyolu', 'wpdev-locations'),
);
