<?php // phpcs:ignore - @generation-checksum TR-66-15
/**
 * State City List for 66 - TR.
 *
 * City count: 15
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 66 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akdağmadeni', 'wpdev-locations'),
	__('Aydıncık', 'wpdev-locations'),
	__('Boğazlıyan İlçesi', 'wpdev-locations'),
	__('Kadışehri', 'wpdev-locations'),
	__('Saraykent', 'wpdev-locations'),
	__('Sarıkaya', 'wpdev-locations'),
	__('Sorgun', 'wpdev-locations'),
	__('Yenifakılı', 'wpdev-locations'),
	__('Yerköy', 'wpdev-locations'),
	__('Yozgat', 'wpdev-locations'),
	__('Çandır İlçesi', 'wpdev-locations'),
	__('Çayıralan', 'wpdev-locations'),
	__('Çekerek', 'wpdev-locations'),
	__('Şefaatli İlçesi', 'wpdev-locations'),
	__('Şefaatlı', 'wpdev-locations'),
);
