<?php // phpcs:ignore - @generation-checksum TR-68-9
/**
 * State City List for 68 - TR.
 *
 * City count: 9
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 68 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aksaray', 'wpdev-locations'),
	__('Ağaçören', 'wpdev-locations'),
	__('Eskil İlçesi', 'wpdev-locations'),
	__('Gülağaç İlçesi', 'wpdev-locations'),
	__('Güzelyurt', 'wpdev-locations'),
	__('Merkez', 'wpdev-locations'),
	__('Ortaköy', 'wpdev-locations'),
	__('Sarıyahşi', 'wpdev-locations'),
	__('Sultanhanı', 'wpdev-locations'),
);
