<?php // phpcs:ignore - @generation-checksum TR-69-4
/**
 * State City List for 69 - TR.
 *
 * City count: 4
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 69 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aydıntepe', 'wpdev-locations'),
	__('Bayburt', 'wpdev-locations'),
	__('Demirözü İlçesi', 'wpdev-locations'),
	__('Pulur', 'wpdev-locations'),
);
