<?php // phpcs:ignore - @generation-checksum TR-73-38
/**
 * State City List for 73 - TR.
 *
 * City count: 38
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 73 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Andaç', 'wpdev-locations'),
	__('Ballı', 'wpdev-locations'),
	__('Balveren', 'wpdev-locations'),
	__('Baraniferho', 'wpdev-locations'),
	__('Bağlıca', 'wpdev-locations'),
	__('Başaran', 'wpdev-locations'),
	__('Becuh', 'wpdev-locations'),
	__('Beytüşşebap', 'wpdev-locations'),
	__('Bisbin', 'wpdev-locations'),
	__('Bostancı', 'wpdev-locations'),
	__('Bozalan', 'wpdev-locations'),
	__('Boğazören', 'wpdev-locations'),
	__('Cizre', 'wpdev-locations'),
	__('Dicle', 'wpdev-locations'),
	__('Doruklu', 'wpdev-locations'),
	__('Düzova', 'wpdev-locations'),
	__('Girikbedro', 'wpdev-locations'),
	__('Güçlükonak İlçesi', 'wpdev-locations'),
	__('Hilal', 'wpdev-locations'),
	__('Kumçatı', 'wpdev-locations'),
	__('Kızılsu', 'wpdev-locations'),
	__('Mezraa', 'wpdev-locations'),
	__('Ortabağ', 'wpdev-locations'),
	__('Ortaköy', 'wpdev-locations'),
	__('Pınarbaşı', 'wpdev-locations'),
	__('Razvaliny Ayinvan', 'wpdev-locations'),
	__('Silopi', 'wpdev-locations'),
	__('Sulak', 'wpdev-locations'),
	__('Tililan', 'wpdev-locations'),
	__('Uludere', 'wpdev-locations'),
	__('Uzungeçit', 'wpdev-locations'),
	__('Yemişli', 'wpdev-locations'),
	__('Yeniköy', 'wpdev-locations'),
	__('Çalışkan', 'wpdev-locations'),
	__('Çardaklı', 'wpdev-locations'),
	__('İdil', 'wpdev-locations'),
	__('Şenoba', 'wpdev-locations'),
	__('Şırnak', 'wpdev-locations'),
);
