<?php // phpcs:ignore - @generation-checksum TR-76-3
/**
 * State City List for 76 - TR.
 *
 * City count: 3
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 76 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Iğdır', 'wpdev-locations'),
	__('Karakoyunlu', 'wpdev-locations'),
	__('Tuzluca İlçesi', 'wpdev-locations'),
);
