<?php // phpcs:ignore - @generation-checksum TR-77-12
/**
 * State City List for 77 - TR.
 *
 * City count: 12
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 77 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Altınova', 'wpdev-locations'),
	__('Armutlu İlçesi', 'wpdev-locations'),
	__('Kadıköy', 'wpdev-locations'),
	__('Kaytazdere', 'wpdev-locations'),
	__('Kocadere', 'wpdev-locations'),
	__('Koruköy', 'wpdev-locations'),
	__('Kılıç', 'wpdev-locations'),
	__('Taşköprü', 'wpdev-locations'),
	__('Termal İlçesi', 'wpdev-locations'),
	__('Yalova', 'wpdev-locations'),
	__('Çiftlikköy', 'wpdev-locations'),
	__('Çınarcık', 'wpdev-locations'),
);
