<?php // phpcs:ignore - @generation-checksum TR-78-7
/**
 * State City List for 78 - TR.
 *
 * City count: 7
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 78 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Eflani', 'wpdev-locations'),
	__('Eskipazar İlçesi', 'wpdev-locations'),
	__('Gözyeri', 'wpdev-locations'),
	__('Karabük', 'wpdev-locations'),
	__('Ovacık İlçesi', 'wpdev-locations'),
	__('Safranbolu', 'wpdev-locations'),
	__('Yenice', 'wpdev-locations'),
);
