<?php // phpcs:ignore - @generation-checksum TR-80-7
/**
 * State City List for 80 - TR.
 *
 * City count: 7
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 80 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bahçe İlçesi', 'wpdev-locations'),
	__('Düziçi İlçesi', 'wpdev-locations'),
	__('Hasanbeyli', 'wpdev-locations'),
	__('Kadirli', 'wpdev-locations'),
	__('Osmaniye', 'wpdev-locations'),
	__('Sumbas İlçesi', 'wpdev-locations'),
	__('Toprakkale', 'wpdev-locations'),
);
