<?php // phpcs:ignore - @generation-checksum TR-81-8
/**
 * State City List for 81 - TR.
 *
 * City count: 8
 *
 * @package WPDevFramework\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 81 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akçakoca', 'wpdev-locations'),
	__('Cumayeri İlçesi', 'wpdev-locations'),
	__('Düzce', 'wpdev-locations'),
	__('Gölyaka İlçesi', 'wpdev-locations'),
	__('Gümüşova İlçesi', 'wpdev-locations'),
	__('Kaynaşlı İlçesi', 'wpdev-locations'),
	__('Yığılca İlçesi', 'wpdev-locations'),
	__('Çilimli İlçesi', 'wpdev-locations'),
);
